export type PopularQuery = {
  query: string;
  href: string;
};

export const HOMEOWNER_POPULAR_QUERIES: PopularQuery[] = [
  { query: "drywall repair houston", href: "/trade/drywall-contractor/tx" },
  { query: "handyman montgomery county maryland", href: "/trade/handyman/md" },
  { query: "hvac contractors ri", href: "/trade/hvac/ri" },
  { query: "garage door repair utah", href: "/trade/garage-door/ut" },
  { query: "electrical contractors in maryland", href: "/trade/electrical/md" },
  { query: "fence installation", href: "/trade/fence-contractor" },
  {
    query: "wallpaper installation palm beach county florida",
    href: "/trade/wallpaper-installation/fl",
  },
  { query: "window repair wichita ks", href: "/trade/window-contractor/ks" },
  { query: "garage door repair near me", href: "/trade/garage-door" },
  { query: "gutter company", href: "/trade/gutter-contractor" },
  { query: "general contractor in arizona", href: "/trade/general-contractor/az" },
  { query: "iowa solar installers", href: "/trade/solar-contractor/ia" },
  { query: "deck repair", href: "/trade/deck-contractor" },
  { query: "bathroom remodeling", href: "/trade/bathroom-remodel" },
  { query: "kitchen remodeling", href: "/trade/kitchen-remodel" },
  { query: "gutter installation services", href: "/trade/gutter-contractor" },
  { query: "fence contractor", href: "/trade/fence-contractor" },
  { query: "lawn mowing near me", href: "/trade/landscaping" },
  { query: "cabinet painting near me", href: "/trade/cabinet-painting" },
  { query: "window installers", href: "/trade/window-contractor" },
  { query: "electrical contractor", href: "/trade/electrical" },
  { query: "gutter repair", href: "/trade/gutter-contractor" },
  { query: "drywall repair near me", href: "/trade/drywall-contractor" },
  { query: "fence company", href: "/trade/fence-contractor" },
  { query: "garage door repair", href: "/trade/garage-door" },
  { query: "cabinet painters", href: "/trade/cabinet-painting" },
  { query: "pool service", href: "/trade/pool-contractor" },
  { query: "commercial tree service", href: "/trade/tree-service" },
];

export const BUSINESS_POPULAR_QUERIES: PopularQuery[] = [
  { query: "trade scout", href: "/for-businesses" },
  { query: "tradescout", href: "/for-businesses" },
  { query: "trade scouts", href: "/for-businesses" },
  { query: "tradescouts", href: "/for-businesses" },
  { query: "small business contractors", href: "/for-businesses" },
  { query: "small business marketing for contractors", href: "/for-businesses" },
  { query: "how to get more local jobs for my business", href: "/for-businesses" },
  { query: "local service business growth", href: "/for-businesses" },
  { query: "small electrical company marketing", href: "/trade/electrical" },
  { query: "small hvac business leads", href: "/trade/hvac" },
  { query: "small plumbing business marketing", href: "/trade/plumbing" },
  { query: "small contractor jobs near me", href: "/trade/general-contractor" },
  { query: "insulation contractors denver co", href: "/trade/insulation-contractor/co" },
  { query: "electrical contractors illinois", href: "/trade/electrical/il" },
  { query: "maine electrical contractors", href: "/trade/electrical/me" },
  { query: "concrete contractors richmond va", href: "/trade/concrete-contractor/va" },
  { query: "masonry contractor", href: "/trade/masonry-contractor" },
  { query: "window replacement berks county", href: "/trade/window-contractor/pa" },
  { query: "flooring iowa", href: "/trade/hardwood-flooring/ia" },
  { query: "cleaning company galveston tx", href: "/trade/cleaning-services/tx" },
  { query: "pest control kent county de", href: "/trade/pest-control/de" },
  { query: "roofing contractors bristol va", href: "/trade/roofing/va" },
  { query: "plumbing contractors nj", href: "/trade/plumbing/nj" },
  { query: "network security services hawaii", href: "/trade" },
];
