import React, { useMemo } from "react";

export interface WatchdogInterventionView {
  id: string;
  type: "continue_project" | "unblock_action" | "objective_refresh" | "success_nudge";
  priority: number;
  urgency: "low" | "medium" | "high";
  title: string;
  body: string;
  ctaLabel: string;
  ctaRoute: string;
  reason?: string;
}

export interface WatchdogInterventionBannerProps {
  interventions: WatchdogInterventionView[];
  engagementScore?: number;
  inactivityHours?: number;
  onOpenIntervention?: (route: string, interventionId: string) => void;
  onDismissIntervention?: (interventionId: string) => void;
  className?: string;
}

function urgencyColor(urgency: WatchdogInterventionView["urgency"]): string {
  if (urgency === "high") return "var(--status-error)";
  if (urgency === "medium") return "var(--status-warning)";
  return "var(--status-success)";
}

function scoreLabel(score?: number): string {
  if (typeof score !== "number" || !Number.isFinite(score)) return "--";
  return `${Math.max(0, Math.min(100, Math.round(score)))}%`;
}

function inactivityLabel(hours?: number): string {
  if (typeof hours !== "number" || !Number.isFinite(hours) || hours < 0) return "recent";
  if (hours < 1) return "active now";
  if (hours < 24) return `${Math.round(hours)}h`;
  return `${Math.round(hours / 24)}d`;
}

/**
 * Banner for proactive success interventions generated by the watchdog service.
 */
export function WatchdogInterventionBanner({
  interventions,
  engagementScore,
  inactivityHours,
  onOpenIntervention,
  onDismissIntervention,
  className,
}: WatchdogInterventionBannerProps) {
  const top = useMemo(
    () => [...interventions].sort((a, b) => b.priority - a.priority)[0] ?? null,
    [interventions]
  );

  if (!top) return null;

  return (
    <aside
      className={className}
      style={{
        borderRadius: "12px",
        border: `1px solid ${urgencyColor(top.urgency)}`,
        padding: "12px",
        background:
          "linear-gradient(165deg, color-mix(in oklab, var(--surface-card) 97%, transparent), color-mix(in oklab, var(--surface-intermediate) 95%, transparent))",
      }}
    >
      <header className="mb-2 flex items-start justify-between gap-2">
        <div>
          <div
            className="text-[11px] uppercase tracking-wide"
            style={{ color: "var(--text-secondary)" }}
          >
            Success watchdog
          </div>
          <h4 className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
            {top.title}
          </h4>
        </div>

        <span
          className="rounded-full px-2 py-1 text-[11px] font-semibold"
          style={{
            color: "var(--ts-text-on-accent)",
            backgroundColor: urgencyColor(top.urgency),
          }}
        >
          {top.urgency.toUpperCase()}
        </span>
      </header>

      <p className="text-sm" style={{ color: "var(--text-secondary)" }}>
        {top.body}
      </p>

      <div className="mt-2 grid grid-cols-2 gap-2">
        <div
          className="rounded border px-2 py-2"
          style={{
            borderColor: "var(--border-subtle)",
            background: "color-mix(in oklab, var(--surface-intermediate) 92%, transparent)",
          }}
        >
          <div className="text-[11px]" style={{ color: "var(--text-secondary)" }}>
            Engagement
          </div>
          <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
            {scoreLabel(engagementScore)}
          </div>
        </div>

        <div
          className="rounded border px-2 py-2"
          style={{
            borderColor: "var(--border-subtle)",
            background: "color-mix(in oklab, var(--surface-intermediate) 92%, transparent)",
          }}
        >
          <div className="text-[11px]" style={{ color: "var(--text-secondary)" }}>
            Inactive
          </div>
          <div className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>
            {inactivityLabel(inactivityHours)}
          </div>
        </div>
      </div>

      <div className="mt-3 flex flex-wrap gap-2">
        <button
          type="button"
          className="rounded-md px-3 py-2 text-sm font-semibold"
          style={{
            color: "var(--ts-text-on-accent)",
            backgroundColor: "var(--theme-accent-primary)",
          }}
          onClick={() => onOpenIntervention?.(top.ctaRoute, top.id)}
        >
          {top.ctaLabel}
        </button>

        <button
          type="button"
          className="rounded-md border px-3 py-2 text-sm"
          style={{
            borderColor: "var(--border-subtle)",
            color: "var(--text-secondary)",
          }}
          onClick={() => onDismissIntervention?.(top.id)}
        >
          Dismiss
        </button>
      </div>

      {interventions.length > 1 && (
        <div className="mt-3">
          <div
            className="mb-1 text-[11px] uppercase tracking-wide"
            style={{ color: "var(--text-secondary)" }}
          >
            More suggestions
          </div>
          <div className="grid gap-1">
            {interventions.slice(1, 4).map((item) => (
              <button
                key={item.id}
                type="button"
                className="rounded border px-2 py-1.5 text-left text-xs"
                style={{
                  borderColor: "var(--border-subtle)",
                  color: "var(--text-primary)",
                  background: "color-mix(in oklab, var(--surface-card) 95%, transparent)",
                }}
                onClick={() => onOpenIntervention?.(item.ctaRoute, item.id)}
              >
                <span style={{ color: urgencyColor(item.urgency) }}>[{item.urgency}] </span>
                {item.title}
              </button>
            ))}
          </div>
        </div>
      )}
    </aside>
  );
}

export default WatchdogInterventionBanner;
