import fs from "fs";
import path from "path";
import { runtimePaths } from "../runtimePaths";
import { extractMarketplace } from "./extractors/marketplace";
import { extractContractors } from "./extractors/contractors";
import { extractHOA } from "./extractors/hoa";
import { extractGroups } from "./extractors/groups";
import { extractCounties } from "./extractors/counties";
import { extractPublicProfiles } from "./extractors/profiles";
import { extractFAQ } from "./extractors/faq";

const CACHE_DIR = runtimePaths.scoutAutogeneratedCache;

// Ensure cache directory exists
function ensureCacheDir() {
  if (!fs.existsSync(CACHE_DIR)) {
    fs.mkdirSync(CACHE_DIR, { recursive: true });
  }
}

/**
 * Write JSON data to cache file
 */
function writeCacheFile(filename: string, data: any) {
  const filepath = path.join(CACHE_DIR, filename);
  try {
    fs.writeFileSync(filepath, JSON.stringify(data, null, 2), "utf-8");
    console.log(`✓ Cache written: ${filename} (${data.length || Object.keys(data).length} items)`);
    return true;
  } catch (error) {
    console.error(`✗ Error writing cache ${filename}:`, error);
    return false;
  }
}

/**
 * Main crawler function
 * Extracts data from DB and writes to cache
 */
export async function runCrawler() {
  console.log("\n🚀 Starting crawler...");
  console.log(`Cache directory: ${CACHE_DIR}\n`);

  ensureCacheDir();

  const startTime = Date.now();
  let successCount = 0;
  let errorCount = 0;

  try {
    // Extract marketplace listings
    console.log("📦 Extracting marketplace listings...");
    const marketplace = await extractMarketplace();
    if (writeCacheFile("marketplace.json", marketplace)) successCount++;
    else errorCount++;

    // Extract contractors
    console.log("🔨 Extracting contractors...");
    const contractors = await extractContractors();
    if (writeCacheFile("contractors.json", contractors)) successCount++;
    else errorCount++;

    // Extract HOA
    console.log("🏘️  Extracting HOA...");
    const hoa = await extractHOA();
    if (writeCacheFile("hoa.json", hoa)) successCount++;
    else errorCount++;

    // Extract groups
    console.log("👥 Extracting community groups...");
    const groups = await extractGroups();
    if (writeCacheFile("groups.json", groups)) successCount++;
    else errorCount++;

    // Extract counties
    console.log("🗺️  Extracting counties...");
    const counties = await extractCounties();
    if (writeCacheFile("counties.json", counties)) successCount++;
    else errorCount++;

    // Extract public profiles
    console.log("👤 Extracting public profiles...");
    const profiles = await extractPublicProfiles();
    if (writeCacheFile("profiles_public.json", profiles)) successCount++;
    else errorCount++;

    // Extract FAQ
    console.log("❓ Extracting FAQ...");
    const faq = await extractFAQ();
    if (writeCacheFile("faq.json", faq)) successCount++;
    else errorCount++;

    // Write metadata
    const metadata = {
      lastCrawled: new Date().toISOString(),
      duration: Date.now() - startTime,
      successCount,
      errorCount,
      timestamp: Date.now(),
    };
    writeCacheFile("_metadata.json", metadata);

    const duration = Date.now() - startTime;
    console.log(`\n✅ Crawler complete in ${duration}ms`);
    console.log(`Success: ${successCount}, Errors: ${errorCount}\n`);

    return {
      success: true,
      duration,
      successCount,
      errorCount,
    };
  } catch (error) {
    console.error("❌ Crawler failed:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}
