FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_OPTIONS=--max-old-space-size=4096
RUN apk add --no-cache fontconfig ttf-dejavu

# Install dependencies deterministically from package-lock.json
COPY package.json package-lock.json ./
RUN npm ci

# Copy source (dockerignore will prevent huge/unneeded folders)
COPY . .

# Ensure optional knowledge folder exists even when excluded from Docker context
RUN mkdir -p /app/data

# Build client (dist/public) + bundle server (dist/index.js)
RUN set -eux; \
  HB_PID=""; \
  cleanup() { \
    if [ -n "${HB_PID}" ]; then \
      kill "${HB_PID}" 2>/dev/null || true; \
      wait "${HB_PID}" 2>/dev/null || true; \
    fi; \
  }; \
  trap cleanup EXIT; \
  (while true; do echo "[build-heartbeat] $(date -u +%Y-%m-%dT%H:%M:%SZ) npm run build still running..."; sleep 20; done) & HB_PID=$!; \
  npm run build

# Install the independently locked server/release dependency closure. Browser,
# mobile, test, and build packages never enter the production runner.
FROM node:20-alpine AS runtime-deps
WORKDIR /runtime
COPY runtime/package.json runtime/package-lock.json runtime/smoke-runtime-dependencies.mjs ./
RUN npm ci --omit=dev && node smoke-runtime-dependencies.mjs

# --- Production image ---
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV TRADESCOUT_RUNTIME_DIR=/app/runtime
ENV SCOUT_CACHE_DIR=/app/runtime/scout-cache
ENV UPLOAD_DIR=/app/runtime/uploads/public
ENV PRIVATE_UPLOAD_DIR=/app/runtime/uploads/private
RUN apk add --no-cache fontconfig ttf-dejavu

# Copy only what runtime needs
COPY --from=builder /app/dist ./dist
COPY --from=runtime-deps /runtime/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/runtime/package.json /app/runtime/package.json
COPY --from=builder /app/runtime/verify-built-runtime.mjs /app/runtime/verify-built-runtime.mjs
COPY --from=builder /app/runtime/run-release.mjs /app/runtime/run-release.mjs
COPY --from=builder /app/shared/database-url-security.mjs /app/runtime/database-url-security.mjs
COPY --from=builder /app/runtime/drizzle.config.mjs ./runtime/drizzle.config.mjs
# SQL and metadata are read by pre-deploy migrations and release health.
COPY --from=builder /app/migrations ./migrations
# Seed only the bounded Scout cache. Raw server/client/shared/scripts/docs/data
# source trees are intentionally absent from the immutable runner.
COPY --from=builder /app/server/cache ./runtime/scout-cache
RUN mkdir -p \
  /app/runtime/scout-cache/manual/bulk_uploads \
  /app/runtime/scout-cache/autogenerated \
  /app/runtime/uploads/public \
  /app/runtime/uploads/private && \
  node runtime/verify-built-runtime.mjs && \
  RENDER=false node dist/release/ensure-public-media-ready.mjs

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10m --retries=3 \
  CMD wget --no-verbose --tries=1 --spider "http://127.0.0.1:${PORT:-5000}/api/health" || exit 1

# Render normally verifies public media in pre-deploy. The runtime gate requires an
# exact-release marker in the selected existing object store and performs the same
# idempotent migration if Blueprint sync ever lags, so a container cannot become
# healthy with missing public inventory. The release launcher also upgrades every
# remote PostgreSQL URL to explicit verify-full certificate validation.
CMD ["sh", "-c", "node runtime/run-release.mjs ensure-public-media-ready scripts/ensure-public-media-ready.mjs && exec node dist/index.js"]
