#!/usr/bin/env powershell
# Quick Test Script for TradeScout AI Assistant System
# Usage: .\test-system.ps1

Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  TradeScout AI Assistant - Quick System Test              ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan

$baseUrl = "http://localhost:5000"
$apiUrl = "$baseUrl/api/assistant"
$healthUrl = "$baseUrl/api/assistant/health"

# Color definitions
$green = "Green"
$red = "Red"
$yellow = "Yellow"
$cyan = "Cyan"

function Test-Endpoint {
    param(
        [string]$name,
        [string]$url,
        [string]$method = "GET",
        [object]$body = $null
    )
    
    Write-Host "`n📋 Test: $name" -ForegroundColor $cyan
    
    try {
        if ($method -eq "GET") {
            $response = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 5
        } else {
            $response = Invoke-RestMethod -Uri $url -Method Post -Body $body -ContentType "application/json" -TimeoutSec 5
        }
        
        Write-Host "✅ Success" -ForegroundColor $green
        
        if ($response) {
            Write-Host "Response Preview:"
            if ($response.GetType().Name -eq "String") {
                Write-Host $response -ForegroundColor $yellow
            } else {
                $response | ConvertTo-Json | Write-Host -ForegroundColor $yellow
            }
        }
        
        return $true
    }
    catch {
        Write-Host "❌ Failed: $($_.Exception.Message)" -ForegroundColor $red
        return $false
    }
}

# Test 1: Health Check
Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor $cyan
Write-Host "LAYER 0: System Health" -ForegroundColor $cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor $cyan

$healthOk = Test-Endpoint "Health Check" $healthUrl "GET"

if (-not $healthOk) {
    Write-Host "`n❌ Server not responding. Is it running?" -ForegroundColor $red
    Write-Host "Start with: npm run dev" -ForegroundColor $yellow
    exit 1
}

# Test 2: Layer 1 - Manual Override
Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor $cyan
Write-Host "LAYER 1: Manual Overrides" -ForegroundColor $cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor $cyan

$body1 = @{ message = "hurricane preparation" } | ConvertTo-Json
$test1 = Test-Endpoint "Override Activation" $apiUrl "POST" $body1

# Test 3: Layer 2 - Cache Hit
Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor $cyan
Write-Host "LAYER 2: Auto-Generated Cache" -ForegroundColor $cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor $cyan

$body2 = @{ message = "Find contractors" } | ConvertTo-Json
$test2 = Test-Endpoint "Cache Query (Contractors)" $apiUrl "POST" $body2

# Test 4: County-Specific
Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor $cyan
Write-Host "COUNTY OVERRIDE: Harris County, Texas" -ForegroundColor $cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor $cyan

$body3 = @{
    message = "roofing in Houston"
    countyCode = "HARRIS"
    stateCode = "TX"
} | ConvertTo-Json
$test3 = Test-Endpoint "County Override" $apiUrl "POST" $body3

# Test 5: Cache Files
Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor $cyan
Write-Host "CACHE FILES: Status Check" -ForegroundColor $cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor $cyan

$cacheDir = "server/cache/autogenerated"
if (Test-Path $cacheDir) {
    Write-Host "✅ Cache directory exists" -ForegroundColor $green
    
    $files = Get-ChildItem $cacheDir -Filter "*.json"
    Write-Host "Cache files found: $($files.Count)" -ForegroundColor $yellow
    
    foreach ($file in $files) {
        $size = $file.Length
        Write-Host "  • $($file.Name) - $size bytes" -ForegroundColor $yellow
    }
} else {
    Write-Host "❌ Cache directory not found" -ForegroundColor $red
}

# Summary
Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor $cyan
Write-Host "TEST SUMMARY" -ForegroundColor $cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor $cyan

$results = @(
    @{name = "Health Check"; passed = $healthOk},
    @{name = "Layer 1 - Manual Override"; passed = $test1},
    @{name = "Layer 2 - Cache"; passed = $test2},
    @{name = "County Override"; passed = $test3}
)

$passCount = ($results | Where-Object { $_.passed } | Measure-Object).Count
$totalTests = $results.Count

foreach ($result in $results) {
    $status = if ($result.passed) { "✅ PASS" } else { "❌ FAIL" }
    Write-Host "$status - $($result.name)" -ForegroundColor $(if ($result.passed) { $green } else { $red })
}

Write-Host "`nResults: $passCount/$totalTests tests passed" -ForegroundColor $(if ($passCount -eq $totalTests) { $green } else { $yellow })

if ($passCount -eq $totalTests) {
    Write-Host "`n🎉 ALL SYSTEMS OPERATIONAL!" -ForegroundColor $green
    Write-Host "The AI Assistant system is ready for production." -ForegroundColor $green
    exit 0
} else {
    Write-Host "`n⚠️  Some tests failed. Check logs for details." -ForegroundColor $yellow
    exit 1
}
