import path from "node:path";

export type RuntimePathEnvironment = NodeJS.ProcessEnv;

export type TradeScoutRuntimePaths = {
  runtimeRoot: string;
  scoutCacheRoot: string;
  scoutManualCache: string;
  scoutAutogeneratedCache: string;
  scoutHybridIndex: string;
  publicUploads: string;
  privateUploads: string;
};

function configuredPath(value: unknown, cwd: string): string | null {
  const candidate = String(value || "").trim();
  if (!candidate) return null;
  return path.isAbsolute(candidate) ? path.normalize(candidate) : path.resolve(cwd, candidate);
}

export function resolveTradeScoutRuntimePaths(
  env: RuntimePathEnvironment = process.env,
  cwd = process.cwd()
): TradeScoutRuntimePaths {
  const workspaceRoot = path.resolve(cwd);
  const production = String(env.NODE_ENV || "").trim().toLowerCase() === "production";
  const runtimeRoot =
    configuredPath(env.TRADESCOUT_RUNTIME_DIR, workspaceRoot) ||
    (production ? path.resolve(workspaceRoot, "runtime") : workspaceRoot);
  const scoutCacheRoot =
    configuredPath(env.SCOUT_CACHE_DIR, workspaceRoot) ||
    (production
      ? path.join(runtimeRoot, "scout-cache")
      : path.join(workspaceRoot, "server", "cache"));
  const scoutManualCache =
    configuredPath(env.SCOUT_MANUAL_CACHE_DIR, workspaceRoot) || path.join(scoutCacheRoot, "manual");
  const scoutAutogeneratedCache =
    configuredPath(env.SCOUT_AUTOGENERATED_CACHE_DIR, workspaceRoot) ||
    path.join(scoutCacheRoot, "autogenerated");

  return {
    runtimeRoot,
    scoutCacheRoot,
    scoutManualCache,
    scoutAutogeneratedCache,
    scoutHybridIndex:
      configuredPath(env.SCOUT_HYBRID_INDEX_PATH, workspaceRoot) ||
      (production
        ? path.join(runtimeRoot, "scout-hybrid-index.v1.json")
        : path.join(workspaceRoot, "data", "scout-hybrid-index.v1.json")),
    publicUploads:
      configuredPath(env.UPLOAD_DIR, workspaceRoot) ||
      (production
        ? path.join(runtimeRoot, "uploads", "public")
        : path.join(workspaceRoot, "public", "uploads")),
    privateUploads:
      configuredPath(env.PRIVATE_UPLOAD_DIR, workspaceRoot) ||
      (production
        ? path.join(runtimeRoot, "uploads", "private")
        : path.join(workspaceRoot, "private", "uploads")),
  };
}

export const runtimePaths = resolveTradeScoutRuntimePaths();
