import { createHash, randomUUID } from "crypto";
import type { LisaFeedItem } from "../../shared/lisa";

/**
 * Scout 2.0 to LISA Converter
 * 
 * Transforms Scout 2.0 intelligence findings into LisaFeedItem format
 * so they can be consumed by LISA's decision engine.
 */

export interface ScoutIntelligenceFinding {
  type: "building_code" | "material_price" | "labor_rate" | "contractor_availability" | "market_condition" | "jurisdiction_change";
  county?: string;
  countyFips?: string;
  state?: string;
  trade?: string;
  headline: string;
  narrative: string;
  evidence: string[];
  confidence: "high" | "medium" | "low";
  freshnessMinutes?: number;
  sources: ("knowledge_base" | "local_data" | "web_search")[];
}

function priorityFromConfidence(confidence: "high" | "medium" | "low"): "critical" | "high" | "medium" | "low" {
  switch (confidence) {
    case "high":
      return "high";
    case "medium":
      return "medium";
    case "low":
      return "low";
    default:
      return "low";
  }
}

function buildScopeRef(county?: string, countyFips?: string, state?: string, trade?: string): string {
  if (countyFips) {
    return countyFips;
  }
  if (county && state) {
    return `${state.toUpperCase()}-${county}`;
  }
  if (trade) {
    return `trade:${trade}`;
  }
  return "global";
}

export function scoutFindingToLisaFeedItem(finding: ScoutIntelligenceFinding): LisaFeedItem {
  const scopeRef = buildScopeRef(finding.county, finding.countyFips, finding.state, finding.trade);
  const scopeType = finding.countyFips || (finding.county && finding.state) ? "county" : finding.trade ? "category" : "global";

  return {
    id: `scout-intelligence-${finding.type}-${scopeRef}-${randomUUID()}`,
    priority: priorityFromConfidence(finding.confidence),
    sourceKind: "scout_intelligence",
    headline: finding.headline,
    narrative: finding.narrative,
    evidence: [
      `scout_intelligence_type=${finding.type}`,
      `confidence=${finding.confidence}`,
      `sources=${finding.sources.join(",")}`,
      ...finding.evidence,
    ],
    freshnessMinutes: finding.freshnessMinutes ?? 60,
    scopeType: scopeType as any,
    scopeRef,
  };
}

export function scoutFindingsToLisaFeed(findings: ScoutIntelligenceFinding[]): LisaFeedItem[] {
  return findings.map(scoutFindingToLisaFeedItem);
}

/**
 * Example Scout findings that would be generated by Scout 2.0
 */
export function createExampleScoutFindings(): ScoutIntelligenceFinding[] {
  return [
    {
      type: "building_code",
      county: "Travis",
      countyFips: "48453",
      state: "TX",
      headline: "Deck permits now require 42-inch railings in Travis County",
      narrative:
        "Travis County updated building code effective 2026-05-01. All decks higher than 30 inches must have railings at least 42 inches tall. This is a 6-inch increase from the previous requirement. Why it matters: Contractors need to adjust deck designs immediately. What to do: Update project estimates and notify homeowners of the code change.",
      evidence: [
        "source=travis_county_building_dept",
        "code_section=IRC-2024-R312",
        "effective_date=2026-05-01",
        "change_type=requirement_increase",
      ],
      confidence: "high",
      freshnessMinutes: 15,
      sources: ["local_data", "knowledge_base"],
    },
    {
      type: "material_price",
      state: "TX",
      trade: "roofing",
      headline: "Asphalt shingle prices up 8% in Texas this week",
      narrative:
        "Material prices for 25-year asphalt shingles increased from $85/sq to $92/sq. This affects roofing project bids across Texas. Why it matters: Contractors need to adjust pricing for new quotes. What to do: Update material cost estimates in your system.",
      evidence: [
        "source=web_search",
        "material=asphalt_shingles",
        "grade=25_year",
        "old_price=85",
        "new_price=92",
        "change_pct=8.2",
      ],
      confidence: "medium",
      freshnessMinutes: 120,
      sources: ["web_search"],
    },
    {
      type: "contractor_availability",
      county: "Travis",
      countyFips: "48453",
      state: "TX",
      trade: "electrical",
      headline: "Licensed electricians in Travis County are at 85% utilization",
      narrative:
        "Scout analysis shows 85% of licensed electricians in Travis County are currently booked or have active projects. This is a 12% increase from last week. Why it matters: Homeowners may face longer wait times for electrical work. What to do: Highlight available electricians or suggest alternative trades.",
      evidence: [
        "source=knowledge_base",
        "analysis_type=contractor_utilization",
        "utilization_pct=85",
        "week_over_week_change=12",
      ],
      confidence: "high",
      freshnessMinutes: 30,
      sources: ["knowledge_base"],
    },
  ];
}
