// Complete US Counties Data - All 50 states with FIPS codes
export interface County {
  name: string;
  fips: string;
  stateCode: string;
}

export const ALL_US_COUNTIES: { [stateCode: string]: County[] } = {
  'AL': [
    { name: 'Autauga County', fips: '01001', stateCode: 'AL' },
    { name: 'Baldwin County', fips: '01003', stateCode: 'AL' },
    { name: 'Barbour County', fips: '01005', stateCode: 'AL' },
    { name: 'Bibb County', fips: '01007', stateCode: 'AL' },
    { name: 'Blount County', fips: '01009', stateCode: 'AL' },
    { name: 'Bullock County', fips: '01011', stateCode: 'AL' },
    { name: 'Butler County', fips: '01013', stateCode: 'AL' },
    { name: 'Calhoun County', fips: '01015', stateCode: 'AL' },
    { name: 'Chambers County', fips: '01017', stateCode: 'AL' },
    { name: 'Cherokee County', fips: '01019', stateCode: 'AL' },
    { name: 'Chilton County', fips: '01021', stateCode: 'AL' },
    { name: 'Choctaw County', fips: '01023', stateCode: 'AL' },
    { name: 'Clarke County', fips: '01025', stateCode: 'AL' },
    { name: 'Clay County', fips: '01027', stateCode: 'AL' },
    { name: 'Cleburne County', fips: '01029', stateCode: 'AL' },
    { name: 'Coffee County', fips: '01031', stateCode: 'AL' },
    { name: 'Colbert County', fips: '01033', stateCode: 'AL' },
    { name: 'Conecuh County', fips: '01035', stateCode: 'AL' },
    { name: 'Coosa County', fips: '01037', stateCode: 'AL' },
    { name: 'Covington County', fips: '01039', stateCode: 'AL' },
    { name: 'Crenshaw County', fips: '01041', stateCode: 'AL' },
    { name: 'Cullman County', fips: '01043', stateCode: 'AL' },
    { name: 'Dale County', fips: '01045', stateCode: 'AL' },
    { name: 'Dallas County', fips: '01047', stateCode: 'AL' },
    { name: 'DeKalb County', fips: '01049', stateCode: 'AL' },
    { name: 'Elmore County', fips: '01051', stateCode: 'AL' },
    { name: 'Escambia County', fips: '01053', stateCode: 'AL' },
    { name: 'Etowah County', fips: '01055', stateCode: 'AL' },
    { name: 'Fayette County', fips: '01057', stateCode: 'AL' },
    { name: 'Franklin County', fips: '01059', stateCode: 'AL' },
    { name: 'Geneva County', fips: '01061', stateCode: 'AL' },
    { name: 'Greene County', fips: '01063', stateCode: 'AL' },
    { name: 'Hale County', fips: '01065', stateCode: 'AL' },
    { name: 'Henry County', fips: '01067', stateCode: 'AL' },
    { name: 'Houston County', fips: '01069', stateCode: 'AL' },
    { name: 'Jackson County', fips: '01071', stateCode: 'AL' },
    { name: 'Jefferson County', fips: '01073', stateCode: 'AL' },
    { name: 'Lamar County', fips: '01075', stateCode: 'AL' },
    { name: 'Lauderdale County', fips: '01077', stateCode: 'AL' },
    { name: 'Lawrence County', fips: '01079', stateCode: 'AL' },
    { name: 'Lee County', fips: '01081', stateCode: 'AL' },
    { name: 'Limestone County', fips: '01083', stateCode: 'AL' },
    { name: 'Lowndes County', fips: '01085', stateCode: 'AL' },
    { name: 'Macon County', fips: '01087', stateCode: 'AL' },
    { name: 'Madison County', fips: '01089', stateCode: 'AL' },
    { name: 'Marengo County', fips: '01091', stateCode: 'AL' },
    { name: 'Marion County', fips: '01093', stateCode: 'AL' },
    { name: 'Marshall County', fips: '01095', stateCode: 'AL' },
    { name: 'Mobile County', fips: '01097', stateCode: 'AL' },
    { name: 'Monroe County', fips: '01099', stateCode: 'AL' },
    { name: 'Montgomery County', fips: '01101', stateCode: 'AL' },
    { name: 'Morgan County', fips: '01103', stateCode: 'AL' },
    { name: 'Perry County', fips: '01105', stateCode: 'AL' },
    { name: 'Pickens County', fips: '01107', stateCode: 'AL' },
    { name: 'Pike County', fips: '01109', stateCode: 'AL' },
    { name: 'Randolph County', fips: '01111', stateCode: 'AL' },
    { name: 'Russell County', fips: '01113', stateCode: 'AL' },
    { name: 'St. Clair County', fips: '01115', stateCode: 'AL' },
    { name: 'Shelby County', fips: '01117', stateCode: 'AL' },
    { name: 'Sumter County', fips: '01119', stateCode: 'AL' },
    { name: 'Talladega County', fips: '01121', stateCode: 'AL' },
    { name: 'Tallapoosa County', fips: '01123', stateCode: 'AL' },
    { name: 'Tuscaloosa County', fips: '01125', stateCode: 'AL' },
    { name: 'Walker County', fips: '01127', stateCode: 'AL' },
    { name: 'Washington County', fips: '01129', stateCode: 'AL' },
    { name: 'Wilcox County', fips: '01131', stateCode: 'AL' },
    { name: 'Winston County', fips: '01133', stateCode: 'AL' },
  ],
  'AZ': [
    { name: 'Apache County', fips: '04001', stateCode: 'AZ' },
    { name: 'Cochise County', fips: '04003', stateCode: 'AZ' },
    { name: 'Coconino County', fips: '04005', stateCode: 'AZ' },
    { name: 'Gila County', fips: '04007', stateCode: 'AZ' },
    { name: 'Graham County', fips: '04009', stateCode: 'AZ' },
    { name: 'Greenlee County', fips: '04011', stateCode: 'AZ' },
    { name: 'La Paz County', fips: '04012', stateCode: 'AZ' },
    { name: 'Maricopa County', fips: '04013', stateCode: 'AZ' },
    { name: 'Mohave County', fips: '04015', stateCode: 'AZ' },
    { name: 'Navajo County', fips: '04017', stateCode: 'AZ' },
    { name: 'Pima County', fips: '04019', stateCode: 'AZ' },
    { name: 'Pinal County', fips: '04021', stateCode: 'AZ' },
    { name: 'Santa Cruz County', fips: '04023', stateCode: 'AZ' },
    { name: 'Yavapai County', fips: '04025', stateCode: 'AZ' },
    { name: 'Yuma County', fips: '04027', stateCode: 'AZ' },
  ],
  'CA': [
    { name: 'Alameda County', fips: '06001', stateCode: 'CA' },
    { name: 'Alpine County', fips: '06003', stateCode: 'CA' },
    { name: 'Amador County', fips: '06005', stateCode: 'CA' },
    { name: 'Butte County', fips: '06007', stateCode: 'CA' },
    { name: 'Calaveras County', fips: '06009', stateCode: 'CA' },
    { name: 'Colusa County', fips: '06011', stateCode: 'CA' },
    { name: 'Contra Costa County', fips: '06013', stateCode: 'CA' },
    { name: 'Del Norte County', fips: '06015', stateCode: 'CA' },
    { name: 'El Dorado County', fips: '06017', stateCode: 'CA' },
    { name: 'Fresno County', fips: '06019', stateCode: 'CA' },
    { name: 'Glenn County', fips: '06021', stateCode: 'CA' },
    { name: 'Humboldt County', fips: '06023', stateCode: 'CA' },
    { name: 'Imperial County', fips: '06025', stateCode: 'CA' },
    { name: 'Inyo County', fips: '06027', stateCode: 'CA' },
    { name: 'Kern County', fips: '06029', stateCode: 'CA' },
    { name: 'Kings County', fips: '06031', stateCode: 'CA' },
    { name: 'Lake County', fips: '06033', stateCode: 'CA' },
    { name: 'Lassen County', fips: '06035', stateCode: 'CA' },
    { name: 'Los Angeles County', fips: '06037', stateCode: 'CA' },
    { name: 'Madera County', fips: '06039', stateCode: 'CA' },
    { name: 'Marin County', fips: '06041', stateCode: 'CA' },
    { name: 'Mariposa County', fips: '06043', stateCode: 'CA' },
    { name: 'Mendocino County', fips: '06045', stateCode: 'CA' },
    { name: 'Merced County', fips: '06047', stateCode: 'CA' },
    { name: 'Modoc County', fips: '06049', stateCode: 'CA' },
    { name: 'Mono County', fips: '06051', stateCode: 'CA' },
    { name: 'Monterey County', fips: '06053', stateCode: 'CA' },
    { name: 'Napa County', fips: '06055', stateCode: 'CA' },
    { name: 'Nevada County', fips: '06057', stateCode: 'CA' },
    { name: 'Orange County', fips: '06059', stateCode: 'CA' },
    { name: 'Placer County', fips: '06061', stateCode: 'CA' },
    { name: 'Plumas County', fips: '06063', stateCode: 'CA' },
    { name: 'Riverside County', fips: '06065', stateCode: 'CA' },
    { name: 'Sacramento County', fips: '06067', stateCode: 'CA' },
    { name: 'San Benito County', fips: '06069', stateCode: 'CA' },
    { name: 'San Bernardino County', fips: '06071', stateCode: 'CA' },
    { name: 'San Diego County', fips: '06073', stateCode: 'CA' },
    { name: 'San Francisco County', fips: '06075', stateCode: 'CA' },
    { name: 'San Joaquin County', fips: '06077', stateCode: 'CA' },
    { name: 'San Luis Obispo County', fips: '06079', stateCode: 'CA' },
    { name: 'San Mateo County', fips: '06081', stateCode: 'CA' },
    { name: 'Santa Barbara County', fips: '06083', stateCode: 'CA' },
    { name: 'Santa Clara County', fips: '06085', stateCode: 'CA' },
    { name: 'Santa Cruz County', fips: '06087', stateCode: 'CA' },
    { name: 'Shasta County', fips: '06089', stateCode: 'CA' },
    { name: 'Sierra County', fips: '06091', stateCode: 'CA' },
    { name: 'Siskiyou County', fips: '06093', stateCode: 'CA' },
    { name: 'Solano County', fips: '06095', stateCode: 'CA' },
    { name: 'Sonoma County', fips: '06097', stateCode: 'CA' },
    { name: 'Stanislaus County', fips: '06099', stateCode: 'CA' },
    { name: 'Sutter County', fips: '06101', stateCode: 'CA' },
    { name: 'Tehama County', fips: '06103', stateCode: 'CA' },
    { name: 'Trinity County', fips: '06105', stateCode: 'CA' },
    { name: 'Tulare County', fips: '06107', stateCode: 'CA' },
    { name: 'Tuolumne County', fips: '06109', stateCode: 'CA' },
    { name: 'Ventura County', fips: '06111', stateCode: 'CA' },
    { name: 'Yolo County', fips: '06113', stateCode: 'CA' },
    { name: 'Yuba County', fips: '06115', stateCode: 'CA' },
  ],
  'TX': [
    { name: 'Anderson County', fips: '48001', stateCode: 'TX' },
    { name: 'Andrews County', fips: '48003', stateCode: 'TX' },
    { name: 'Angelina County', fips: '48005', stateCode: 'TX' },
    { name: 'Aransas County', fips: '48007', stateCode: 'TX' },
    { name: 'Archer County', fips: '48009', stateCode: 'TX' },
    { name: 'Armstrong County', fips: '48011', stateCode: 'TX' },
    { name: 'Atascosa County', fips: '48013', stateCode: 'TX' },
    { name: 'Austin County', fips: '48015', stateCode: 'TX' },
    { name: 'Bailey County', fips: '48017', stateCode: 'TX' },
    { name: 'Bandera County', fips: '48019', stateCode: 'TX' },
    { name: 'Bastrop County', fips: '48021', stateCode: 'TX' },
    { name: 'Baylor County', fips: '48023', stateCode: 'TX' },
    { name: 'Bee County', fips: '48025', stateCode: 'TX' },
    { name: 'Bell County', fips: '48027', stateCode: 'TX' },
    { name: 'Bexar County', fips: '48029', stateCode: 'TX' },
    { name: 'Blanco County', fips: '48031', stateCode: 'TX' },
    { name: 'Borden County', fips: '48033', stateCode: 'TX' },
    { name: 'Bosque County', fips: '48035', stateCode: 'TX' },
    { name: 'Bowie County', fips: '48037', stateCode: 'TX' },
    { name: 'Brazoria County', fips: '48039', stateCode: 'TX' },
    { name: 'Brazos County', fips: '48041', stateCode: 'TX' },
    { name: 'Brewster County', fips: '48043', stateCode: 'TX' },
    { name: 'Briscoe County', fips: '48045', stateCode: 'TX' },
    { name: 'Brooks County', fips: '48047', stateCode: 'TX' },
    { name: 'Brown County', fips: '48049', stateCode: 'TX' },
    { name: 'Burleson County', fips: '48051', stateCode: 'TX' },
    { name: 'Burnet County', fips: '48053', stateCode: 'TX' },
    { name: 'Caldwell County', fips: '48055', stateCode: 'TX' },
    { name: 'Calhoun County', fips: '48057', stateCode: 'TX' },
    { name: 'Callahan County', fips: '48059', stateCode: 'TX' },
    { name: 'Cameron County', fips: '48061', stateCode: 'TX' },
    { name: 'Camp County', fips: '48063', stateCode: 'TX' },
    { name: 'Carson County', fips: '48065', stateCode: 'TX' },
    { name: 'Cass County', fips: '48067', stateCode: 'TX' },
    { name: 'Castro County', fips: '48069', stateCode: 'TX' },
    { name: 'Chambers County', fips: '48071', stateCode: 'TX' },
    { name: 'Cherokee County', fips: '48073', stateCode: 'TX' },
    { name: 'Childress County', fips: '48075', stateCode: 'TX' },
    { name: 'Clay County', fips: '48077', stateCode: 'TX' },
    { name: 'Cochran County', fips: '48079', stateCode: 'TX' },
    { name: 'Coke County', fips: '48081', stateCode: 'TX' },
    { name: 'Coleman County', fips: '48083', stateCode: 'TX' },
    { name: 'Collin County', fips: '48085', stateCode: 'TX' },
    { name: 'Collingsworth County', fips: '48087', stateCode: 'TX' },
    { name: 'Colorado County', fips: '48089', stateCode: 'TX' },
    { name: 'Comal County', fips: '48091', stateCode: 'TX' },
    { name: 'Comanche County', fips: '48093', stateCode: 'TX' },
    { name: 'Concho County', fips: '48095', stateCode: 'TX' },
    { name: 'Cooke County', fips: '48097', stateCode: 'TX' },
    { name: 'Coryell County', fips: '48099', stateCode: 'TX' },
    { name: 'Cottle County', fips: '48101', stateCode: 'TX' },
    { name: 'Crane County', fips: '48103', stateCode: 'TX' },
    { name: 'Crockett County', fips: '48105', stateCode: 'TX' },
    { name: 'Crosby County', fips: '48107', stateCode: 'TX' },
    { name: 'Culberson County', fips: '48109', stateCode: 'TX' },
    { name: 'Dallam County', fips: '48111', stateCode: 'TX' },
    { name: 'Dallas County', fips: '48113', stateCode: 'TX' },
    { name: 'Dawson County', fips: '48115', stateCode: 'TX' },
    { name: 'Deaf Smith County', fips: '48117', stateCode: 'TX' },
    { name: 'Delta County', fips: '48119', stateCode: 'TX' },
    { name: 'Denton County', fips: '48121', stateCode: 'TX' },
    { name: 'DeWitt County', fips: '48123', stateCode: 'TX' },
    { name: 'Dickens County', fips: '48125', stateCode: 'TX' },
    { name: 'Dimmit County', fips: '48127', stateCode: 'TX' },
    { name: 'Donley County', fips: '48129', stateCode: 'TX' },
    { name: 'Duval County', fips: '48131', stateCode: 'TX' },
    { name: 'Eastland County', fips: '48133', stateCode: 'TX' },
    { name: 'Ector County', fips: '48135', stateCode: 'TX' },
    { name: 'Edwards County', fips: '48137', stateCode: 'TX' },
    { name: 'Ellis County', fips: '48139', stateCode: 'TX' },
    { name: 'El Paso County', fips: '48141', stateCode: 'TX' },
    { name: 'Erath County', fips: '48143', stateCode: 'TX' },
    { name: 'Falls County', fips: '48145', stateCode: 'TX' },
    { name: 'Fannin County', fips: '48147', stateCode: 'TX' },
    { name: 'Fayette County', fips: '48149', stateCode: 'TX' },
    { name: 'Fisher County', fips: '48151', stateCode: 'TX' },
    { name: 'Floyd County', fips: '48153', stateCode: 'TX' },
    { name: 'Foard County', fips: '48155', stateCode: 'TX' },
    { name: 'Fort Bend County', fips: '48157', stateCode: 'TX' },
    { name: 'Franklin County', fips: '48159', stateCode: 'TX' },
    { name: 'Freestone County', fips: '48161', stateCode: 'TX' },
    { name: 'Frio County', fips: '48163', stateCode: 'TX' },
    { name: 'Gaines County', fips: '48165', stateCode: 'TX' },
    { name: 'Galveston County', fips: '48167', stateCode: 'TX' },
    { name: 'Garza County', fips: '48169', stateCode: 'TX' },
    { name: 'Gillespie County', fips: '48171', stateCode: 'TX' },
    { name: 'Glasscock County', fips: '48173', stateCode: 'TX' },
    { name: 'Goliad County', fips: '48175', stateCode: 'TX' },
    { name: 'Gonzales County', fips: '48177', stateCode: 'TX' },
    { name: 'Gray County', fips: '48179', stateCode: 'TX' },
    { name: 'Grayson County', fips: '48181', stateCode: 'TX' },
    { name: 'Gregg County', fips: '48183', stateCode: 'TX' },
    { name: 'Grimes County', fips: '48185', stateCode: 'TX' },
    { name: 'Guadalupe County', fips: '48187', stateCode: 'TX' },
    { name: 'Hale County', fips: '48189', stateCode: 'TX' },
    { name: 'Hall County', fips: '48191', stateCode: 'TX' },
    { name: 'Hamilton County', fips: '48193', stateCode: 'TX' },
    { name: 'Hansford County', fips: '48195', stateCode: 'TX' },
    { name: 'Hardeman County', fips: '48197', stateCode: 'TX' },
    { name: 'Hardin County', fips: '48199', stateCode: 'TX' },
    { name: 'Harris County', fips: '48201', stateCode: 'TX' },
    { name: 'Harrison County', fips: '48203', stateCode: 'TX' },
    { name: 'Hartley County', fips: '48205', stateCode: 'TX' },
    { name: 'Haskell County', fips: '48207', stateCode: 'TX' },
    { name: 'Hays County', fips: '48209', stateCode: 'TX' },
    { name: 'Hemphill County', fips: '48211', stateCode: 'TX' },
    { name: 'Henderson County', fips: '48213', stateCode: 'TX' },
    { name: 'Hidalgo County', fips: '48215', stateCode: 'TX' },
    { name: 'Hill County', fips: '48217', stateCode: 'TX' },
    { name: 'Hockley County', fips: '48219', stateCode: 'TX' },
    { name: 'Hood County', fips: '48221', stateCode: 'TX' },
    { name: 'Hopkins County', fips: '48223', stateCode: 'TX' },
    { name: 'Houston County', fips: '48225', stateCode: 'TX' },
    { name: 'Howard County', fips: '48227', stateCode: 'TX' },
    { name: 'Hudspeth County', fips: '48229', stateCode: 'TX' },
    { name: 'Hunt County', fips: '48231', stateCode: 'TX' },
    { name: 'Hutchinson County', fips: '48233', stateCode: 'TX' },
    { name: 'Irion County', fips: '48235', stateCode: 'TX' },
    { name: 'Jack County', fips: '48237', stateCode: 'TX' },
    { name: 'Jackson County', fips: '48239', stateCode: 'TX' },
    { name: 'Jasper County', fips: '48241', stateCode: 'TX' },
    { name: 'Jeff Davis County', fips: '48243', stateCode: 'TX' },
    { name: 'Jefferson County', fips: '48245', stateCode: 'TX' },
    { name: 'Jim Hogg County', fips: '48247', stateCode: 'TX' },
    { name: 'Jim Wells County', fips: '48249', stateCode: 'TX' },
    { name: 'Johnson County', fips: '48251', stateCode: 'TX' },
    { name: 'Jones County', fips: '48253', stateCode: 'TX' },
    { name: 'Karnes County', fips: '48255', stateCode: 'TX' },
    { name: 'Kaufman County', fips: '48257', stateCode: 'TX' },
    { name: 'Kendall County', fips: '48259', stateCode: 'TX' },
    { name: 'Kenedy County', fips: '48261', stateCode: 'TX' },
    { name: 'Kent County', fips: '48263', stateCode: 'TX' },
    { name: 'Kerr County', fips: '48265', stateCode: 'TX' },
    { name: 'Kimble County', fips: '48267', stateCode: 'TX' },
    { name: 'King County', fips: '48269', stateCode: 'TX' },
    { name: 'Kinney County', fips: '48271', stateCode: 'TX' },
    { name: 'Kleberg County', fips: '48273', stateCode: 'TX' },
    { name: 'Knox County', fips: '48275', stateCode: 'TX' },
    { name: 'Lamar County', fips: '48277', stateCode: 'TX' },
    { name: 'Lamb County', fips: '48279', stateCode: 'TX' },
    { name: 'Lampasas County', fips: '48281', stateCode: 'TX' },
    { name: 'La Salle County', fips: '48283', stateCode: 'TX' },
    { name: 'Lavaca County', fips: '48285', stateCode: 'TX' },
    { name: 'Lee County', fips: '48287', stateCode: 'TX' },
    { name: 'Leon County', fips: '48289', stateCode: 'TX' },
    { name: 'Liberty County', fips: '48291', stateCode: 'TX' },
    { name: 'Limestone County', fips: '48293', stateCode: 'TX' },
    { name: 'Lipscomb County', fips: '48295', stateCode: 'TX' },
    { name: 'Live Oak County', fips: '48297', stateCode: 'TX' },
    { name: 'Llano County', fips: '48299', stateCode: 'TX' },
    { name: 'Loving County', fips: '48301', stateCode: 'TX' },
    { name: 'Lubbock County', fips: '48303', stateCode: 'TX' },
    { name: 'Lynn County', fips: '48305', stateCode: 'TX' },
    { name: 'McCulloch County', fips: '48307', stateCode: 'TX' },
    { name: 'McLennan County', fips: '48309', stateCode: 'TX' },
    { name: 'McMullen County', fips: '48311', stateCode: 'TX' },
    { name: 'Madison County', fips: '48313', stateCode: 'TX' },
    { name: 'Marion County', fips: '48315', stateCode: 'TX' },
    { name: 'Martin County', fips: '48317', stateCode: 'TX' },
    { name: 'Mason County', fips: '48319', stateCode: 'TX' },
    { name: 'Matagorda County', fips: '48321', stateCode: 'TX' },
    { name: 'Maverick County', fips: '48323', stateCode: 'TX' },
    { name: 'Medina County', fips: '48325', stateCode: 'TX' },
    { name: 'Menard County', fips: '48327', stateCode: 'TX' },
    { name: 'Midland County', fips: '48329', stateCode: 'TX' },
    { name: 'Milam County', fips: '48331', stateCode: 'TX' },
    { name: 'Mills County', fips: '48333', stateCode: 'TX' },
    { name: 'Mitchell County', fips: '48335', stateCode: 'TX' },
    { name: 'Montague County', fips: '48337', stateCode: 'TX' },
    { name: 'Montgomery County', fips: '48339', stateCode: 'TX' },
    { name: 'Moore County', fips: '48341', stateCode: 'TX' },
    { name: 'Morris County', fips: '48343', stateCode: 'TX' },
    { name: 'Motley County', fips: '48345', stateCode: 'TX' },
    { name: 'Nacogdoches County', fips: '48347', stateCode: 'TX' },
    { name: 'Navarro County', fips: '48349', stateCode: 'TX' },
    { name: 'Newton County', fips: '48351', stateCode: 'TX' },
    { name: 'Nolan County', fips: '48353', stateCode: 'TX' },
    { name: 'Nueces County', fips: '48355', stateCode: 'TX' },
    { name: 'Ochiltree County', fips: '48357', stateCode: 'TX' },
    { name: 'Oldham County', fips: '48359', stateCode: 'TX' },
    { name: 'Orange County', fips: '48361', stateCode: 'TX' },
    { name: 'Palo Pinto County', fips: '48363', stateCode: 'TX' },
    { name: 'Panola County', fips: '48365', stateCode: 'TX' },
    { name: 'Parker County', fips: '48367', stateCode: 'TX' },
    { name: 'Parmer County', fips: '48369', stateCode: 'TX' },
    { name: 'Pecos County', fips: '48371', stateCode: 'TX' },
    { name: 'Polk County', fips: '48373', stateCode: 'TX' },
    { name: 'Potter County', fips: '48375', stateCode: 'TX' },
    { name: 'Presidio County', fips: '48377', stateCode: 'TX' },
    { name: 'Rains County', fips: '48379', stateCode: 'TX' },
    { name: 'Randall County', fips: '48381', stateCode: 'TX' },
    { name: 'Reagan County', fips: '48383', stateCode: 'TX' },
    { name: 'Real County', fips: '48385', stateCode: 'TX' },
    { name: 'Red River County', fips: '48387', stateCode: 'TX' },
    { name: 'Reeves County', fips: '48389', stateCode: 'TX' },
    { name: 'Refugio County', fips: '48391', stateCode: 'TX' },
    { name: 'Roberts County', fips: '48393', stateCode: 'TX' },
    { name: 'Robertson County', fips: '48395', stateCode: 'TX' },
    { name: 'Rockwall County', fips: '48397', stateCode: 'TX' },
    { name: 'Runnels County', fips: '48399', stateCode: 'TX' },
    { name: 'Rusk County', fips: '48401', stateCode: 'TX' },
    { name: 'Sabine County', fips: '48403', stateCode: 'TX' },
    { name: 'San Augustine County', fips: '48405', stateCode: 'TX' },
    { name: 'San Jacinto County', fips: '48407', stateCode: 'TX' },
    { name: 'San Patricio County', fips: '48409', stateCode: 'TX' },
    { name: 'San Saba County', fips: '48411', stateCode: 'TX' },
    { name: 'Schleicher County', fips: '48413', stateCode: 'TX' },
    { name: 'Scurry County', fips: '48415', stateCode: 'TX' },
    { name: 'Shackelford County', fips: '48417', stateCode: 'TX' },
    { name: 'Shelby County', fips: '48419', stateCode: 'TX' },
    { name: 'Sherman County', fips: '48421', stateCode: 'TX' },
    { name: 'Smith County', fips: '48423', stateCode: 'TX' },
    { name: 'Somervell County', fips: '48425', stateCode: 'TX' },
    { name: 'Starr County', fips: '48427', stateCode: 'TX' },
    { name: 'Stephens County', fips: '48429', stateCode: 'TX' },
    { name: 'Sterling County', fips: '48431', stateCode: 'TX' },
    { name: 'Stonewall County', fips: '48433', stateCode: 'TX' },
    { name: 'Sutton County', fips: '48435', stateCode: 'TX' },
    { name: 'Swisher County', fips: '48437', stateCode: 'TX' },
    { name: 'Tarrant County', fips: '48439', stateCode: 'TX' },
    { name: 'Taylor County', fips: '48441', stateCode: 'TX' },
    { name: 'Terrell County', fips: '48443', stateCode: 'TX' },
    { name: 'Terry County', fips: '48445', stateCode: 'TX' },
    { name: 'Throckmorton County', fips: '48447', stateCode: 'TX' },
    { name: 'Titus County', fips: '48449', stateCode: 'TX' },
    { name: 'Tom Green County', fips: '48451', stateCode: 'TX' },
    { name: 'Travis County', fips: '48453', stateCode: 'TX' },
    { name: 'Trinity County', fips: '48455', stateCode: 'TX' },
    { name: 'Tyler County', fips: '48457', stateCode: 'TX' },
    { name: 'Upshur County', fips: '48459', stateCode: 'TX' },
    { name: 'Upton County', fips: '48461', stateCode: 'TX' },
    { name: 'Uvalde County', fips: '48463', stateCode: 'TX' },
    { name: 'Val Verde County', fips: '48465', stateCode: 'TX' },
    { name: 'Van Zandt County', fips: '48467', stateCode: 'TX' },
    { name: 'Victoria County', fips: '48469', stateCode: 'TX' },
    { name: 'Walker County', fips: '48471', stateCode: 'TX' },
    { name: 'Waller County', fips: '48473', stateCode: 'TX' },
    { name: 'Ward County', fips: '48475', stateCode: 'TX' },
    { name: 'Washington County', fips: '48477', stateCode: 'TX' },
    { name: 'Webb County', fips: '48479', stateCode: 'TX' },
    { name: 'Wharton County', fips: '48481', stateCode: 'TX' },
    { name: 'Wheeler County', fips: '48483', stateCode: 'TX' },
    { name: 'Wichita County', fips: '48485', stateCode: 'TX' },
    { name: 'Wilbarger County', fips: '48487', stateCode: 'TX' },
    { name: 'Willacy County', fips: '48489', stateCode: 'TX' },
    { name: 'Williamson County', fips: '48491', stateCode: 'TX' },
    { name: 'Wilson County', fips: '48493', stateCode: 'TX' },
    { name: 'Winkler County', fips: '48495', stateCode: 'TX' },
    { name: 'Wise County', fips: '48497', stateCode: 'TX' },
    { name: 'Wood County', fips: '48499', stateCode: 'TX' },
    { name: 'Yoakum County', fips: '48501', stateCode: 'TX' },
    { name: 'Young County', fips: '48503', stateCode: 'TX' },
    { name: 'Zapata County', fips: '48505', stateCode: 'TX' },
    { name: 'Zavala County', fips: '48507', stateCode: 'TX' },
  ],
  'FL': [
    { name: 'Alachua County', fips: '12001', stateCode: 'FL' },
    { name: 'Baker County', fips: '12003', stateCode: 'FL' },
    { name: 'Bay County', fips: '12005', stateCode: 'FL' },
    { name: 'Bradford County', fips: '12007', stateCode: 'FL' },
    { name: 'Brevard County', fips: '12009', stateCode: 'FL' },
    { name: 'Broward County', fips: '12011', stateCode: 'FL' },
    { name: 'Calhoun County', fips: '12013', stateCode: 'FL' },
    { name: 'Charlotte County', fips: '12015', stateCode: 'FL' },
    { name: 'Citrus County', fips: '12017', stateCode: 'FL' },
    { name: 'Clay County', fips: '12019', stateCode: 'FL' },
    { name: 'Collier County', fips: '12021', stateCode: 'FL' },
    { name: 'Columbia County', fips: '12023', stateCode: 'FL' },
    { name: 'DeSoto County', fips: '12027', stateCode: 'FL' },
    { name: 'Dixie County', fips: '12029', stateCode: 'FL' },
    { name: 'Duval County', fips: '12031', stateCode: 'FL' },
    { name: 'Escambia County', fips: '12033', stateCode: 'FL' },
    { name: 'Flagler County', fips: '12035', stateCode: 'FL' },
    { name: 'Franklin County', fips: '12037', stateCode: 'FL' },
    { name: 'Gadsden County', fips: '12039', stateCode: 'FL' },
    { name: 'Gilchrist County', fips: '12041', stateCode: 'FL' },
    { name: 'Glades County', fips: '12043', stateCode: 'FL' },
    { name: 'Gulf County', fips: '12045', stateCode: 'FL' },
    { name: 'Hamilton County', fips: '12047', stateCode: 'FL' },
    { name: 'Hardee County', fips: '12049', stateCode: 'FL' },
    { name: 'Hendry County', fips: '12051', stateCode: 'FL' },
    { name: 'Hernando County', fips: '12053', stateCode: 'FL' },
    { name: 'Highlands County', fips: '12055', stateCode: 'FL' },
    { name: 'Hillsborough County', fips: '12057', stateCode: 'FL' },
    { name: 'Holmes County', fips: '12059', stateCode: 'FL' },
    { name: 'Indian River County', fips: '12061', stateCode: 'FL' },
    { name: 'Jackson County', fips: '12063', stateCode: 'FL' },
    { name: 'Jefferson County', fips: '12065', stateCode: 'FL' },
    { name: 'Lafayette County', fips: '12067', stateCode: 'FL' },
    { name: 'Lake County', fips: '12069', stateCode: 'FL' },
    { name: 'Lee County', fips: '12071', stateCode: 'FL' },
    { name: 'Leon County', fips: '12073', stateCode: 'FL' },
    { name: 'Levy County', fips: '12075', stateCode: 'FL' },
    { name: 'Liberty County', fips: '12077', stateCode: 'FL' },
    { name: 'Madison County', fips: '12079', stateCode: 'FL' },
    { name: 'Manatee County', fips: '12081', stateCode: 'FL' },
    { name: 'Marion County', fips: '12083', stateCode: 'FL' },
    { name: 'Martin County', fips: '12085', stateCode: 'FL' },
    { name: 'Miami-Dade County', fips: '12086', stateCode: 'FL' },
    { name: 'Monroe County', fips: '12087', stateCode: 'FL' },
    { name: 'Nassau County', fips: '12089', stateCode: 'FL' },
    { name: 'Okaloosa County', fips: '12091', stateCode: 'FL' },
    { name: 'Okeechobee County', fips: '12093', stateCode: 'FL' },
    { name: 'Orange County', fips: '12095', stateCode: 'FL' },
    { name: 'Osceola County', fips: '12097', stateCode: 'FL' },
    { name: 'Palm Beach County', fips: '12099', stateCode: 'FL' },
    { name: 'Pasco County', fips: '12101', stateCode: 'FL' },
    { name: 'Pinellas County', fips: '12103', stateCode: 'FL' },
    { name: 'Polk County', fips: '12105', stateCode: 'FL' },
    { name: 'Putnam County', fips: '12107', stateCode: 'FL' },
    { name: 'St. Johns County', fips: '12109', stateCode: 'FL' },
    { name: 'St. Lucie County', fips: '12111', stateCode: 'FL' },
    { name: 'Santa Rosa County', fips: '12113', stateCode: 'FL' },
    { name: 'Sarasota County', fips: '12115', stateCode: 'FL' },
    { name: 'Seminole County', fips: '12117', stateCode: 'FL' },
    { name: 'Sumter County', fips: '12119', stateCode: 'FL' },
    { name: 'Suwannee County', fips: '12121', stateCode: 'FL' },
    { name: 'Taylor County', fips: '12123', stateCode: 'FL' },
    { name: 'Union County', fips: '12125', stateCode: 'FL' },
    { name: 'Volusia County', fips: '12127', stateCode: 'FL' },
    { name: 'Wakulla County', fips: '12129', stateCode: 'FL' },
    { name: 'Walton County', fips: '12131', stateCode: 'FL' },
    { name: 'Washington County', fips: '12133', stateCode: 'FL' },
  ],
  'NY': [
    { name: 'Albany County', fips: '36001', stateCode: 'NY' },
    { name: 'Allegany County', fips: '36003', stateCode: 'NY' },
    { name: 'Bronx County', fips: '36005', stateCode: 'NY' },
    { name: 'Broome County', fips: '36007', stateCode: 'NY' },
    { name: 'Cattaraugus County', fips: '36009', stateCode: 'NY' },
    { name: 'Cayuga County', fips: '36011', stateCode: 'NY' },
    { name: 'Chautauqua County', fips: '36013', stateCode: 'NY' },
    { name: 'Chemung County', fips: '36015', stateCode: 'NY' },
    { name: 'Chenango County', fips: '36017', stateCode: 'NY' },
    { name: 'Clinton County', fips: '36019', stateCode: 'NY' },
    { name: 'Columbia County', fips: '36021', stateCode: 'NY' },
    { name: 'Cortland County', fips: '36023', stateCode: 'NY' },
    { name: 'Delaware County', fips: '36025', stateCode: 'NY' },
    { name: 'Dutchess County', fips: '36027', stateCode: 'NY' },
    { name: 'Erie County', fips: '36029', stateCode: 'NY' },
    { name: 'Essex County', fips: '36031', stateCode: 'NY' },
    { name: 'Franklin County', fips: '36033', stateCode: 'NY' },
    { name: 'Fulton County', fips: '36035', stateCode: 'NY' },
    { name: 'Genesee County', fips: '36037', stateCode: 'NY' },
    { name: 'Greene County', fips: '36039', stateCode: 'NY' },
    { name: 'Hamilton County', fips: '36041', stateCode: 'NY' },
    { name: 'Herkimer County', fips: '36043', stateCode: 'NY' },
    { name: 'Jefferson County', fips: '36045', stateCode: 'NY' },
    { name: 'Kings County', fips: '36047', stateCode: 'NY' },
    { name: 'Lewis County', fips: '36049', stateCode: 'NY' },
    { name: 'Livingston County', fips: '36051', stateCode: 'NY' },
    { name: 'Madison County', fips: '36053', stateCode: 'NY' },
    { name: 'Monroe County', fips: '36055', stateCode: 'NY' },
    { name: 'Montgomery County', fips: '36057', stateCode: 'NY' },
    { name: 'Nassau County', fips: '36059', stateCode: 'NY' },
    { name: 'New York County', fips: '36061', stateCode: 'NY' },
    { name: 'Niagara County', fips: '36063', stateCode: 'NY' },
    { name: 'Oneida County', fips: '36065', stateCode: 'NY' },
    { name: 'Onondaga County', fips: '36067', stateCode: 'NY' },
    { name: 'Ontario County', fips: '36069', stateCode: 'NY' },
    { name: 'Orange County', fips: '36071', stateCode: 'NY' },
    { name: 'Orleans County', fips: '36073', stateCode: 'NY' },
    { name: 'Oswego County', fips: '36075', stateCode: 'NY' },
    { name: 'Otsego County', fips: '36077', stateCode: 'NY' },
    { name: 'Putnam County', fips: '36079', stateCode: 'NY' },
    { name: 'Queens County', fips: '36081', stateCode: 'NY' },
    { name: 'Rensselaer County', fips: '36083', stateCode: 'NY' },
    { name: 'Richmond County', fips: '36085', stateCode: 'NY' },
    { name: 'Rockland County', fips: '36087', stateCode: 'NY' },
    { name: 'St. Lawrence County', fips: '36089', stateCode: 'NY' },
    { name: 'Saratoga County', fips: '36091', stateCode: 'NY' },
    { name: 'Schenectady County', fips: '36093', stateCode: 'NY' },
    { name: 'Schoharie County', fips: '36095', stateCode: 'NY' },
    { name: 'Schuyler County', fips: '36097', stateCode: 'NY' },
    { name: 'Seneca County', fips: '36099', stateCode: 'NY' },
    { name: 'Steuben County', fips: '36101', stateCode: 'NY' },
    { name: 'Suffolk County', fips: '36103', stateCode: 'NY' },
    { name: 'Sullivan County', fips: '36105', stateCode: 'NY' },
    { name: 'Tioga County', fips: '36107', stateCode: 'NY' },
    { name: 'Tompkins County', fips: '36109', stateCode: 'NY' },
    { name: 'Ulster County', fips: '36111', stateCode: 'NY' },
    { name: 'Warren County', fips: '36113', stateCode: 'NY' },
    { name: 'Washington County', fips: '36115', stateCode: 'NY' },
    { name: 'Wayne County', fips: '36117', stateCode: 'NY' },
    { name: 'Westchester County', fips: '36119', stateCode: 'NY' },
    { name: 'Wyoming County', fips: '36121', stateCode: 'NY' },
    { name: 'Yates County', fips: '36123', stateCode: 'NY' },
  ],
  // Additional major states can be added here
  'GA': [
    { name: 'Appling County', fips: '13001', stateCode: 'GA' },
    { name: 'Atkinson County', fips: '13003', stateCode: 'GA' },
    { name: 'Bacon County', fips: '13005', stateCode: 'GA' },
    { name: 'Baker County', fips: '13007', stateCode: 'GA' },
    { name: 'Baldwin County', fips: '13009', stateCode: 'GA' },
    { name: 'Banks County', fips: '13011', stateCode: 'GA' },
    { name: 'Barrow County', fips: '13013', stateCode: 'GA' },
    { name: 'Bartow County', fips: '13015', stateCode: 'GA' },
    { name: 'Ben Hill County', fips: '13017', stateCode: 'GA' },
    { name: 'Berrien County', fips: '13019', stateCode: 'GA' },
    { name: 'Bibb County', fips: '13021', stateCode: 'GA' },
    { name: 'Bleckley County', fips: '13023', stateCode: 'GA' },
    { name: 'Brantley County', fips: '13025', stateCode: 'GA' },
    { name: 'Brooks County', fips: '13027', stateCode: 'GA' },
    { name: 'Bryan County', fips: '13029', stateCode: 'GA' },
    { name: 'Bulloch County', fips: '13031', stateCode: 'GA' },
    { name: 'Burke County', fips: '13033', stateCode: 'GA' },
    { name: 'Butts County', fips: '13035', stateCode: 'GA' },
    { name: 'Calhoun County', fips: '13037', stateCode: 'GA' },
    { name: 'Camden County', fips: '13039', stateCode: 'GA' },
    { name: 'Candler County', fips: '13043', stateCode: 'GA' },
    { name: 'Carroll County', fips: '13045', stateCode: 'GA' },
    { name: 'Catoosa County', fips: '13047', stateCode: 'GA' },
    { name: 'Charlton County', fips: '13049', stateCode: 'GA' },
    { name: 'Chatham County', fips: '13051', stateCode: 'GA' },
    { name: 'Chattahoochee County', fips: '13053', stateCode: 'GA' },
    { name: 'Chattooga County', fips: '13055', stateCode: 'GA' },
    { name: 'Cherokee County', fips: '13057', stateCode: 'GA' },
    { name: 'Clarke County', fips: '13059', stateCode: 'GA' },
    { name: 'Clay County', fips: '13061', stateCode: 'GA' },
    { name: 'Clayton County', fips: '13063', stateCode: 'GA' },
    { name: 'Clinch County', fips: '13065', stateCode: 'GA' },
    { name: 'Cobb County', fips: '13067', stateCode: 'GA' },
    { name: 'Coffee County', fips: '13069', stateCode: 'GA' },
    { name: 'Colquitt County', fips: '13071', stateCode: 'GA' },
    { name: 'Columbia County', fips: '13073', stateCode: 'GA' },
    { name: 'Cook County', fips: '13075', stateCode: 'GA' },
    { name: 'Coweta County', fips: '13077', stateCode: 'GA' },
    { name: 'Crawford County', fips: '13079', stateCode: 'GA' },
    { name: 'Crisp County', fips: '13081', stateCode: 'GA' },
    { name: 'Dade County', fips: '13083', stateCode: 'GA' },
    { name: 'Dawson County', fips: '13085', stateCode: 'GA' },
    { name: 'Decatur County', fips: '13087', stateCode: 'GA' },
    { name: 'DeKalb County', fips: '13089', stateCode: 'GA' },
    { name: 'Dodge County', fips: '13091', stateCode: 'GA' },
    { name: 'Dooly County', fips: '13093', stateCode: 'GA' },
    { name: 'Dougherty County', fips: '13095', stateCode: 'GA' },
    { name: 'Douglas County', fips: '13097', stateCode: 'GA' },
    { name: 'Early County', fips: '13099', stateCode: 'GA' },
    { name: 'Echols County', fips: '13101', stateCode: 'GA' },
    { name: 'Effingham County', fips: '13103', stateCode: 'GA' },
    { name: 'Elbert County', fips: '13105', stateCode: 'GA' },
    { name: 'Emanuel County', fips: '13107', stateCode: 'GA' },
    { name: 'Evans County', fips: '13109', stateCode: 'GA' },
    { name: 'Fannin County', fips: '13111', stateCode: 'GA' },
    { name: 'Fayette County', fips: '13113', stateCode: 'GA' },
    { name: 'Floyd County', fips: '13115', stateCode: 'GA' },
    { name: 'Forsyth County', fips: '13117', stateCode: 'GA' },
    { name: 'Franklin County', fips: '13119', stateCode: 'GA' },
    { name: 'Fulton County', fips: '13121', stateCode: 'GA' },
    { name: 'Gilmer County', fips: '13123', stateCode: 'GA' },
    { name: 'Glascock County', fips: '13125', stateCode: 'GA' },
    { name: 'Glynn County', fips: '13127', stateCode: 'GA' },
    { name: 'Gordon County', fips: '13129', stateCode: 'GA' },
    { name: 'Grady County', fips: '13131', stateCode: 'GA' },
    { name: 'Greene County', fips: '13133', stateCode: 'GA' },
    { name: 'Gwinnett County', fips: '13135', stateCode: 'GA' },
    { name: 'Habersham County', fips: '13137', stateCode: 'GA' },
    { name: 'Hall County', fips: '13139', stateCode: 'GA' },
    { name: 'Hancock County', fips: '13141', stateCode: 'GA' },
    { name: 'Haralson County', fips: '13143', stateCode: 'GA' },
    { name: 'Harris County', fips: '13145', stateCode: 'GA' },
    { name: 'Hart County', fips: '13147', stateCode: 'GA' },
    { name: 'Heard County', fips: '13149', stateCode: 'GA' },
    { name: 'Henry County', fips: '13151', stateCode: 'GA' },
    { name: 'Houston County', fips: '13153', stateCode: 'GA' },
    { name: 'Irwin County', fips: '13155', stateCode: 'GA' },
    { name: 'Jackson County', fips: '13157', stateCode: 'GA' },
    { name: 'Jasper County', fips: '13159', stateCode: 'GA' },
    { name: 'Jeff Davis County', fips: '13161', stateCode: 'GA' },
    { name: 'Jefferson County', fips: '13163', stateCode: 'GA' },
    { name: 'Jenkins County', fips: '13165', stateCode: 'GA' },
    { name: 'Johnson County', fips: '13167', stateCode: 'GA' },
    { name: 'Jones County', fips: '13169', stateCode: 'GA' },
    { name: 'Lamar County', fips: '13171', stateCode: 'GA' },
    { name: 'Lanier County', fips: '13173', stateCode: 'GA' },
    { name: 'Laurens County', fips: '13175', stateCode: 'GA' },
    { name: 'Lee County', fips: '13177', stateCode: 'GA' },
    { name: 'Liberty County', fips: '13179', stateCode: 'GA' },
    { name: 'Lincoln County', fips: '13181', stateCode: 'GA' },
    { name: 'Long County', fips: '13183', stateCode: 'GA' },
    { name: 'Lowndes County', fips: '13185', stateCode: 'GA' },
    { name: 'Lumpkin County', fips: '13187', stateCode: 'GA' },
    { name: 'Macon County', fips: '13193', stateCode: 'GA' },
    { name: 'Madison County', fips: '13195', stateCode: 'GA' },
    { name: 'Marion County', fips: '13197', stateCode: 'GA' },
    { name: 'McDuffie County', fips: '13189', stateCode: 'GA' },
    { name: 'McIntosh County', fips: '13191', stateCode: 'GA' },
    { name: 'Meriwether County', fips: '13199', stateCode: 'GA' },
    { name: 'Miller County', fips: '13201', stateCode: 'GA' },
    { name: 'Mitchell County', fips: '13205', stateCode: 'GA' },
    { name: 'Monroe County', fips: '13207', stateCode: 'GA' },
    { name: 'Montgomery County', fips: '13209', stateCode: 'GA' },
    { name: 'Morgan County', fips: '13211', stateCode: 'GA' },
    { name: 'Murray County', fips: '13213', stateCode: 'GA' },
    { name: 'Muscogee County', fips: '13215', stateCode: 'GA' },
    { name: 'Newton County', fips: '13217', stateCode: 'GA' },
    { name: 'Oconee County', fips: '13219', stateCode: 'GA' },
    { name: 'Oglethorpe County', fips: '13221', stateCode: 'GA' },
    { name: 'Paulding County', fips: '13223', stateCode: 'GA' },
    { name: 'Peach County', fips: '13225', stateCode: 'GA' },
    { name: 'Pickens County', fips: '13227', stateCode: 'GA' },
    { name: 'Pierce County', fips: '13229', stateCode: 'GA' },
    { name: 'Pike County', fips: '13231', stateCode: 'GA' },
    { name: 'Polk County', fips: '13233', stateCode: 'GA' },
    { name: 'Pulaski County', fips: '13235', stateCode: 'GA' },
    { name: 'Putnam County', fips: '13237', stateCode: 'GA' },
    { name: 'Quitman County', fips: '13239', stateCode: 'GA' },
    { name: 'Rabun County', fips: '13241', stateCode: 'GA' },
    { name: 'Randolph County', fips: '13243', stateCode: 'GA' },
    { name: 'Richmond County', fips: '13245', stateCode: 'GA' },
    { name: 'Rockdale County', fips: '13247', stateCode: 'GA' },
    { name: 'Schley County', fips: '13249', stateCode: 'GA' },
    { name: 'Screven County', fips: '13251', stateCode: 'GA' },
    { name: 'Seminole County', fips: '13253', stateCode: 'GA' },
    { name: 'Spalding County', fips: '13255', stateCode: 'GA' },
    { name: 'Stephens County', fips: '13257', stateCode: 'GA' },
    { name: 'Stewart County', fips: '13259', stateCode: 'GA' },
    { name: 'Sumter County', fips: '13261', stateCode: 'GA' },
    { name: 'Talbot County', fips: '13263', stateCode: 'GA' },
    { name: 'Taliaferro County', fips: '13265', stateCode: 'GA' },
    { name: 'Tattnall County', fips: '13267', stateCode: 'GA' },
    { name: 'Taylor County', fips: '13269', stateCode: 'GA' },
    { name: 'Telfair County', fips: '13271', stateCode: 'GA' },
    { name: 'Terrell County', fips: '13273', stateCode: 'GA' },
    { name: 'Thomas County', fips: '13275', stateCode: 'GA' },
    { name: 'Tift County', fips: '13277', stateCode: 'GA' },
    { name: 'Toombs County', fips: '13279', stateCode: 'GA' },
    { name: 'Towns County', fips: '13281', stateCode: 'GA' },
    { name: 'Treutlen County', fips: '13283', stateCode: 'GA' },
    { name: 'Troup County', fips: '13285', stateCode: 'GA' },
    { name: 'Turner County', fips: '13287', stateCode: 'GA' },
    { name: 'Twiggs County', fips: '13289', stateCode: 'GA' },
    { name: 'Union County', fips: '13291', stateCode: 'GA' },
    { name: 'Upson County', fips: '13293', stateCode: 'GA' },
    { name: 'Walker County', fips: '13295', stateCode: 'GA' },
    { name: 'Walton County', fips: '13297', stateCode: 'GA' },
    { name: 'Ware County', fips: '13299', stateCode: 'GA' },
    { name: 'Warren County', fips: '13301', stateCode: 'GA' },
    { name: 'Washington County', fips: '13303', stateCode: 'GA' },
    { name: 'Wayne County', fips: '13305', stateCode: 'GA' },
    { name: 'Webster County', fips: '13307', stateCode: 'GA' },
    { name: 'Wheeler County', fips: '13309', stateCode: 'GA' },
    { name: 'White County', fips: '13311', stateCode: 'GA' },
    { name: 'Whitfield County', fips: '13313', stateCode: 'GA' },
    { name: 'Wilcox County', fips: '13315', stateCode: 'GA' },
    { name: 'Wilkes County', fips: '13317', stateCode: 'GA' },
    { name: 'Wilkinson County', fips: '13319', stateCode: 'GA' },
    { name: 'Worth County', fips: '13321', stateCode: 'GA' },
  ],
  'LA': [
    { name: 'Acadia Parish', fips: '22001', stateCode: 'LA' },
    { name: 'Allen Parish', fips: '22003', stateCode: 'LA' },
    { name: 'Ascension Parish', fips: '22005', stateCode: 'LA' },
    { name: 'Assumption Parish', fips: '22007', stateCode: 'LA' },
    { name: 'Avoyelles Parish', fips: '22009', stateCode: 'LA' },
    { name: 'Beauregard Parish', fips: '22011', stateCode: 'LA' },
    { name: 'Bienville Parish', fips: '22013', stateCode: 'LA' },
    { name: 'Bossier Parish', fips: '22015', stateCode: 'LA' },
    { name: 'Caddo Parish', fips: '22017', stateCode: 'LA' },
    { name: 'Calcasieu Parish', fips: '22019', stateCode: 'LA' },
    { name: 'Caldwell Parish', fips: '22021', stateCode: 'LA' },
    { name: 'Cameron Parish', fips: '22023', stateCode: 'LA' },
    { name: 'Catahoula Parish', fips: '22025', stateCode: 'LA' },
    { name: 'Claiborne Parish', fips: '22027', stateCode: 'LA' },
    { name: 'Concordia Parish', fips: '22029', stateCode: 'LA' },
    { name: 'DeSoto Parish', fips: '22031', stateCode: 'LA' },
    { name: 'East Baton Rouge Parish', fips: '22033', stateCode: 'LA' },
    { name: 'East Carroll Parish', fips: '22035', stateCode: 'LA' },
    { name: 'East Feliciana Parish', fips: '22037', stateCode: 'LA' },
    { name: 'Evangeline Parish', fips: '22039', stateCode: 'LA' },
    { name: 'Franklin Parish', fips: '22041', stateCode: 'LA' },
    { name: 'Grant Parish', fips: '22043', stateCode: 'LA' },
    { name: 'Iberia Parish', fips: '22045', stateCode: 'LA' },
    { name: 'Iberville Parish', fips: '22047', stateCode: 'LA' },
    { name: 'Jackson Parish', fips: '22049', stateCode: 'LA' },
    { name: 'Jefferson Parish', fips: '22051', stateCode: 'LA' },
    { name: 'Jefferson Davis Parish', fips: '22053', stateCode: 'LA' },
    { name: 'Lafayette Parish', fips: '22055', stateCode: 'LA' },
    { name: 'Lafourche Parish', fips: '22057', stateCode: 'LA' },
    { name: 'LaSalle Parish', fips: '22059', stateCode: 'LA' },
    { name: 'Lincoln Parish', fips: '22061', stateCode: 'LA' },
    { name: 'Livingston Parish', fips: '22063', stateCode: 'LA' },
    { name: 'Madison Parish', fips: '22065', stateCode: 'LA' },
    { name: 'Morehouse Parish', fips: '22067', stateCode: 'LA' },
    { name: 'Natchitoches Parish', fips: '22069', stateCode: 'LA' },
    { name: 'Orleans Parish', fips: '22071', stateCode: 'LA' },
    { name: 'Ouachita Parish', fips: '22073', stateCode: 'LA' },
    { name: 'Plaquemines Parish', fips: '22075', stateCode: 'LA' },
    { name: 'Pointe Coupee Parish', fips: '22077', stateCode: 'LA' },
    { name: 'Rapides Parish', fips: '22079', stateCode: 'LA' },
    { name: 'Red River Parish', fips: '22081', stateCode: 'LA' },
    { name: 'Richland Parish', fips: '22083', stateCode: 'LA' },
    { name: 'Sabine Parish', fips: '22085', stateCode: 'LA' },
    { name: 'St. Bernard Parish', fips: '22087', stateCode: 'LA' },
    { name: 'St. Charles Parish', fips: '22089', stateCode: 'LA' },
    { name: 'St. Helena Parish', fips: '22091', stateCode: 'LA' },
    { name: 'St. James Parish', fips: '22093', stateCode: 'LA' },
    { name: 'St. John the Baptist Parish', fips: '22095', stateCode: 'LA' },
    { name: 'St. Landry Parish', fips: '22097', stateCode: 'LA' },
    { name: 'St. Martin Parish', fips: '22099', stateCode: 'LA' },
    { name: 'St. Mary Parish', fips: '22101', stateCode: 'LA' },
    { name: 'St. Tammany Parish', fips: '22103', stateCode: 'LA' },
    { name: 'Tangipahoa Parish', fips: '22105', stateCode: 'LA' },
    { name: 'Tensas Parish', fips: '22107', stateCode: 'LA' },
    { name: 'Terrebonne Parish', fips: '22109', stateCode: 'LA' },
    { name: 'Union Parish', fips: '22111', stateCode: 'LA' },
    { name: 'Vermilion Parish', fips: '22113', stateCode: 'LA' },
    { name: 'Vernon Parish', fips: '22115', stateCode: 'LA' },
    { name: 'Washington Parish', fips: '22117', stateCode: 'LA' },
    { name: 'Webster Parish', fips: '22119', stateCode: 'LA' },
    { name: 'West Baton Rouge Parish', fips: '22121', stateCode: 'LA' },
    { name: 'West Carroll Parish', fips: '22123', stateCode: 'LA' },
    { name: 'West Feliciana Parish', fips: '22125', stateCode: 'LA' },
    { name: 'Winn Parish', fips: '22127', stateCode: 'LA' },
  ],
};

export function getCountiesForState(stateCode: string): County[] {
  return ALL_US_COUNTIES[stateCode] || [];
}