// US States and Territories with comprehensive county/parish/borough data
export interface State {
  code: string;
  name: string;
  subdivisionType: 'county' | 'parish' | 'borough' | 'census area' | 'municipality' | 'district';
}

export interface County {
  name: string;
  fips: string;
  stateCode: string;
}

export const US_STATES: State[] = [
  { code: 'AL', name: 'Alabama', subdivisionType: 'county' },
  { code: 'AK', name: 'Alaska', subdivisionType: 'borough' },
  { code: 'AZ', name: 'Arizona', subdivisionType: 'county' },
  { code: 'AR', name: 'Arkansas', subdivisionType: 'county' },
  { code: 'CA', name: 'California', subdivisionType: 'county' },
  { code: 'CO', name: 'Colorado', subdivisionType: 'county' },
  { code: 'CT', name: 'Connecticut', subdivisionType: 'county' },
  { code: 'DE', name: 'Delaware', subdivisionType: 'county' },
  { code: 'FL', name: 'Florida', subdivisionType: 'county' },
  { code: 'GA', name: 'Georgia', subdivisionType: 'county' },
  { code: 'HI', name: 'Hawaii', subdivisionType: 'county' },
  { code: 'ID', name: 'Idaho', subdivisionType: 'county' },
  { code: 'IL', name: 'Illinois', subdivisionType: 'county' },
  { code: 'IN', name: 'Indiana', subdivisionType: 'county' },
  { code: 'IA', name: 'Iowa', subdivisionType: 'county' },
  { code: 'KS', name: 'Kansas', subdivisionType: 'county' },
  { code: 'KY', name: 'Kentucky', subdivisionType: 'county' },
  { code: 'LA', name: 'Louisiana', subdivisionType: 'parish' },
  { code: 'ME', name: 'Maine', subdivisionType: 'county' },
  { code: 'MD', name: 'Maryland', subdivisionType: 'county' },
  { code: 'MA', name: 'Massachusetts', subdivisionType: 'county' },
  { code: 'MI', name: 'Michigan', subdivisionType: 'county' },
  { code: 'MN', name: 'Minnesota', subdivisionType: 'county' },
  { code: 'MS', name: 'Mississippi', subdivisionType: 'county' },
  { code: 'MO', name: 'Missouri', subdivisionType: 'county' },
  { code: 'MT', name: 'Montana', subdivisionType: 'county' },
  { code: 'NE', name: 'Nebraska', subdivisionType: 'county' },
  { code: 'NV', name: 'Nevada', subdivisionType: 'county' },
  { code: 'NH', name: 'New Hampshire', subdivisionType: 'county' },
  { code: 'NJ', name: 'New Jersey', subdivisionType: 'county' },
  { code: 'NM', name: 'New Mexico', subdivisionType: 'county' },
  { code: 'NY', name: 'New York', subdivisionType: 'county' },
  { code: 'NC', name: 'North Carolina', subdivisionType: 'county' },
  { code: 'ND', name: 'North Dakota', subdivisionType: 'county' },
  { code: 'OH', name: 'Ohio', subdivisionType: 'county' },
  { code: 'OK', name: 'Oklahoma', subdivisionType: 'county' },
  { code: 'OR', name: 'Oregon', subdivisionType: 'county' },
  { code: 'PA', name: 'Pennsylvania', subdivisionType: 'county' },
  { code: 'RI', name: 'Rhode Island', subdivisionType: 'county' },
  { code: 'SC', name: 'South Carolina', subdivisionType: 'county' },
  { code: 'SD', name: 'South Dakota', subdivisionType: 'county' },
  { code: 'TN', name: 'Tennessee', subdivisionType: 'county' },
  { code: 'TX', name: 'Texas', subdivisionType: 'county' },
  { code: 'UT', name: 'Utah', subdivisionType: 'county' },
  { code: 'VT', name: 'Vermont', subdivisionType: 'county' },
  { code: 'VA', name: 'Virginia', subdivisionType: 'county' },
  { code: 'WA', name: 'Washington', subdivisionType: 'county' },
  { code: 'WV', name: 'West Virginia', subdivisionType: 'county' },
  { code: 'WI', name: 'Wisconsin', subdivisionType: 'county' },
  { code: 'WY', name: 'Wyoming', subdivisionType: 'county' },
  // US Territories
  { code: 'DC', name: 'District of Columbia', subdivisionType: 'district' },
  { code: 'AS', name: 'American Samoa', subdivisionType: 'district' },
  { code: 'GU', name: 'Guam', subdivisionType: 'district' },
  { code: 'MP', name: 'Northern Mariana Islands', subdivisionType: 'municipality' },
  { code: 'PR', name: 'Puerto Rico', subdivisionType: 'municipality' },
  { code: 'VI', name: 'U.S. Virgin Islands', subdivisionType: 'district' },
];

// Sample counties for major states - in production this would be comprehensive
export const SAMPLE_COUNTIES: { [stateCode: string]: County[] } = {
  'CA': [
    { name: 'Alameda County', fips: '06001', stateCode: 'CA' },
    { name: 'Alpine County', fips: '06003', stateCode: 'CA' },
    { name: 'Amador County', fips: '06005', stateCode: 'CA' },
    { name: 'Butte County', fips: '06007', stateCode: 'CA' },
    { name: 'Calaveras County', fips: '06009', stateCode: 'CA' },
    { name: 'Colusa County', fips: '06011', stateCode: 'CA' },
    { name: 'Contra Costa County', fips: '06013', stateCode: 'CA' },
    { name: 'Del Norte County', fips: '06015', stateCode: 'CA' },
    { name: 'El Dorado County', fips: '06017', stateCode: 'CA' },
    { name: 'Fresno County', fips: '06019', stateCode: 'CA' },
    { name: 'Glenn County', fips: '06021', stateCode: 'CA' },
    { name: 'Humboldt County', fips: '06023', stateCode: 'CA' },
    { name: 'Imperial County', fips: '06025', stateCode: 'CA' },
    { name: 'Inyo County', fips: '06027', stateCode: 'CA' },
    { name: 'Kern County', fips: '06029', stateCode: 'CA' },
    { name: 'Kings County', fips: '06031', stateCode: 'CA' },
    { name: 'Lake County', fips: '06033', stateCode: 'CA' },
    { name: 'Lassen County', fips: '06035', stateCode: 'CA' },
    { name: 'Los Angeles County', fips: '06037', stateCode: 'CA' },
    { name: 'Madera County', fips: '06039', stateCode: 'CA' },
    { name: 'Marin County', fips: '06041', stateCode: 'CA' },
    { name: 'Mariposa County', fips: '06043', stateCode: 'CA' },
    { name: 'Mendocino County', fips: '06045', stateCode: 'CA' },
    { name: 'Merced County', fips: '06047', stateCode: 'CA' },
    { name: 'Modoc County', fips: '06049', stateCode: 'CA' },
    { name: 'Mono County', fips: '06051', stateCode: 'CA' },
    { name: 'Monterey County', fips: '06053', stateCode: 'CA' },
    { name: 'Napa County', fips: '06055', stateCode: 'CA' },
    { name: 'Nevada County', fips: '06057', stateCode: 'CA' },
    { name: 'Orange County', fips: '06059', stateCode: 'CA' },
    { name: 'Placer County', fips: '06061', stateCode: 'CA' },
    { name: 'Plumas County', fips: '06063', stateCode: 'CA' },
    { name: 'Riverside County', fips: '06065', stateCode: 'CA' },
    { name: 'Sacramento County', fips: '06067', stateCode: 'CA' },
    { name: 'San Benito County', fips: '06069', stateCode: 'CA' },
    { name: 'San Bernardino County', fips: '06071', stateCode: 'CA' },
    { name: 'San Diego County', fips: '06073', stateCode: 'CA' },
    { name: 'San Francisco County', fips: '06075', stateCode: 'CA' },
    { name: 'San Joaquin County', fips: '06077', stateCode: 'CA' },
    { name: 'San Luis Obispo County', fips: '06079', stateCode: 'CA' },
    { name: 'San Mateo County', fips: '06081', stateCode: 'CA' },
    { name: 'Santa Barbara County', fips: '06083', stateCode: 'CA' },
    { name: 'Santa Clara County', fips: '06085', stateCode: 'CA' },
    { name: 'Santa Cruz County', fips: '06087', stateCode: 'CA' },
    { name: 'Shasta County', fips: '06089', stateCode: 'CA' },
    { name: 'Sierra County', fips: '06091', stateCode: 'CA' },
    { name: 'Siskiyou County', fips: '06093', stateCode: 'CA' },
    { name: 'Solano County', fips: '06095', stateCode: 'CA' },
    { name: 'Sonoma County', fips: '06097', stateCode: 'CA' },
    { name: 'Stanislaus County', fips: '06099', stateCode: 'CA' },
    { name: 'Sutter County', fips: '06101', stateCode: 'CA' },
    { name: 'Tehama County', fips: '06103', stateCode: 'CA' },
    { name: 'Trinity County', fips: '06105', stateCode: 'CA' },
    { name: 'Tulare County', fips: '06107', stateCode: 'CA' },
    { name: 'Tuolumne County', fips: '06109', stateCode: 'CA' },
    { name: 'Ventura County', fips: '06111', stateCode: 'CA' },
    { name: 'Yolo County', fips: '06113', stateCode: 'CA' },
    { name: 'Yuba County', fips: '06115', stateCode: 'CA' },
  ],
  'TX': [
    { name: 'Anderson County', fips: '48001', stateCode: 'TX' },
    { name: 'Andrews County', fips: '48003', stateCode: 'TX' },
    { name: 'Angelina County', fips: '48005', stateCode: 'TX' },
    { name: 'Aransas County', fips: '48007', stateCode: 'TX' },
    { name: 'Archer County', fips: '48009', stateCode: 'TX' },
    { name: 'Armstrong County', fips: '48011', stateCode: 'TX' },
    { name: 'Atascosa County', fips: '48013', stateCode: 'TX' },
    { name: 'Austin County', fips: '48015', stateCode: 'TX' },
    { name: 'Bailey County', fips: '48017', stateCode: 'TX' },
    { name: 'Bandera County', fips: '48019', stateCode: 'TX' },
    { name: 'Bastrop County', fips: '48021', stateCode: 'TX' },
    { name: 'Baylor County', fips: '48023', stateCode: 'TX' },
    { name: 'Bee County', fips: '48025', stateCode: 'TX' },
    { name: 'Bell County', fips: '48027', stateCode: 'TX' },
    { name: 'Bexar County', fips: '48029', stateCode: 'TX' },
    { name: 'Blanco County', fips: '48031', stateCode: 'TX' },
    { name: 'Borden County', fips: '48033', stateCode: 'TX' },
    { name: 'Bosque County', fips: '48035', stateCode: 'TX' },
    { name: 'Bowie County', fips: '48037', stateCode: 'TX' },
    { name: 'Brazoria County', fips: '48039', stateCode: 'TX' },
    { name: 'Brazos County', fips: '48041', stateCode: 'TX' },
    { name: 'Brewster County', fips: '48043', stateCode: 'TX' },
    { name: 'Briscoe County', fips: '48045', stateCode: 'TX' },
    { name: 'Brooks County', fips: '48047', stateCode: 'TX' },
    { name: 'Brown County', fips: '48049', stateCode: 'TX' },
    { name: 'Burleson County', fips: '48051', stateCode: 'TX' },
    { name: 'Burnet County', fips: '48053', stateCode: 'TX' },
    { name: 'Caldwell County', fips: '48055', stateCode: 'TX' },
    { name: 'Calhoun County', fips: '48057', stateCode: 'TX' },
    { name: 'Callahan County', fips: '48059', stateCode: 'TX' },
    { name: 'Cameron County', fips: '48061', stateCode: 'TX' },
    { name: 'Camp County', fips: '48063', stateCode: 'TX' },
    { name: 'Carson County', fips: '48065', stateCode: 'TX' },
    { name: 'Cass County', fips: '48067', stateCode: 'TX' },
    { name: 'Castro County', fips: '48069', stateCode: 'TX' },
    { name: 'Chambers County', fips: '48071', stateCode: 'TX' },
    { name: 'Cherokee County', fips: '48073', stateCode: 'TX' },
    { name: 'Childress County', fips: '48075', stateCode: 'TX' },
    { name: 'Clay County', fips: '48077', stateCode: 'TX' },
    { name: 'Cochran County', fips: '48079', stateCode: 'TX' },
    { name: 'Coke County', fips: '48081', stateCode: 'TX' },
    { name: 'Coleman County', fips: '48083', stateCode: 'TX' },
    { name: 'Collin County', fips: '48085', stateCode: 'TX' },
    { name: 'Collingsworth County', fips: '48087', stateCode: 'TX' },
    { name: 'Colorado County', fips: '48089', stateCode: 'TX' },
    { name: 'Comal County', fips: '48091', stateCode: 'TX' },
    { name: 'Comanche County', fips: '48093', stateCode: 'TX' },
    { name: 'Concho County', fips: '48095', stateCode: 'TX' },
    { name: 'Cooke County', fips: '48097', stateCode: 'TX' },
    { name: 'Coryell County', fips: '48099', stateCode: 'TX' },
    { name: 'Cottle County', fips: '48101', stateCode: 'TX' },
    { name: 'Crane County', fips: '48103', stateCode: 'TX' },
    { name: 'Crockett County', fips: '48105', stateCode: 'TX' },
    { name: 'Crosby County', fips: '48107', stateCode: 'TX' },
    { name: 'Culberson County', fips: '48109', stateCode: 'TX' },
    { name: 'Dallam County', fips: '48111', stateCode: 'TX' },
    { name: 'Dallas County', fips: '48113', stateCode: 'TX' },
    { name: 'Dawson County', fips: '48115', stateCode: 'TX' },
    { name: 'Deaf Smith County', fips: '48117', stateCode: 'TX' },
    { name: 'Delta County', fips: '48119', stateCode: 'TX' },
    { name: 'Denton County', fips: '48121', stateCode: 'TX' },
    { name: 'DeWitt County', fips: '48123', stateCode: 'TX' },
    { name: 'Dickens County', fips: '48125', stateCode: 'TX' },
    { name: 'Dimmit County', fips: '48127', stateCode: 'TX' },
    { name: 'Donley County', fips: '48129', stateCode: 'TX' },
    { name: 'Duval County', fips: '48131', stateCode: 'TX' },
    { name: 'Eastland County', fips: '48133', stateCode: 'TX' },
    { name: 'Ector County', fips: '48135', stateCode: 'TX' },
    { name: 'Edwards County', fips: '48137', stateCode: 'TX' },
    { name: 'Ellis County', fips: '48139', stateCode: 'TX' },
    { name: 'El Paso County', fips: '48141', stateCode: 'TX' },
    { name: 'Erath County', fips: '48143', stateCode: 'TX' },
    { name: 'Falls County', fips: '48145', stateCode: 'TX' },
    { name: 'Fannin County', fips: '48147', stateCode: 'TX' },
    { name: 'Fayette County', fips: '48149', stateCode: 'TX' },
    { name: 'Fisher County', fips: '48151', stateCode: 'TX' },
    { name: 'Floyd County', fips: '48153', stateCode: 'TX' },
    { name: 'Foard County', fips: '48155', stateCode: 'TX' },
    { name: 'Fort Bend County', fips: '48157', stateCode: 'TX' },
    { name: 'Franklin County', fips: '48159', stateCode: 'TX' },
    { name: 'Freestone County', fips: '48161', stateCode: 'TX' },
    { name: 'Frio County', fips: '48163', stateCode: 'TX' },
    { name: 'Gaines County', fips: '48165', stateCode: 'TX' },
    { name: 'Galveston County', fips: '48167', stateCode: 'TX' },
    { name: 'Garza County', fips: '48169', stateCode: 'TX' },
    { name: 'Gillespie County', fips: '48171', stateCode: 'TX' },
    { name: 'Glasscock County', fips: '48173', stateCode: 'TX' },
    { name: 'Goliad County', fips: '48175', stateCode: 'TX' },
    { name: 'Gonzales County', fips: '48177', stateCode: 'TX' },
    { name: 'Gray County', fips: '48179', stateCode: 'TX' },
    { name: 'Grayson County', fips: '48181', stateCode: 'TX' },
    { name: 'Gregg County', fips: '48183', stateCode: 'TX' },
    { name: 'Grimes County', fips: '48185', stateCode: 'TX' },
    { name: 'Guadalupe County', fips: '48187', stateCode: 'TX' },
    { name: 'Hale County', fips: '48189', stateCode: 'TX' },
    { name: 'Hall County', fips: '48191', stateCode: 'TX' },
    { name: 'Hamilton County', fips: '48193', stateCode: 'TX' },
    { name: 'Hansford County', fips: '48195', stateCode: 'TX' },
    { name: 'Hardeman County', fips: '48197', stateCode: 'TX' },
    { name: 'Hardin County', fips: '48199', stateCode: 'TX' },
    { name: 'Harris County', fips: '48201', stateCode: 'TX' },
    { name: 'Harrison County', fips: '48203', stateCode: 'TX' },
    { name: 'Hartley County', fips: '48205', stateCode: 'TX' },
    { name: 'Haskell County', fips: '48207', stateCode: 'TX' },
    { name: 'Hays County', fips: '48209', stateCode: 'TX' },
    { name: 'Hemphill County', fips: '48211', stateCode: 'TX' },
    { name: 'Henderson County', fips: '48213', stateCode: 'TX' },
    { name: 'Hidalgo County', fips: '48215', stateCode: 'TX' },
    { name: 'Hill County', fips: '48217', stateCode: 'TX' },
    { name: 'Hockley County', fips: '48219', stateCode: 'TX' },
    { name: 'Hood County', fips: '48221', stateCode: 'TX' },
    { name: 'Hopkins County', fips: '48223', stateCode: 'TX' },
    { name: 'Houston County', fips: '48225', stateCode: 'TX' },
    { name: 'Howard County', fips: '48227', stateCode: 'TX' },
    { name: 'Hudspeth County', fips: '48229', stateCode: 'TX' },
    { name: 'Hunt County', fips: '48231', stateCode: 'TX' },
    { name: 'Hutchinson County', fips: '48233', stateCode: 'TX' },
    { name: 'Irion County', fips: '48235', stateCode: 'TX' },
    { name: 'Jack County', fips: '48237', stateCode: 'TX' },
    { name: 'Jackson County', fips: '48239', stateCode: 'TX' },
    { name: 'Jasper County', fips: '48241', stateCode: 'TX' },
    { name: 'Jeff Davis County', fips: '48243', stateCode: 'TX' },
    { name: 'Jefferson County', fips: '48245', stateCode: 'TX' },
    { name: 'Jim Hogg County', fips: '48247', stateCode: 'TX' },
    { name: 'Jim Wells County', fips: '48249', stateCode: 'TX' },
    { name: 'Johnson County', fips: '48251', stateCode: 'TX' },
    { name: 'Jones County', fips: '48253', stateCode: 'TX' },
    { name: 'Karnes County', fips: '48255', stateCode: 'TX' },
    { name: 'Kaufman County', fips: '48257', stateCode: 'TX' },
    { name: 'Kendall County', fips: '48259', stateCode: 'TX' },
    { name: 'Kenedy County', fips: '48261', stateCode: 'TX' },
    { name: 'Kent County', fips: '48263', stateCode: 'TX' },
    { name: 'Kerr County', fips: '48265', stateCode: 'TX' },
    { name: 'Kimble County', fips: '48267', stateCode: 'TX' },
    { name: 'King County', fips: '48269', stateCode: 'TX' },
    { name: 'Kinney County', fips: '48271', stateCode: 'TX' },
    { name: 'Kleberg County', fips: '48273', stateCode: 'TX' },
    { name: 'Knox County', fips: '48275', stateCode: 'TX' },
    { name: 'Lamar County', fips: '48277', stateCode: 'TX' },
    { name: 'Lamb County', fips: '48279', stateCode: 'TX' },
    { name: 'Lampasas County', fips: '48281', stateCode: 'TX' },
    { name: 'La Salle County', fips: '48283', stateCode: 'TX' },
    { name: 'Lavaca County', fips: '48285', stateCode: 'TX' },
    { name: 'Lee County', fips: '48287', stateCode: 'TX' },
    { name: 'Leon County', fips: '48289', stateCode: 'TX' },
    { name: 'Liberty County', fips: '48291', stateCode: 'TX' },
    { name: 'Limestone County', fips: '48293', stateCode: 'TX' },
    { name: 'Lipscomb County', fips: '48295', stateCode: 'TX' },
    { name: 'Live Oak County', fips: '48297', stateCode: 'TX' },
    { name: 'Llano County', fips: '48299', stateCode: 'TX' },
    { name: 'Loving County', fips: '48301', stateCode: 'TX' },
    { name: 'Lubbock County', fips: '48303', stateCode: 'TX' },
    { name: 'Lynn County', fips: '48305', stateCode: 'TX' },
    { name: 'McCulloch County', fips: '48307', stateCode: 'TX' },
    { name: 'McLennan County', fips: '48309', stateCode: 'TX' },
    { name: 'McMullen County', fips: '48311', stateCode: 'TX' },
    { name: 'Madison County', fips: '48313', stateCode: 'TX' },
    { name: 'Marion County', fips: '48315', stateCode: 'TX' },
    { name: 'Martin County', fips: '48317', stateCode: 'TX' },
    { name: 'Mason County', fips: '48319', stateCode: 'TX' },
    { name: 'Matagorda County', fips: '48321', stateCode: 'TX' },
    { name: 'Maverick County', fips: '48323', stateCode: 'TX' },
    { name: 'Medina County', fips: '48325', stateCode: 'TX' },
    { name: 'Menard County', fips: '48327', stateCode: 'TX' },
    { name: 'Midland County', fips: '48329', stateCode: 'TX' },
    { name: 'Milam County', fips: '48331', stateCode: 'TX' },
    { name: 'Mills County', fips: '48333', stateCode: 'TX' },
    { name: 'Mitchell County', fips: '48335', stateCode: 'TX' },
    { name: 'Montague County', fips: '48337', stateCode: 'TX' },
    { name: 'Montgomery County', fips: '48339', stateCode: 'TX' },
    { name: 'Moore County', fips: '48341', stateCode: 'TX' },
    { name: 'Morris County', fips: '48343', stateCode: 'TX' },
    { name: 'Motley County', fips: '48345', stateCode: 'TX' },
    { name: 'Nacogdoches County', fips: '48347', stateCode: 'TX' },
    { name: 'Navarro County', fips: '48349', stateCode: 'TX' },
    { name: 'Newton County', fips: '48351', stateCode: 'TX' },
    { name: 'Nolan County', fips: '48353', stateCode: 'TX' },
    { name: 'Nueces County', fips: '48355', stateCode: 'TX' },
    { name: 'Ochiltree County', fips: '48357', stateCode: 'TX' },
    { name: 'Oldham County', fips: '48359', stateCode: 'TX' },
    { name: 'Orange County', fips: '48361', stateCode: 'TX' },
    { name: 'Palo Pinto County', fips: '48363', stateCode: 'TX' },
    { name: 'Panola County', fips: '48365', stateCode: 'TX' },
    { name: 'Parker County', fips: '48367', stateCode: 'TX' },
    { name: 'Parmer County', fips: '48369', stateCode: 'TX' },
    { name: 'Pecos County', fips: '48371', stateCode: 'TX' },
    { name: 'Polk County', fips: '48373', stateCode: 'TX' },
    { name: 'Potter County', fips: '48375', stateCode: 'TX' },
    { name: 'Presidio County', fips: '48377', stateCode: 'TX' },
    { name: 'Rains County', fips: '48379', stateCode: 'TX' },
    { name: 'Randall County', fips: '48381', stateCode: 'TX' },
    { name: 'Reagan County', fips: '48383', stateCode: 'TX' },
    { name: 'Real County', fips: '48385', stateCode: 'TX' },
    { name: 'Red River County', fips: '48387', stateCode: 'TX' },
    { name: 'Reeves County', fips: '48389', stateCode: 'TX' },
    { name: 'Refugio County', fips: '48391', stateCode: 'TX' },
    { name: 'Roberts County', fips: '48393', stateCode: 'TX' },
    { name: 'Robertson County', fips: '48395', stateCode: 'TX' },
    { name: 'Rockwall County', fips: '48397', stateCode: 'TX' },
    { name: 'Runnels County', fips: '48399', stateCode: 'TX' },
    { name: 'Rusk County', fips: '48401', stateCode: 'TX' },
    { name: 'Sabine County', fips: '48403', stateCode: 'TX' },
    { name: 'San Augustine County', fips: '48405', stateCode: 'TX' },
    { name: 'San Jacinto County', fips: '48407', stateCode: 'TX' },
    { name: 'San Patricio County', fips: '48409', stateCode: 'TX' },
    { name: 'San Saba County', fips: '48411', stateCode: 'TX' },
    { name: 'Schleicher County', fips: '48413', stateCode: 'TX' },
    { name: 'Scurry County', fips: '48415', stateCode: 'TX' },
    { name: 'Shackelford County', fips: '48417', stateCode: 'TX' },
    { name: 'Shelby County', fips: '48419', stateCode: 'TX' },
    { name: 'Sherman County', fips: '48421', stateCode: 'TX' },
    { name: 'Smith County', fips: '48423', stateCode: 'TX' },
    { name: 'Somervell County', fips: '48425', stateCode: 'TX' },
    { name: 'Starr County', fips: '48427', stateCode: 'TX' },
    { name: 'Stephens County', fips: '48429', stateCode: 'TX' },
    { name: 'Sterling County', fips: '48431', stateCode: 'TX' },
    { name: 'Stonewall County', fips: '48433', stateCode: 'TX' },
    { name: 'Sutton County', fips: '48435', stateCode: 'TX' },
    { name: 'Swisher County', fips: '48437', stateCode: 'TX' },
    { name: 'Tarrant County', fips: '48439', stateCode: 'TX' },
    { name: 'Taylor County', fips: '48441', stateCode: 'TX' },
    { name: 'Terrell County', fips: '48443', stateCode: 'TX' },
    { name: 'Terry County', fips: '48445', stateCode: 'TX' },
    { name: 'Throckmorton County', fips: '48447', stateCode: 'TX' },
    { name: 'Titus County', fips: '48449', stateCode: 'TX' },
    { name: 'Tom Green County', fips: '48451', stateCode: 'TX' },
    { name: 'Travis County', fips: '48453', stateCode: 'TX' },
    { name: 'Trinity County', fips: '48455', stateCode: 'TX' },
    { name: 'Tyler County', fips: '48457', stateCode: 'TX' },
    { name: 'Upshur County', fips: '48459', stateCode: 'TX' },
    { name: 'Upton County', fips: '48461', stateCode: 'TX' },
    { name: 'Uvalde County', fips: '48463', stateCode: 'TX' },
    { name: 'Val Verde County', fips: '48465', stateCode: 'TX' },
    { name: 'Van Zandt County', fips: '48467', stateCode: 'TX' },
    { name: 'Victoria County', fips: '48469', stateCode: 'TX' },
    { name: 'Walker County', fips: '48471', stateCode: 'TX' },
    { name: 'Waller County', fips: '48473', stateCode: 'TX' },
    { name: 'Ward County', fips: '48475', stateCode: 'TX' },
    { name: 'Washington County', fips: '48477', stateCode: 'TX' },
    { name: 'Webb County', fips: '48479', stateCode: 'TX' },
    { name: 'Wharton County', fips: '48481', stateCode: 'TX' },
    { name: 'Wheeler County', fips: '48483', stateCode: 'TX' },
    { name: 'Wichita County', fips: '48485', stateCode: 'TX' },
    { name: 'Wilbarger County', fips: '48487', stateCode: 'TX' },
    { name: 'Willacy County', fips: '48489', stateCode: 'TX' },
    { name: 'Williamson County', fips: '48491', stateCode: 'TX' },
    { name: 'Wilson County', fips: '48493', stateCode: 'TX' },
    { name: 'Winkler County', fips: '48495', stateCode: 'TX' },
    { name: 'Wise County', fips: '48497', stateCode: 'TX' },
    { name: 'Wood County', fips: '48499', stateCode: 'TX' },
    { name: 'Yoakum County', fips: '48501', stateCode: 'TX' },
    { name: 'Young County', fips: '48503', stateCode: 'TX' },
    { name: 'Zapata County', fips: '48505', stateCode: 'TX' },
    { name: 'Zavala County', fips: '48507', stateCode: 'TX' },
  ],
  'FL': [
    { name: 'Alachua County', fips: '12001', stateCode: 'FL' },
    { name: 'Baker County', fips: '12003', stateCode: 'FL' },
    { name: 'Bay County', fips: '12005', stateCode: 'FL' },
    { name: 'Bradford County', fips: '12007', stateCode: 'FL' },
    { name: 'Brevard County', fips: '12009', stateCode: 'FL' },
    { name: 'Broward County', fips: '12011', stateCode: 'FL' },
    { name: 'Calhoun County', fips: '12013', stateCode: 'FL' },
    { name: 'Charlotte County', fips: '12015', stateCode: 'FL' },
    { name: 'Citrus County', fips: '12017', stateCode: 'FL' },
    { name: 'Clay County', fips: '12019', stateCode: 'FL' },
    { name: 'Collier County', fips: '12021', stateCode: 'FL' },
    { name: 'Columbia County', fips: '12023', stateCode: 'FL' },
    { name: 'DeSoto County', fips: '12027', stateCode: 'FL' },
    { name: 'Dixie County', fips: '12029', stateCode: 'FL' },
    { name: 'Duval County', fips: '12031', stateCode: 'FL' },
    { name: 'Escambia County', fips: '12033', stateCode: 'FL' },
    { name: 'Flagler County', fips: '12035', stateCode: 'FL' },
    { name: 'Franklin County', fips: '12037', stateCode: 'FL' },
    { name: 'Gadsden County', fips: '12039', stateCode: 'FL' },
    { name: 'Gilchrist County', fips: '12041', stateCode: 'FL' },
    { name: 'Glades County', fips: '12043', stateCode: 'FL' },
    { name: 'Gulf County', fips: '12045', stateCode: 'FL' },
    { name: 'Hamilton County', fips: '12047', stateCode: 'FL' },
    { name: 'Hardee County', fips: '12049', stateCode: 'FL' },
    { name: 'Hendry County', fips: '12051', stateCode: 'FL' },
    { name: 'Hernando County', fips: '12053', stateCode: 'FL' },
    { name: 'Highlands County', fips: '12055', stateCode: 'FL' },
    { name: 'Hillsborough County', fips: '12057', stateCode: 'FL' },
    { name: 'Holmes County', fips: '12059', stateCode: 'FL' },
    { name: 'Indian River County', fips: '12061', stateCode: 'FL' },
    { name: 'Jackson County', fips: '12063', stateCode: 'FL' },
    { name: 'Jefferson County', fips: '12065', stateCode: 'FL' },
    { name: 'Lafayette County', fips: '12067', stateCode: 'FL' },
    { name: 'Lake County', fips: '12069', stateCode: 'FL' },
    { name: 'Lee County', fips: '12071', stateCode: 'FL' },
    { name: 'Leon County', fips: '12073', stateCode: 'FL' },
    { name: 'Levy County', fips: '12075', stateCode: 'FL' },
    { name: 'Liberty County', fips: '12077', stateCode: 'FL' },
    { name: 'Madison County', fips: '12079', stateCode: 'FL' },
    { name: 'Manatee County', fips: '12081', stateCode: 'FL' },
    { name: 'Marion County', fips: '12083', stateCode: 'FL' },
    { name: 'Martin County', fips: '12085', stateCode: 'FL' },
    { name: 'Miami-Dade County', fips: '12086', stateCode: 'FL' },
    { name: 'Monroe County', fips: '12087', stateCode: 'FL' },
    { name: 'Nassau County', fips: '12089', stateCode: 'FL' },
    { name: 'Okaloosa County', fips: '12091', stateCode: 'FL' },
    { name: 'Okeechobee County', fips: '12093', stateCode: 'FL' },
    { name: 'Orange County', fips: '12095', stateCode: 'FL' },
    { name: 'Osceola County', fips: '12097', stateCode: 'FL' },
    { name: 'Palm Beach County', fips: '12099', stateCode: 'FL' },
    { name: 'Pasco County', fips: '12101', stateCode: 'FL' },
    { name: 'Pinellas County', fips: '12103', stateCode: 'FL' },
    { name: 'Polk County', fips: '12105', stateCode: 'FL' },
    { name: 'Putnam County', fips: '12107', stateCode: 'FL' },
    { name: 'St. Johns County', fips: '12109', stateCode: 'FL' },
    { name: 'St. Lucie County', fips: '12111', stateCode: 'FL' },
    { name: 'Santa Rosa County', fips: '12113', stateCode: 'FL' },
    { name: 'Sarasota County', fips: '12115', stateCode: 'FL' },
    { name: 'Seminole County', fips: '12117', stateCode: 'FL' },
    { name: 'Sumter County', fips: '12119', stateCode: 'FL' },
    { name: 'Suwannee County', fips: '12121', stateCode: 'FL' },
    { name: 'Taylor County', fips: '12123', stateCode: 'FL' },
    { name: 'Union County', fips: '12125', stateCode: 'FL' },
    { name: 'Volusia County', fips: '12127', stateCode: 'FL' },
    { name: 'Wakulla County', fips: '12129', stateCode: 'FL' },
    { name: 'Walton County', fips: '12131', stateCode: 'FL' },
    { name: 'Washington County', fips: '12133', stateCode: 'FL' },
  ],
  'NY': [
    { name: 'Albany County', fips: '36001', stateCode: 'NY' },
    { name: 'Allegany County', fips: '36003', stateCode: 'NY' },
    { name: 'Bronx County', fips: '36005', stateCode: 'NY' },
    { name: 'Broome County', fips: '36007', stateCode: 'NY' },
    { name: 'Cattaraugus County', fips: '36009', stateCode: 'NY' },
    { name: 'Cayuga County', fips: '36011', stateCode: 'NY' },
    { name: 'Chautauqua County', fips: '36013', stateCode: 'NY' },
    { name: 'Chemung County', fips: '36015', stateCode: 'NY' },
    { name: 'Chenango County', fips: '36017', stateCode: 'NY' },
    { name: 'Clinton County', fips: '36019', stateCode: 'NY' },
    { name: 'Columbia County', fips: '36021', stateCode: 'NY' },
    { name: 'Cortland County', fips: '36023', stateCode: 'NY' },
    { name: 'Delaware County', fips: '36025', stateCode: 'NY' },
    { name: 'Dutchess County', fips: '36027', stateCode: 'NY' },
    { name: 'Erie County', fips: '36029', stateCode: 'NY' },
    { name: 'Essex County', fips: '36031', stateCode: 'NY' },
    { name: 'Franklin County', fips: '36033', stateCode: 'NY' },
    { name: 'Fulton County', fips: '36035', stateCode: 'NY' },
    { name: 'Genesee County', fips: '36037', stateCode: 'NY' },
    { name: 'Greene County', fips: '36039', stateCode: 'NY' },
    { name: 'Hamilton County', fips: '36041', stateCode: 'NY' },
    { name: 'Herkimer County', fips: '36043', stateCode: 'NY' },
    { name: 'Jefferson County', fips: '36045', stateCode: 'NY' },
    { name: 'Kings County', fips: '36047', stateCode: 'NY' },
    { name: 'Lewis County', fips: '36049', stateCode: 'NY' },
    { name: 'Livingston County', fips: '36051', stateCode: 'NY' },
    { name: 'Madison County', fips: '36053', stateCode: 'NY' },
    { name: 'Monroe County', fips: '36055', stateCode: 'NY' },
    { name: 'Montgomery County', fips: '36057', stateCode: 'NY' },
    { name: 'Nassau County', fips: '36059', stateCode: 'NY' },
    { name: 'New York County', fips: '36061', stateCode: 'NY' },
    { name: 'Niagara County', fips: '36063', stateCode: 'NY' },
    { name: 'Oneida County', fips: '36065', stateCode: 'NY' },
    { name: 'Onondaga County', fips: '36067', stateCode: 'NY' },
    { name: 'Ontario County', fips: '36069', stateCode: 'NY' },
    { name: 'Orange County', fips: '36071', stateCode: 'NY' },
    { name: 'Orleans County', fips: '36073', stateCode: 'NY' },
    { name: 'Oswego County', fips: '36075', stateCode: 'NY' },
    { name: 'Otsego County', fips: '36077', stateCode: 'NY' },
    { name: 'Putnam County', fips: '36079', stateCode: 'NY' },
    { name: 'Queens County', fips: '36081', stateCode: 'NY' },
    { name: 'Rensselaer County', fips: '36083', stateCode: 'NY' },
    { name: 'Richmond County', fips: '36085', stateCode: 'NY' },
    { name: 'Rockland County', fips: '36087', stateCode: 'NY' },
    { name: 'St. Lawrence County', fips: '36089', stateCode: 'NY' },
    { name: 'Saratoga County', fips: '36091', stateCode: 'NY' },
    { name: 'Schenectady County', fips: '36093', stateCode: 'NY' },
    { name: 'Schoharie County', fips: '36095', stateCode: 'NY' },
    { name: 'Schuyler County', fips: '36097', stateCode: 'NY' },
    { name: 'Seneca County', fips: '36099', stateCode: 'NY' },
    { name: 'Steuben County', fips: '36101', stateCode: 'NY' },
    { name: 'Suffolk County', fips: '36103', stateCode: 'NY' },
    { name: 'Sullivan County', fips: '36105', stateCode: 'NY' },
    { name: 'Tioga County', fips: '36107', stateCode: 'NY' },
    { name: 'Tompkins County', fips: '36109', stateCode: 'NY' },
    { name: 'Ulster County', fips: '36111', stateCode: 'NY' },
    { name: 'Warren County', fips: '36113', stateCode: 'NY' },
    { name: 'Washington County', fips: '36115', stateCode: 'NY' },
    { name: 'Wayne County', fips: '36117', stateCode: 'NY' },
    { name: 'Westchester County', fips: '36119', stateCode: 'NY' },
    { name: 'Wyoming County', fips: '36121', stateCode: 'NY' },
    { name: 'Yates County', fips: '36123', stateCode: 'NY' },
  ],
  'LA': [
    { name: 'Acadia Parish', fips: '22001', stateCode: 'LA' },
    { name: 'Allen Parish', fips: '22003', stateCode: 'LA' },
    { name: 'Ascension Parish', fips: '22005', stateCode: 'LA' },
    { name: 'Assumption Parish', fips: '22007', stateCode: 'LA' },
    { name: 'Avoyelles Parish', fips: '22009', stateCode: 'LA' },
    { name: 'Beauregard Parish', fips: '22011', stateCode: 'LA' },
    { name: 'Bienville Parish', fips: '22013', stateCode: 'LA' },
    { name: 'Bossier Parish', fips: '22015', stateCode: 'LA' },
    { name: 'Caddo Parish', fips: '22017', stateCode: 'LA' },
    { name: 'Calcasieu Parish', fips: '22019', stateCode: 'LA' },
    { name: 'Caldwell Parish', fips: '22021', stateCode: 'LA' },
    { name: 'Cameron Parish', fips: '22023', stateCode: 'LA' },
    { name: 'Catahoula Parish', fips: '22025', stateCode: 'LA' },
    { name: 'Claiborne Parish', fips: '22027', stateCode: 'LA' },
    { name: 'Concordia Parish', fips: '22029', stateCode: 'LA' },
    { name: 'De Soto Parish', fips: '22031', stateCode: 'LA' },
    { name: 'East Baton Rouge Parish', fips: '22033', stateCode: 'LA' },
    { name: 'East Carroll Parish', fips: '22035', stateCode: 'LA' },
    { name: 'East Feliciana Parish', fips: '22037', stateCode: 'LA' },
    { name: 'Evangeline Parish', fips: '22039', stateCode: 'LA' },
    { name: 'Franklin Parish', fips: '22041', stateCode: 'LA' },
    { name: 'Grant Parish', fips: '22043', stateCode: 'LA' },
    { name: 'Iberia Parish', fips: '22045', stateCode: 'LA' },
    { name: 'Iberville Parish', fips: '22047', stateCode: 'LA' },
    { name: 'Jackson Parish', fips: '22049', stateCode: 'LA' },
    { name: 'Jefferson Parish', fips: '22051', stateCode: 'LA' },
    { name: 'Jefferson Davis Parish', fips: '22053', stateCode: 'LA' },
    { name: 'Lafayette Parish', fips: '22055', stateCode: 'LA' },
    { name: 'Lafourche Parish', fips: '22057', stateCode: 'LA' },
    { name: 'La Salle Parish', fips: '22059', stateCode: 'LA' },
    { name: 'Lincoln Parish', fips: '22061', stateCode: 'LA' },
    { name: 'Livingston Parish', fips: '22063', stateCode: 'LA' },
    { name: 'Madison Parish', fips: '22065', stateCode: 'LA' },
    { name: 'Morehouse Parish', fips: '22067', stateCode: 'LA' },
    { name: 'Natchitoches Parish', fips: '22069', stateCode: 'LA' },
    { name: 'Orleans Parish', fips: '22071', stateCode: 'LA' },
    { name: 'Ouachita Parish', fips: '22073', stateCode: 'LA' },
    { name: 'Plaquemines Parish', fips: '22075', stateCode: 'LA' },
    { name: 'Pointe Coupee Parish', fips: '22077', stateCode: 'LA' },
    { name: 'Rapides Parish', fips: '22079', stateCode: 'LA' },
    { name: 'Red River Parish', fips: '22081', stateCode: 'LA' },
    { name: 'Richland Parish', fips: '22083', stateCode: 'LA' },
    { name: 'Sabine Parish', fips: '22085', stateCode: 'LA' },
    { name: 'St. Bernard Parish', fips: '22087', stateCode: 'LA' },
    { name: 'St. Charles Parish', fips: '22089', stateCode: 'LA' },
    { name: 'St. Helena Parish', fips: '22091', stateCode: 'LA' },
    { name: 'St. James Parish', fips: '22093', stateCode: 'LA' },
    { name: 'St. John the Baptist Parish', fips: '22095', stateCode: 'LA' },
    { name: 'St. Landry Parish', fips: '22097', stateCode: 'LA' },
    { name: 'St. Martin Parish', fips: '22099', stateCode: 'LA' },
    { name: 'St. Mary Parish', fips: '22101', stateCode: 'LA' },
    { name: 'St. Tammany Parish', fips: '22103', stateCode: 'LA' },
    { name: 'Tangipahoa Parish', fips: '22105', stateCode: 'LA' },
    { name: 'Tensas Parish', fips: '22107', stateCode: 'LA' },
    { name: 'Terrebonne Parish', fips: '22109', stateCode: 'LA' },
    { name: 'Union Parish', fips: '22111', stateCode: 'LA' },
    { name: 'Vermilion Parish', fips: '22113', stateCode: 'LA' },
    { name: 'Vernon Parish', fips: '22115', stateCode: 'LA' },
    { name: 'Washington Parish', fips: '22117', stateCode: 'LA' },
    { name: 'Webster Parish', fips: '22119', stateCode: 'LA' },
    { name: 'West Baton Rouge Parish', fips: '22121', stateCode: 'LA' },
    { name: 'West Carroll Parish', fips: '22123', stateCode: 'LA' },
    { name: 'West Feliciana Parish', fips: '22125', stateCode: 'LA' },
  ],
  'IL': [
    { name: 'Adams County', fips: '17001', stateCode: 'IL' },
    { name: 'Alexander County', fips: '17003', stateCode: 'IL' },
    { name: 'Bond County', fips: '17005', stateCode: 'IL' },
    { name: 'Boone County', fips: '17007', stateCode: 'IL' },
    { name: 'Brown County', fips: '17009', stateCode: 'IL' },
    { name: 'Bureau County', fips: '17011', stateCode: 'IL' },
    { name: 'Calhoun County', fips: '17013', stateCode: 'IL' },
    { name: 'Carroll County', fips: '17015', stateCode: 'IL' },
    { name: 'Cass County', fips: '17017', stateCode: 'IL' },
    { name: 'Champaign County', fips: '17019', stateCode: 'IL' },
    { name: 'Christian County', fips: '17021', stateCode: 'IL' },
    { name: 'Clark County', fips: '17023', stateCode: 'IL' },
    { name: 'Clay County', fips: '17025', stateCode: 'IL' },
    { name: 'Clinton County', fips: '17027', stateCode: 'IL' },
    { name: 'Coles County', fips: '17029', stateCode: 'IL' },
    { name: 'Cook County', fips: '17031', stateCode: 'IL' },
    { name: 'Crawford County', fips: '17033', stateCode: 'IL' },
    { name: 'Cumberland County', fips: '17035', stateCode: 'IL' },
    { name: 'DeKalb County', fips: '17037', stateCode: 'IL' },
    { name: 'De Witt County', fips: '17039', stateCode: 'IL' },
    { name: 'Douglas County', fips: '17041', stateCode: 'IL' },
    { name: 'DuPage County', fips: '17043', stateCode: 'IL' },
    { name: 'Edgar County', fips: '17045', stateCode: 'IL' },
    { name: 'Edwards County', fips: '17047', stateCode: 'IL' },
    { name: 'Effingham County', fips: '17049', stateCode: 'IL' },
    { name: 'Fayette County', fips: '17051', stateCode: 'IL' },
    { name: 'Ford County', fips: '17053', stateCode: 'IL' },
    { name: 'Franklin County', fips: '17055', stateCode: 'IL' },
    { name: 'Fulton County', fips: '17057', stateCode: 'IL' },
    { name: 'Gallatin County', fips: '17059', stateCode: 'IL' },
    { name: 'Greene County', fips: '17061', stateCode: 'IL' },
    { name: 'Grundy County', fips: '17063', stateCode: 'IL' },
    { name: 'Hamilton County', fips: '17065', stateCode: 'IL' },
    { name: 'Hancock County', fips: '17067', stateCode: 'IL' },
    { name: 'Hardin County', fips: '17069', stateCode: 'IL' },
    { name: 'Henderson County', fips: '17071', stateCode: 'IL' },
    { name: 'Henry County', fips: '17073', stateCode: 'IL' },
    { name: 'Iroquois County', fips: '17075', stateCode: 'IL' },
    { name: 'Jackson County', fips: '17077', stateCode: 'IL' },
    { name: 'Jasper County', fips: '17079', stateCode: 'IL' },
    { name: 'Jefferson County', fips: '17081', stateCode: 'IL' },
    { name: 'Jersey County', fips: '17083', stateCode: 'IL' },
    { name: 'Jo Daviess County', fips: '17085', stateCode: 'IL' },
    { name: 'Johnson County', fips: '17087', stateCode: 'IL' },
    { name: 'Kane County', fips: '17089', stateCode: 'IL' },
    { name: 'Kankakee County', fips: '17091', stateCode: 'IL' },
    { name: 'Kendall County', fips: '17093', stateCode: 'IL' },
    { name: 'Knox County', fips: '17095', stateCode: 'IL' },
    { name: 'Lake County', fips: '17097', stateCode: 'IL' },
    { name: 'LaSalle County', fips: '17099', stateCode: 'IL' },
    { name: 'Lawrence County', fips: '17101', stateCode: 'IL' },
    { name: 'Lee County', fips: '17103', stateCode: 'IL' },
    { name: 'Livingston County', fips: '17105', stateCode: 'IL' },
    { name: 'Logan County', fips: '17107', stateCode: 'IL' },
    { name: 'McDonough County', fips: '17109', stateCode: 'IL' },
    { name: 'McHenry County', fips: '17111', stateCode: 'IL' },
    { name: 'McLean County', fips: '17113', stateCode: 'IL' },
    { name: 'Macon County', fips: '17115', stateCode: 'IL' },
    { name: 'Macoupin County', fips: '17117', stateCode: 'IL' },
    { name: 'Madison County', fips: '17119', stateCode: 'IL' },
    { name: 'Marion County', fips: '17121', stateCode: 'IL' },
    { name: 'Marshall County', fips: '17123', stateCode: 'IL' },
    { name: 'Mason County', fips: '17125', stateCode: 'IL' },
    { name: 'Massac County', fips: '17127', stateCode: 'IL' },
    { name: 'Menard County', fips: '17129', stateCode: 'IL' },
    { name: 'Mercer County', fips: '17131', stateCode: 'IL' },
    { name: 'Monroe County', fips: '17133', stateCode: 'IL' },
    { name: 'Montgomery County', fips: '17135', stateCode: 'IL' },
    { name: 'Morgan County', fips: '17137', stateCode: 'IL' },
    { name: 'Moultrie County', fips: '17139', stateCode: 'IL' },
    { name: 'Ogle County', fips: '17141', stateCode: 'IL' },
    { name: 'Peoria County', fips: '17143', stateCode: 'IL' },
    { name: 'Perry County', fips: '17145', stateCode: 'IL' },
    { name: 'Piatt County', fips: '17147', stateCode: 'IL' },
    { name: 'Pike County', fips: '17149', stateCode: 'IL' },
    { name: 'Pope County', fips: '17151', stateCode: 'IL' },
    { name: 'Pulaski County', fips: '17153', stateCode: 'IL' },
    { name: 'Putnam County', fips: '17155', stateCode: 'IL' },
    { name: 'Randolph County', fips: '17157', stateCode: 'IL' },
    { name: 'Richland County', fips: '17159', stateCode: 'IL' },
    { name: 'Rock Island County', fips: '17161', stateCode: 'IL' },
    { name: 'St. Clair County', fips: '17163', stateCode: 'IL' },
    { name: 'Saline County', fips: '17165', stateCode: 'IL' },
    { name: 'Sangamon County', fips: '17167', stateCode: 'IL' },
    { name: 'Schuyler County', fips: '17169', stateCode: 'IL' },
    { name: 'Scott County', fips: '17171', stateCode: 'IL' },
    { name: 'Shelby County', fips: '17173', stateCode: 'IL' },
    { name: 'Stark County', fips: '17175', stateCode: 'IL' },
    { name: 'Stephenson County', fips: '17177', stateCode: 'IL' },
    { name: 'Tazewell County', fips: '17179', stateCode: 'IL' },
    { name: 'Union County', fips: '17181', stateCode: 'IL' },
    { name: 'Vermilion County', fips: '17183', stateCode: 'IL' },
    { name: 'Wabash County', fips: '17185', stateCode: 'IL' },
    { name: 'Warren County', fips: '17187', stateCode: 'IL' },
    { name: 'Washington County', fips: '17189', stateCode: 'IL' },
    { name: 'Wayne County', fips: '17191', stateCode: 'IL' },
    { name: 'White County', fips: '17193', stateCode: 'IL' },
    { name: 'Whiteside County', fips: '17195', stateCode: 'IL' },
    { name: 'Will County', fips: '17197', stateCode: 'IL' },
    { name: 'Williamson County', fips: '17199', stateCode: 'IL' },
    { name: 'Winnebago County', fips: '17201', stateCode: 'IL' },
    { name: 'Woodford County', fips: '17203', stateCode: 'IL' },
  ],
  'PA': [
    { name: 'Adams County', fips: '42001', stateCode: 'PA' },
    { name: 'Allegheny County', fips: '42003', stateCode: 'PA' },
    { name: 'Armstrong County', fips: '42005', stateCode: 'PA' },
    { name: 'Beaver County', fips: '42007', stateCode: 'PA' },
    { name: 'Bedford County', fips: '42009', stateCode: 'PA' },
    { name: 'Berks County', fips: '42011', stateCode: 'PA' },
    { name: 'Blair County', fips: '42013', stateCode: 'PA' },
    { name: 'Bradford County', fips: '42015', stateCode: 'PA' },
    { name: 'Bucks County', fips: '42017', stateCode: 'PA' },
    { name: 'Butler County', fips: '42019', stateCode: 'PA' },
    { name: 'Cambria County', fips: '42021', stateCode: 'PA' },
    { name: 'Cameron County', fips: '42023', stateCode: 'PA' },
    { name: 'Carbon County', fips: '42025', stateCode: 'PA' },
    { name: 'Centre County', fips: '42027', stateCode: 'PA' },
    { name: 'Chester County', fips: '42029', stateCode: 'PA' },
    { name: 'Clarion County', fips: '42031', stateCode: 'PA' },
    { name: 'Clearfield County', fips: '42033', stateCode: 'PA' },
    { name: 'Clinton County', fips: '42035', stateCode: 'PA' },
    { name: 'Columbia County', fips: '42037', stateCode: 'PA' },
    { name: 'Crawford County', fips: '42039', stateCode: 'PA' },
    { name: 'Cumberland County', fips: '42041', stateCode: 'PA' },
    { name: 'Dauphin County', fips: '42043', stateCode: 'PA' },
    { name: 'Delaware County', fips: '42045', stateCode: 'PA' },
    { name: 'Elk County', fips: '42047', stateCode: 'PA' },
    { name: 'Erie County', fips: '42049', stateCode: 'PA' },
    { name: 'Fayette County', fips: '42051', stateCode: 'PA' },
    { name: 'Forest County', fips: '42053', stateCode: 'PA' },
    { name: 'Franklin County', fips: '42055', stateCode: 'PA' },
    { name: 'Fulton County', fips: '42057', stateCode: 'PA' },
    { name: 'Greene County', fips: '42059', stateCode: 'PA' },
    { name: 'Huntingdon County', fips: '42061', stateCode: 'PA' },
    { name: 'Indiana County', fips: '42063', stateCode: 'PA' },
    { name: 'Jefferson County', fips: '42065', stateCode: 'PA' },
    { name: 'Juniata County', fips: '42067', stateCode: 'PA' },
    { name: 'Lackawanna County', fips: '42069', stateCode: 'PA' },
    { name: 'Lancaster County', fips: '42071', stateCode: 'PA' },
    { name: 'Lawrence County', fips: '42073', stateCode: 'PA' },
    { name: 'Lebanon County', fips: '42075', stateCode: 'PA' },
    { name: 'Lehigh County', fips: '42077', stateCode: 'PA' },
    { name: 'Luzerne County', fips: '42079', stateCode: 'PA' },
    { name: 'Lycoming County', fips: '42081', stateCode: 'PA' },
    { name: 'McKean County', fips: '42083', stateCode: 'PA' },
    { name: 'Mercer County', fips: '42085', stateCode: 'PA' },
    { name: 'Mifflin County', fips: '42087', stateCode: 'PA' },
    { name: 'Monroe County', fips: '42089', stateCode: 'PA' },
    { name: 'Montgomery County', fips: '42091', stateCode: 'PA' },
    { name: 'Montour County', fips: '42093', stateCode: 'PA' },
    { name: 'Northampton County', fips: '42095', stateCode: 'PA' },
    { name: 'Northumberland County', fips: '42097', stateCode: 'PA' },
    { name: 'Perry County', fips: '42099', stateCode: 'PA' },
    { name: 'Philadelphia County', fips: '42101', stateCode: 'PA' },
    { name: 'Pike County', fips: '42103', stateCode: 'PA' },
    { name: 'Potter County', fips: '42105', stateCode: 'PA' },
    { name: 'Schuylkill County', fips: '42107', stateCode: 'PA' },
    { name: 'Snyder County', fips: '42109', stateCode: 'PA' },
    { name: 'Somerset County', fips: '42111', stateCode: 'PA' },
    { name: 'Sullivan County', fips: '42113', stateCode: 'PA' },
    { name: 'Susquehanna County', fips: '42115', stateCode: 'PA' },
    { name: 'Tioga County', fips: '42117', stateCode: 'PA' },
    { name: 'Union County', fips: '42119', stateCode: 'PA' },
    { name: 'Venango County', fips: '42121', stateCode: 'PA' },
    { name: 'Warren County', fips: '42123', stateCode: 'PA' },
    { name: 'Washington County', fips: '42125', stateCode: 'PA' },
    { name: 'Wayne County', fips: '42127', stateCode: 'PA' },
    { name: 'Westmoreland County', fips: '42129', stateCode: 'PA' },
    { name: 'Wyoming County', fips: '42131', stateCode: 'PA' },
    { name: 'York County', fips: '42133', stateCode: 'PA' },
  ],
  'OH': [
    { name: 'Adams County', fips: '39001', stateCode: 'OH' },
    { name: 'Allen County', fips: '39003', stateCode: 'OH' },
    { name: 'Ashland County', fips: '39005', stateCode: 'OH' },
    { name: 'Ashtabula County', fips: '39007', stateCode: 'OH' },
    { name: 'Athens County', fips: '39009', stateCode: 'OH' },
    { name: 'Auglaize County', fips: '39011', stateCode: 'OH' },
    { name: 'Belmont County', fips: '39013', stateCode: 'OH' },
    { name: 'Brown County', fips: '39015', stateCode: 'OH' },
    { name: 'Butler County', fips: '39017', stateCode: 'OH' },
    { name: 'Carroll County', fips: '39019', stateCode: 'OH' },
    { name: 'Champaign County', fips: '39021', stateCode: 'OH' },
    { name: 'Clark County', fips: '39023', stateCode: 'OH' },
    { name: 'Clermont County', fips: '39025', stateCode: 'OH' },
    { name: 'Clinton County', fips: '39027', stateCode: 'OH' },
    { name: 'Columbiana County', fips: '39029', stateCode: 'OH' },
    { name: 'Coshocton County', fips: '39031', stateCode: 'OH' },
    { name: 'Crawford County', fips: '39033', stateCode: 'OH' },
    { name: 'Cuyahoga County', fips: '39035', stateCode: 'OH' },
    { name: 'Darke County', fips: '39037', stateCode: 'OH' },
    { name: 'Defiance County', fips: '39039', stateCode: 'OH' },
    { name: 'Delaware County', fips: '39041', stateCode: 'OH' },
    { name: 'Erie County', fips: '39043', stateCode: 'OH' },
    { name: 'Fairfield County', fips: '39045', stateCode: 'OH' },
    { name: 'Fayette County', fips: '39047', stateCode: 'OH' },
    { name: 'Franklin County', fips: '39049', stateCode: 'OH' },
    { name: 'Fulton County', fips: '39051', stateCode: 'OH' },
    { name: 'Gallia County', fips: '39053', stateCode: 'OH' },
    { name: 'Geauga County', fips: '39055', stateCode: 'OH' },
    { name: 'Greene County', fips: '39057', stateCode: 'OH' },
    { name: 'Guernsey County', fips: '39059', stateCode: 'OH' },
    { name: 'Hamilton County', fips: '39061', stateCode: 'OH' },
    { name: 'Hancock County', fips: '39063', stateCode: 'OH' },
    { name: 'Hardin County', fips: '39065', stateCode: 'OH' },
    { name: 'Harrison County', fips: '39067', stateCode: 'OH' },
    { name: 'Henry County', fips: '39069', stateCode: 'OH' },
    { name: 'Highland County', fips: '39071', stateCode: 'OH' },
    { name: 'Hocking County', fips: '39073', stateCode: 'OH' },
    { name: 'Holmes County', fips: '39075', stateCode: 'OH' },
    { name: 'Huron County', fips: '39077', stateCode: 'OH' },
    { name: 'Jackson County', fips: '39079', stateCode: 'OH' },
    { name: 'Jefferson County', fips: '39081', stateCode: 'OH' },
    { name: 'Knox County', fips: '39083', stateCode: 'OH' },
    { name: 'Lake County', fips: '39085', stateCode: 'OH' },
    { name: 'Lawrence County', fips: '39087', stateCode: 'OH' },
    { name: 'Licking County', fips: '39089', stateCode: 'OH' },
    { name: 'Logan County', fips: '39091', stateCode: 'OH' },
    { name: 'Lorain County', fips: '39093', stateCode: 'OH' },
    { name: 'Lucas County', fips: '39095', stateCode: 'OH' },
    { name: 'Madison County', fips: '39097', stateCode: 'OH' },
    { name: 'Mahoning County', fips: '39099', stateCode: 'OH' },
    { name: 'Marion County', fips: '39101', stateCode: 'OH' },
    { name: 'Medina County', fips: '39103', stateCode: 'OH' },
    { name: 'Meigs County', fips: '39105', stateCode: 'OH' },
    { name: 'Mercer County', fips: '39107', stateCode: 'OH' },
    { name: 'Miami County', fips: '39109', stateCode: 'OH' },
    { name: 'Monroe County', fips: '39111', stateCode: 'OH' },
    { name: 'Montgomery County', fips: '39113', stateCode: 'OH' },
    { name: 'Morgan County', fips: '39115', stateCode: 'OH' },
    { name: 'Morrow County', fips: '39117', stateCode: 'OH' },
    { name: 'Muskingum County', fips: '39119', stateCode: 'OH' },
    { name: 'Noble County', fips: '39121', stateCode: 'OH' },
    { name: 'Ottawa County', fips: '39123', stateCode: 'OH' },
    { name: 'Paulding County', fips: '39125', stateCode: 'OH' },
    { name: 'Perry County', fips: '39127', stateCode: 'OH' },
    { name: 'Pickaway County', fips: '39129', stateCode: 'OH' },
    { name: 'Pike County', fips: '39131', stateCode: 'OH' },
    { name: 'Portage County', fips: '39133', stateCode: 'OH' },
    { name: 'Preble County', fips: '39135', stateCode: 'OH' },
    { name: 'Putnam County', fips: '39137', stateCode: 'OH' },
    { name: 'Richland County', fips: '39139', stateCode: 'OH' },
    { name: 'Ross County', fips: '39141', stateCode: 'OH' },
    { name: 'Sandusky County', fips: '39143', stateCode: 'OH' },
    { name: 'Scioto County', fips: '39145', stateCode: 'OH' },
    { name: 'Seneca County', fips: '39147', stateCode: 'OH' },
    { name: 'Shelby County', fips: '39149', stateCode: 'OH' },
    { name: 'Stark County', fips: '39151', stateCode: 'OH' },
    { name: 'Summit County', fips: '39153', stateCode: 'OH' },
    { name: 'Trumbull County', fips: '39155', stateCode: 'OH' },
    { name: 'Tuscarawas County', fips: '39157', stateCode: 'OH' },
    { name: 'Union County', fips: '39159', stateCode: 'OH' },
    { name: 'Van Wert County', fips: '39161', stateCode: 'OH' },
    { name: 'Vinton County', fips: '39163', stateCode: 'OH' },
    { name: 'Warren County', fips: '39165', stateCode: 'OH' },
    { name: 'Washington County', fips: '39167', stateCode: 'OH' },
    { name: 'Wayne County', fips: '39169', stateCode: 'OH' },
    { name: 'Williams County', fips: '39171', stateCode: 'OH' },
    { name: 'Wood County', fips: '39173', stateCode: 'OH' },
    { name: 'Wyandot County', fips: '39175', stateCode: 'OH' },
  ],
  'AK': [
    { name: 'Aleutians East Borough', fips: '02013', stateCode: 'AK' },
    { name: 'Aleutians West Census Area', fips: '02016', stateCode: 'AK' },
    { name: 'Anchorage Municipality', fips: '02020', stateCode: 'AK' },
    { name: 'Bethel Census Area', fips: '02050', stateCode: 'AK' },
    { name: 'Bristol Bay Borough', fips: '02060', stateCode: 'AK' },
    { name: 'Denali Borough', fips: '02068', stateCode: 'AK' },
    { name: 'Dillingham Census Area', fips: '02070', stateCode: 'AK' },
    { name: 'Fairbanks North Star Borough', fips: '02090', stateCode: 'AK' },
    { name: 'Haines Borough', fips: '02100', stateCode: 'AK' },
    { name: 'Hoonah-Angoon Census Area', fips: '02105', stateCode: 'AK' },
    { name: 'Juneau City and Borough', fips: '02110', stateCode: 'AK' },
    { name: 'Kenai Peninsula Borough', fips: '02122', stateCode: 'AK' },
    { name: 'Ketchikan Gateway Borough', fips: '02130', stateCode: 'AK' },
    { name: 'Kodiak Island Borough', fips: '02150', stateCode: 'AK' },
    { name: 'Kusilvak Census Area', fips: '02158', stateCode: 'AK' },
    { name: 'Lake and Peninsula Borough', fips: '02164', stateCode: 'AK' },
    { name: 'Matanuska-Susitna Borough', fips: '02170', stateCode: 'AK' },
    { name: 'Nome Census Area', fips: '02180', stateCode: 'AK' },
    { name: 'North Slope Borough', fips: '02185', stateCode: 'AK' },
    { name: 'Northwest Arctic Borough', fips: '02188', stateCode: 'AK' },
    { name: 'Petersburg Borough', fips: '02195', stateCode: 'AK' },
    { name: 'Prince of Wales-Hyder Census Area', fips: '02198', stateCode: 'AK' },
    { name: 'Sitka City and Borough', fips: '02220', stateCode: 'AK' },
    { name: 'Skagway Borough', fips: '02230', stateCode: 'AK' },
    { name: 'Southeast Fairbanks Census Area', fips: '02240', stateCode: 'AK' },
    { name: 'Wrangell City and Borough', fips: '02275', stateCode: 'AK' },
    { name: 'Yakutat City and Borough', fips: '02282', stateCode: 'AK' },
    { name: 'Yukon-Koyukuk Census Area', fips: '02290', stateCode: 'AK' },
  ],
};

export function getStateSubdivisionType(stateCode: string): string {
  const state = US_STATES.find(s => s.code === stateCode);
  return state?.subdivisionType || 'county';
}

export function getCountiesForState(stateCode: string): County[] {
  return SAMPLE_COUNTIES[stateCode] || [];
}