#!/usr/bin/env node

// Post-build script to ensure ESM compatibility for deployment
// This runs after npm run build to fix the bundled index.js

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('Running post-build ESM compatibility fix...');

const distPath = path.join(__dirname, '..', 'dist');
const indexPath = path.join(distPath, 'index.js');
const esmEntryPath = path.join(distPath, 'esm-entry.js');
const serverEsmEntryPath = path.join(__dirname, '..', 'server', 'esm-entry.js');

try {
  // Check if dist directory exists
  if (!fs.existsSync(distPath)) {
    console.log('Dist directory does not exist. Run npm run build first.');
    process.exit(1);
  }

  // Backup the bundled version if it exists and has __dirname issues
  if (fs.existsSync(indexPath)) {
    const indexContent = fs.readFileSync(indexPath, 'utf-8');
    if (indexContent.includes('__dirname') || indexContent.includes('__require')) {
      console.log('Found problematic bundled index.js, replacing with ESM-compatible version...');
      
      // Backup the bundled version
      fs.renameSync(indexPath, path.join(distPath, 'index-bundled.js'));
      
      // Copy ESM entry point
      if (fs.existsSync(serverEsmEntryPath)) {
        fs.copyFileSync(serverEsmEntryPath, esmEntryPath);
      }
      
      // Create new ESM-compatible index.js
      const esmIndexContent = `// ESM-compatible index.js for Trade Scout deployment
// Auto-generated by post-build script

import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import path from 'path';

// ESM compatibility setup
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Set production environment
process.env.NODE_ENV = process.env.NODE_ENV || 'production';

console.log('Trade Scout - ESM Production Entry');
console.log('Environment:', process.env.NODE_ENV);
console.log('Node version:', process.version);

// Load the working ESM application
try {
  await import('./esm-entry.js');
} catch (error) {
  console.error('ESM deployment failed:', error);
  console.error('Stack trace:', error.stack);
  process.exit(1);
}`;
      
      fs.writeFileSync(indexPath, esmIndexContent);
      console.log('✅ ESM compatibility fix applied successfully');
      console.log('- Bundled version saved as index-bundled.js');
      console.log('- New ESM-compatible index.js created');
      console.log('- ESM entry point copied to dist/');
    } else {
      console.log('✅ Index.js already appears to be ESM-compatible');
    }
  } else {
    console.log('No index.js found in dist directory');
  }

} catch (error) {
  console.error('Post-build ESM fix failed:', error);
  process.exit(1);
}

console.log('Post-build ESM compatibility fix completed');