import { db } from '../server/db.js';
import { counties } from '../shared/schema.js';
import { eq } from 'drizzle-orm';

// Texas Counties - All 254 counties
const texasCounties = [
  { name: "Anderson County", fips: "48001", stateCode: "TX" },
  { name: "Andrews County", fips: "48003", stateCode: "TX" },
  { name: "Angelina County", fips: "48005", stateCode: "TX" },
  { name: "Aransas County", fips: "48007", stateCode: "TX" },
  { name: "Archer County", fips: "48009", stateCode: "TX" },
  { name: "Armstrong County", fips: "48011", stateCode: "TX" },
  { name: "Atascosa County", fips: "48013", stateCode: "TX" },
  { name: "Austin County", fips: "48015", stateCode: "TX" },
  { name: "Bailey County", fips: "48017", stateCode: "TX" },
  { name: "Bandera County", fips: "48019", stateCode: "TX" },
  { name: "Bastrop County", fips: "48021", stateCode: "TX" },
  { name: "Baylor County", fips: "48023", stateCode: "TX" },
  { name: "Bee County", fips: "48025", stateCode: "TX" },
  { name: "Bell County", fips: "48027", stateCode: "TX" },
  { name: "Bexar County", fips: "48029", stateCode: "TX" },
  { name: "Blanco County", fips: "48031", stateCode: "TX" },
  { name: "Borden County", fips: "48033", stateCode: "TX" },
  { name: "Bosque County", fips: "48035", stateCode: "TX" },
  { name: "Bowie County", fips: "48037", stateCode: "TX" },
  { name: "Brazoria County", fips: "48039", stateCode: "TX" },
  { name: "Brazos County", fips: "48041", stateCode: "TX" },
  { name: "Brewster County", fips: "48043", stateCode: "TX" },
  { name: "Briscoe County", fips: "48045", stateCode: "TX" },
  { name: "Brooks County", fips: "48047", stateCode: "TX" },
  { name: "Brown County", fips: "48049", stateCode: "TX" },
  { name: "Burleson County", fips: "48051", stateCode: "TX" },
  { name: "Burnet County", fips: "48053", stateCode: "TX" },
  { name: "Caldwell County", fips: "48055", stateCode: "TX" },
  { name: "Calhoun County", fips: "48057", stateCode: "TX" },
  { name: "Callahan County", fips: "48059", stateCode: "TX" },
  { name: "Cameron County", fips: "48061", stateCode: "TX" },
  { name: "Camp County", fips: "48063", stateCode: "TX" },
  { name: "Carson County", fips: "48065", stateCode: "TX" },
  { name: "Cass County", fips: "48067", stateCode: "TX" },
  { name: "Castro County", fips: "48069", stateCode: "TX" },
  { name: "Chambers County", fips: "48071", stateCode: "TX" },
  { name: "Cherokee County", fips: "48073", stateCode: "TX" },
  { name: "Childress County", fips: "48075", stateCode: "TX" },
  { name: "Clay County", fips: "48077", stateCode: "TX" },
  { name: "Cochran County", fips: "48079", stateCode: "TX" },
  { name: "Coke County", fips: "48081", stateCode: "TX" },
  { name: "Coleman County", fips: "48083", stateCode: "TX" },
  { name: "Collin County", fips: "48085", stateCode: "TX" },
  { name: "Collingsworth County", fips: "48087", stateCode: "TX" },
  { name: "Colorado County", fips: "48089", stateCode: "TX" },
  { name: "Comal County", fips: "48091", stateCode: "TX" },
  { name: "Comanche County", fips: "48093", stateCode: "TX" },
  { name: "Concho County", fips: "48095", stateCode: "TX" },
  { name: "Cooke County", fips: "48097", stateCode: "TX" },
  { name: "Coryell County", fips: "48099", stateCode: "TX" },
  { name: "Cottle County", fips: "48101", stateCode: "TX" },
  { name: "Crane County", fips: "48103", stateCode: "TX" },
  { name: "Crockett County", fips: "48105", stateCode: "TX" },
  { name: "Crosby County", fips: "48107", stateCode: "TX" },
  { name: "Culberson County", fips: "48109", stateCode: "TX" },
  { name: "Dallam County", fips: "48111", stateCode: "TX" },
  { name: "Dallas County", fips: "48113", stateCode: "TX" },
  { name: "Dawson County", fips: "48115", stateCode: "TX" },
  { name: "Deaf Smith County", fips: "48117", stateCode: "TX" },
  { name: "Delta County", fips: "48119", stateCode: "TX" },
  { name: "Denton County", fips: "48121", stateCode: "TX" },
  { name: "DeWitt County", fips: "48123", stateCode: "TX" },
  { name: "Dickens County", fips: "48125", stateCode: "TX" },
  { name: "Dimmit County", fips: "48127", stateCode: "TX" },
  { name: "Donley County", fips: "48129", stateCode: "TX" },
  { name: "Duval County", fips: "48131", stateCode: "TX" },
  { name: "Eastland County", fips: "48133", stateCode: "TX" },
  { name: "Ector County", fips: "48135", stateCode: "TX" },
  { name: "Edwards County", fips: "48137", stateCode: "TX" },
  { name: "Ellis County", fips: "48139", stateCode: "TX" },
  { name: "El Paso County", fips: "48141", stateCode: "TX" },
  { name: "Erath County", fips: "48143", stateCode: "TX" },
  { name: "Falls County", fips: "48145", stateCode: "TX" },
  { name: "Fannin County", fips: "48147", stateCode: "TX" },
  { name: "Fayette County", fips: "48149", stateCode: "TX" },
  { name: "Fisher County", fips: "48151", stateCode: "TX" },
  { name: "Floyd County", fips: "48153", stateCode: "TX" },
  { name: "Foard County", fips: "48155", stateCode: "TX" },
  { name: "Fort Bend County", fips: "48157", stateCode: "TX" },
  { name: "Franklin County", fips: "48159", stateCode: "TX" },
  { name: "Freestone County", fips: "48161", stateCode: "TX" },
  { name: "Frio County", fips: "48163", stateCode: "TX" },
  { name: "Gaines County", fips: "48165", stateCode: "TX" },
  { name: "Galveston County", fips: "48167", stateCode: "TX" },
  { name: "Garza County", fips: "48169", stateCode: "TX" },
  { name: "Gillespie County", fips: "48171", stateCode: "TX" },
  { name: "Glasscock County", fips: "48173", stateCode: "TX" },
  { name: "Goliad County", fips: "48175", stateCode: "TX" },
  { name: "Gonzales County", fips: "48177", stateCode: "TX" },
  { name: "Gray County", fips: "48179", stateCode: "TX" },
  { name: "Grayson County", fips: "48181", stateCode: "TX" },
  { name: "Gregg County", fips: "48183", stateCode: "TX" },
  { name: "Grimes County", fips: "48185", stateCode: "TX" },
  { name: "Guadalupe County", fips: "48187", stateCode: "TX" },
  { name: "Hale County", fips: "48189", stateCode: "TX" },
  { name: "Hall County", fips: "48191", stateCode: "TX" },
  { name: "Hamilton County", fips: "48193", stateCode: "TX" },
  { name: "Hansford County", fips: "48195", stateCode: "TX" },
  { name: "Hardeman County", fips: "48197", stateCode: "TX" },
  { name: "Hardin County", fips: "48199", stateCode: "TX" },
  { name: "Harris County", fips: "48201", stateCode: "TX" },
  { name: "Harrison County", fips: "48203", stateCode: "TX" },
  { name: "Hartley County", fips: "48205", stateCode: "TX" },
  { name: "Haskell County", fips: "48207", stateCode: "TX" },
  { name: "Hays County", fips: "48209", stateCode: "TX" },
  { name: "Hemphill County", fips: "48211", stateCode: "TX" },
  { name: "Henderson County", fips: "48213", stateCode: "TX" },
  { name: "Hidalgo County", fips: "48215", stateCode: "TX" },
  { name: "Hill County", fips: "48217", stateCode: "TX" },
  { name: "Hockley County", fips: "48219", stateCode: "TX" },
  { name: "Hood County", fips: "48221", stateCode: "TX" },
  { name: "Hopkins County", fips: "48223", stateCode: "TX" },
  { name: "Houston County", fips: "48225", stateCode: "TX" },
  { name: "Howard County", fips: "48227", stateCode: "TX" },
  { name: "Hudspeth County", fips: "48229", stateCode: "TX" },
  { name: "Hunt County", fips: "48231", stateCode: "TX" },
  { name: "Hutchinson County", fips: "48233", stateCode: "TX" },
  { name: "Irion County", fips: "48235", stateCode: "TX" },
  { name: "Jack County", fips: "48237", stateCode: "TX" },
  { name: "Jackson County", fips: "48239", stateCode: "TX" },
  { name: "Jasper County", fips: "48241", stateCode: "TX" },
  { name: "Jeff Davis County", fips: "48243", stateCode: "TX" },
  { name: "Jefferson County", fips: "48245", stateCode: "TX" },
  { name: "Jim Hogg County", fips: "48247", stateCode: "TX" },
  { name: "Jim Wells County", fips: "48249", stateCode: "TX" },
  { name: "Johnson County", fips: "48251", stateCode: "TX" },
  { name: "Jones County", fips: "48253", stateCode: "TX" },
  { name: "Karnes County", fips: "48255", stateCode: "TX" },
  { name: "Kaufman County", fips: "48257", stateCode: "TX" },
  { name: "Kendall County", fips: "48259", stateCode: "TX" },
  { name: "Kenedy County", fips: "48261", stateCode: "TX" },
  { name: "Kent County", fips: "48263", stateCode: "TX" },
  { name: "Kerr County", fips: "48265", stateCode: "TX" },
  { name: "Kimble County", fips: "48267", stateCode: "TX" },
  { name: "King County", fips: "48269", stateCode: "TX" },
  { name: "Kinney County", fips: "48271", stateCode: "TX" },
  { name: "Kleberg County", fips: "48273", stateCode: "TX" },
  { name: "Knox County", fips: "48275", stateCode: "TX" },
  { name: "Lamar County", fips: "48277", stateCode: "TX" },
  { name: "Lamb County", fips: "48279", stateCode: "TX" },
  { name: "Lampasas County", fips: "48281", stateCode: "TX" },
  { name: "La Salle County", fips: "48283", stateCode: "TX" },
  { name: "Lavaca County", fips: "48285", stateCode: "TX" },
  { name: "Lee County", fips: "48287", stateCode: "TX" },
  { name: "Leon County", fips: "48289", stateCode: "TX" },
  { name: "Liberty County", fips: "48291", stateCode: "TX" },
  { name: "Limestone County", fips: "48293", stateCode: "TX" },
  { name: "Lipscomb County", fips: "48295", stateCode: "TX" },
  { name: "Live Oak County", fips: "48297", stateCode: "TX" },
  { name: "Llano County", fips: "48299", stateCode: "TX" },
  { name: "Loving County", fips: "48301", stateCode: "TX" },
  { name: "Lubbock County", fips: "48303", stateCode: "TX" },
  { name: "Lynn County", fips: "48305", stateCode: "TX" },
  { name: "McCulloch County", fips: "48307", stateCode: "TX" },
  { name: "McLennan County", fips: "48309", stateCode: "TX" },
  { name: "McMullen County", fips: "48311", stateCode: "TX" },
  { name: "Madison County", fips: "48313", stateCode: "TX" },
  { name: "Marion County", fips: "48315", stateCode: "TX" },
  { name: "Martin County", fips: "48317", stateCode: "TX" },
  { name: "Mason County", fips: "48319", stateCode: "TX" },
  { name: "Matagorda County", fips: "48321", stateCode: "TX" },
  { name: "Maverick County", fips: "48323", stateCode: "TX" },
  { name: "Medina County", fips: "48325", stateCode: "TX" },
  { name: "Menard County", fips: "48327", stateCode: "TX" },
  { name: "Midland County", fips: "48329", stateCode: "TX" },
  { name: "Milam County", fips: "48331", stateCode: "TX" },
  { name: "Mills County", fips: "48333", stateCode: "TX" },
  { name: "Mitchell County", fips: "48335", stateCode: "TX" },
  { name: "Montague County", fips: "48337", stateCode: "TX" },
  { name: "Montgomery County", fips: "48339", stateCode: "TX" },
  { name: "Moore County", fips: "48341", stateCode: "TX" },
  { name: "Morris County", fips: "48343", stateCode: "TX" },
  { name: "Motley County", fips: "48345", stateCode: "TX" },
  { name: "Nacogdoches County", fips: "48347", stateCode: "TX" },
  { name: "Navarro County", fips: "48349", stateCode: "TX" },
  { name: "Newton County", fips: "48351", stateCode: "TX" },
  { name: "Nolan County", fips: "48353", stateCode: "TX" },
  { name: "Nueces County", fips: "48355", stateCode: "TX" },
  { name: "Ochiltree County", fips: "48357", stateCode: "TX" },
  { name: "Oldham County", fips: "48359", stateCode: "TX" },
  { name: "Orange County", fips: "48361", stateCode: "TX" },
  { name: "Palo Pinto County", fips: "48363", stateCode: "TX" },
  { name: "Panola County", fips: "48365", stateCode: "TX" },
  { name: "Parker County", fips: "48367", stateCode: "TX" },
  { name: "Parmer County", fips: "48369", stateCode: "TX" },
  { name: "Pecos County", fips: "48371", stateCode: "TX" },
  { name: "Polk County", fips: "48373", stateCode: "TX" },
  { name: "Potter County", fips: "48375", stateCode: "TX" },
  { name: "Presidio County", fips: "48377", stateCode: "TX" },
  { name: "Rains County", fips: "48379", stateCode: "TX" },
  { name: "Randall County", fips: "48381", stateCode: "TX" },
  { name: "Reagan County", fips: "48383", stateCode: "TX" },
  { name: "Real County", fips: "48385", stateCode: "TX" },
  { name: "Red River County", fips: "48387", stateCode: "TX" },
  { name: "Reeves County", fips: "48389", stateCode: "TX" },
  { name: "Refugio County", fips: "48391", stateCode: "TX" },
  { name: "Roberts County", fips: "48393", stateCode: "TX" },
  { name: "Robertson County", fips: "48395", stateCode: "TX" },
  { name: "Rockwall County", fips: "48397", stateCode: "TX" },
  { name: "Runnels County", fips: "48399", stateCode: "TX" },
  { name: "Rusk County", fips: "48401", stateCode: "TX" },
  { name: "Sabine County", fips: "48403", stateCode: "TX" },
  { name: "San Augustine County", fips: "48405", stateCode: "TX" },
  { name: "San Jacinto County", fips: "48407", stateCode: "TX" },
  { name: "San Patricio County", fips: "48409", stateCode: "TX" },
  { name: "San Saba County", fips: "48411", stateCode: "TX" },
  { name: "Schleicher County", fips: "48413", stateCode: "TX" },
  { name: "Scurry County", fips: "48415", stateCode: "TX" },
  { name: "Shackelford County", fips: "48417", stateCode: "TX" },
  { name: "Shelby County", fips: "48419", stateCode: "TX" },
  { name: "Sherman County", fips: "48421", stateCode: "TX" },
  { name: "Smith County", fips: "48423", stateCode: "TX" },
  { name: "Somervell County", fips: "48425", stateCode: "TX" },
  { name: "Starr County", fips: "48427", stateCode: "TX" },
  { name: "Stephens County", fips: "48429", stateCode: "TX" },
  { name: "Sterling County", fips: "48431", stateCode: "TX" },
  { name: "Stonewall County", fips: "48433", stateCode: "TX" },
  { name: "Sutton County", fips: "48435", stateCode: "TX" },
  { name: "Swisher County", fips: "48437", stateCode: "TX" },
  { name: "Tarrant County", fips: "48439", stateCode: "TX" },
  { name: "Taylor County", fips: "48441", stateCode: "TX" },
  { name: "Terrell County", fips: "48443", stateCode: "TX" },
  { name: "Terry County", fips: "48445", stateCode: "TX" },
  { name: "Throckmorton County", fips: "48447", stateCode: "TX" },
  { name: "Titus County", fips: "48449", stateCode: "TX" },
  { name: "Tom Green County", fips: "48451", stateCode: "TX" },
  { name: "Travis County", fips: "48453", stateCode: "TX" },
  { name: "Trinity County", fips: "48455", stateCode: "TX" },
  { name: "Tyler County", fips: "48457", stateCode: "TX" },
  { name: "Upshur County", fips: "48459", stateCode: "TX" },
  { name: "Upton County", fips: "48461", stateCode: "TX" },
  { name: "Uvalde County", fips: "48463", stateCode: "TX" },
  { name: "Val Verde County", fips: "48465", stateCode: "TX" },
  { name: "Van Zandt County", fips: "48467", stateCode: "TX" },
  { name: "Victoria County", fips: "48469", stateCode: "TX" },
  { name: "Walker County", fips: "48471", stateCode: "TX" },
  { name: "Waller County", fips: "48473", stateCode: "TX" },
  { name: "Ward County", fips: "48475", stateCode: "TX" },
  { name: "Washington County", fips: "48477", stateCode: "TX" },
  { name: "Webb County", fips: "48479", stateCode: "TX" },
  { name: "Wharton County", fips: "48481", stateCode: "TX" },
  { name: "Wheeler County", fips: "48483", stateCode: "TX" },
  { name: "Wichita County", fips: "48485", stateCode: "TX" },
  { name: "Wilbarger County", fips: "48487", stateCode: "TX" },
  { name: "Willacy County", fips: "48489", stateCode: "TX" },
  { name: "Williamson County", fips: "48491", stateCode: "TX" },
  { name: "Wilson County", fips: "48493", stateCode: "TX" },
  { name: "Winkler County", fips: "48495", stateCode: "TX" },
  { name: "Wise County", fips: "48497", stateCode: "TX" },
  { name: "Wood County", fips: "48499", stateCode: "TX" },
  { name: "Yoakum County", fips: "48501", stateCode: "TX" },
  { name: "Young County", fips: "48503", stateCode: "TX" },
  { name: "Zapata County", fips: "48505", stateCode: "TX" },
  { name: "Zavala County", fips: "48507", stateCode: "TX" }
];

export async function seedTexasCounties() {
  try {
    console.log("Starting Texas county seeding...");
    
    // Remove existing Texas counties to avoid duplicates
    await db.delete(counties).where(eq(counties.stateCode, 'TX'));
    console.log("Cleared existing Texas county data");

    // Insert Texas counties in batches
    const batchSize = 50;
    for (let i = 0; i < texasCounties.length; i += batchSize) {
      const batch = texasCounties.slice(i, i + batchSize);
      await db.insert(counties).values(batch);
      console.log(`Inserted Texas batch ${Math.floor(i / batchSize) + 1}, counties ${i + 1}-${Math.min(i + batchSize, texasCounties.length)}`);
    }

    console.log(`Successfully seeded ${texasCounties.length} Texas counties`);
    
    // Verify the data
    const count = await db.select().from(counties).where(eq(counties.stateCode, 'TX'));
    console.log(`Total Texas counties in database: ${count.length}`);
    
    return count.length;
  } catch (error) {
    console.error("Error seeding Texas counties:", error);
    throw error;
  }
}

// Run the seeding function immediately
seedTexasCounties()
  .then(() => {
    console.log("Texas county seeding completed successfully");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Texas county seeding failed:", error);
    process.exit(1);
  });