import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";
import mammoth from "mammoth";
import { db } from "../../src/db/drizzle-mock";

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const AUTO_CACHE_DIR = path.join(__dirname, "..", "cache", "autogenerated");
const MANUAL_CACHE_DIR = path.join(__dirname, "..", "cache", "manual");
const KNOWLEDGE_BASE_DIR = path.join(__dirname, "..", "..", "data", "TradeScout Brain");
const CHAT_CORPUS_FILE = path.join(AUTO_CACHE_DIR, "chat_corpus.json");
const KNOWLEDGE_EXTENSIONS = new Set([".md", ".txt", ".docx"]);
const knowledgeTextCache: Record<string, { mtimeMs: number; text: string }> = {};

interface CacheResult {
  source: "manual" | "auto" | "database" | "internet" | "none";
  data: any;
  timestamp?: string;
  itemCount?: number;
  layer?: number;
}

interface KnowledgeRequest {
  message: string;
  userId?: string;
  countyCode?: string;
  stateCode?: string;
}

interface KnowledgeResponse {
  answer: string;
  sources: string[];
  layer: 1 | 2 | 3 | 4;
  confidence: "high" | "medium" | "low";
}

/**
 * Read a cached JSON file
 */
function readCacheFile(filename: string, isManual = false): any | null {
  try {
    const dir = isManual ? MANUAL_CACHE_DIR : AUTO_CACHE_DIR;
    const filepath = path.join(dir, filename);

    if (!fs.existsSync(filepath)) {
      return null;
    }

    const content = fs.readFileSync(filepath, "utf-8");
    return JSON.parse(content);
  } catch (error) {
    console.error(`Error reading cache ${filename}:`, error);
    return null;
  }
}

function walkKnowledgeFiles(dir: string): string[] {
  const files: string[] = [];
  if (!fs.existsSync(dir)) return files;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkKnowledgeFiles(fullPath));
    } else if (KNOWLEDGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      files.push(fullPath);
    }
  }
  return files;
}

async function loadKnowledgeText(filePath: string): Promise<string | null> {
  try {
    const stats = fs.statSync(filePath);
    const cached = knowledgeTextCache[filePath];
    if (cached && cached.mtimeMs === stats.mtimeMs) {
      return cached.text;
    }

    const ext = path.extname(filePath).toLowerCase();
    let text: string | null = null;

    if (ext === ".docx") {
      const result = await mammoth.extractRawText({ path: filePath });
      text = result.value;
    } else {
      text = fs.readFileSync(filePath, "utf-8");
    }

    const clean = text?.trim();
    if (clean) {
      knowledgeTextCache[filePath] = { mtimeMs: stats.mtimeMs, text: clean };
      return clean;
    }
  } catch (error) {
    console.error(`Error loading knowledge file ${filePath}:`, error);
  }

  return null;
}

function buildSnippet(text: string, terms: string[]): string {
  const lower = text.toLowerCase();
  const term = terms.find((t) => lower.includes(t));
  if (!term) {
    return text.slice(0, 600);
  }

  const idx = lower.indexOf(term);
  const start = Math.max(0, idx - 200);
  const end = Math.min(text.length, idx + 800);
  return text.slice(start, end);
}

async function searchLocalKnowledgeBase(message: string): Promise<CacheResult> {
  try {
    if (!fs.existsSync(KNOWLEDGE_BASE_DIR)) {
      return { source: "none", data: null, layer: 0 };
    }

    const files = walkKnowledgeFiles(KNOWLEDGE_BASE_DIR);
    if (!files.length) {
      return { source: "none", data: null, layer: 0 };
    }

    const terms = message
      .toLowerCase()
      .split(/\s+/)
      .map((t) => t.trim())
      .filter((t) => t.length > 3);

    const matches: Array<{ file: string; snippet: string; score: number }> = [];

    for (const file of files) {
      const text = await loadKnowledgeText(file);
      if (!text) continue;

      const lower = text.toLowerCase();
      let score = 0;
      for (const term of terms) {
        if (lower.includes(term)) {
          score += 1;
        }
      }

      if (score > 0) {
        matches.push({
          file: path.relative(KNOWLEDGE_BASE_DIR, file),
          snippet: buildSnippet(text, terms),
          score,
        });
      }
    }

    matches.sort((a, b) => b.score - a.score);
    const top = matches.slice(0, 3);

    if (top.length) {
      return {
        source: "manual",
        data: top,
        itemCount: top.length,
        layer: 1,
      };
    }
  } catch (error) {
    console.error("Local knowledge search error:", error);
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * Write/update a manual knowledge JSON file
 */
export function writeManualCacheFile(filename: string, data: any): void {
  try {
    if (!fs.existsSync(MANUAL_CACHE_DIR)) {
      fs.mkdirSync(MANUAL_CACHE_DIR, { recursive: true });
    }
    const filepath = path.join(MANUAL_CACHE_DIR, filename);
    fs.writeFileSync(filepath, JSON.stringify(data, null, 2), "utf-8");
  } catch (error) {
    console.error(`Error writing manual cache ${filename}:`, error);
    throw error;
  }
}

/**
 * Append non-sensitive Q&A pairs from Scout conversations to the auto cache.
 * Skips obvious PII (emails, phones, credit cards, SSNs) and dedupes by question text.
 */
export function appendChatKnowledge(entry: {
  question: string;
  answer: string;
  userId?: string;
  countyCode?: string;
  stateCode?: string;
  layer?: number;
  sources?: string[];
  actions?: string[];
}): void {
  try {
    // Guard against sensitive data (simple regex heuristics)
    const textBlob = `${entry.question} ${entry.answer}`;
    const hasEmail = /[\w.-]+@[\w.-]+\.[A-Za-z]{2,}/.test(textBlob);
    const hasPhone = /\+?\d[\d\s().-]{8,}/.test(textBlob);
    const hasCard = /\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b/.test(textBlob);
    const hasSSN = /\b\d{3}-\d{2}-\d{4}\b/.test(textBlob);
    if (hasEmail || hasPhone || hasCard || hasSSN) {
      return; // skip storing sensitive-looking content
    }

    if (!fs.existsSync(AUTO_CACHE_DIR)) {
      fs.mkdirSync(AUTO_CACHE_DIR, { recursive: true });
    }

    let corpus: any[] = [];
    if (fs.existsSync(CHAT_CORPUS_FILE)) {
      try {
        const raw = fs.readFileSync(CHAT_CORPUS_FILE, "utf-8");
        corpus = JSON.parse(raw);
      } catch {
        corpus = [];
      }
    }

    // Deduplicate by normalized question text
    const normalizedQuestion = entry.question.trim().toLowerCase();
    const exists = corpus.some((item) =>
      typeof item.question === "string" && item.question.trim().toLowerCase() === normalizedQuestion
    );
    if (exists) return;

    corpus.push({
      question: entry.question,
      answer: entry.answer,
      layer: entry.layer,
      sources: entry.sources,
      actions: entry.actions,
      countyCode: entry.countyCode,
      stateCode: entry.stateCode,
      timestamp: new Date().toISOString(),
    });

    fs.writeFileSync(CHAT_CORPUS_FILE, JSON.stringify(corpus, null, 2), "utf-8");
  } catch (error) {
    console.error("Error appending chat knowledge:", error);
  }
}

/**
 * LAYER 1: Check manual admin overrides
 * Highest priority - admin-controlled facts that override everything
 */
function checkManualOverrides(message: string, countyCode?: string): CacheResult {
  // Check response overrides
  const overrides = readCacheFile("overrides.json", true);
  if (overrides?.responseOverrides) {
    for (const [key, value] of Object.entries(overrides.responseOverrides)) {
      if (message.toLowerCase().includes(key.toLowerCase())) {
        return {
          source: "manual",
          data: { override: true, response: value },
          layer: 1,
        };
      }
    }

    // Check forced facts
    if (overrides?.forcedFacts) {
      for (const [key, fact] of Object.entries(overrides.forcedFacts)) {
        if (message.toLowerCase().includes(key.toLowerCase())) {
          return {
            source: "manual",
            data: { fact: true, content: fact },
            layer: 1,
          };
        }
      }
    }
  }

  // Check county-specific overrides
  if (countyCode) {
    const countyFile = `county_overrides/${countyCode.toUpperCase()}.json`;
    const countyData = readCacheFile(countyFile, true);
    if (countyData) {
      return {
        source: "manual",
        data: countyData,
        layer: 1,
      };
    }
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * LAYER 2: Auto-generated cache (crawler data)
 * Primary knowledge source - updated every 5 minutes
 */
function readAutoCache(category: string): CacheResult {
  const cacheFile = category.toLowerCase();
  const data = readCacheFile(`${cacheFile}.json`, false);

  if (data && data.status !== "cache initialized") {
    return {
      source: "auto",
      data: data.items || data,
      timestamp: data.lastUpdated,
      itemCount: Array.isArray(data.items) ? data.items.length : 0,
      layer: 2,
    };
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * LAYER 3: Query live website database
 * Fallback when cache is insufficient
 */
async function queryWebsite(
  message: string,
  userId?: string,
  countyCode?: string
): Promise<CacheResult> {
  try {
    const messageLower = message.toLowerCase();
    let result: any = null;

    // Detect category from message
    if (
      messageLower.includes("contractor") ||
      messageLower.includes("roofer") ||
      messageLower.includes("plumber") ||
      messageLower.includes("electrician") ||
      messageLower.includes("hvac")
    ) {
      const contractors = await db.query.contractors.findMany({
        where: countyCode ? ((c: any) => c.countyCode.equals(countyCode)) : undefined,
        limit: 10,
      });
      result = {
        category: "contractors",
        items: contractors.map((c: any) => ({
          id: c.id,
          name: c.name,
          trades: c.trades,
          verified: c.verified,
          rating: c.rating,
          countyCode: c.countyCode,
          stateCode: c.stateCode,
        })),
      };
    } else if (
      messageLower.includes("listing") ||
      messageLower.includes("sell") ||
      messageLower.includes("buy") ||
      messageLower.includes("item") ||
      messageLower.includes("marketplace")
    ) {
      const listings = await db.query.marketplaceListings.findMany({
        where: countyCode ? ((m: any) => m.countyCode.equals(countyCode)) : undefined,
        limit: 10,
      });
      result = {
        category: "marketplace",
        items: listings.map((m: any) => ({
          id: m.id,
          title: m.title,
          price: m.price,
          description: m.description,
          countyCode: m.countyCode,
          stateCode: m.stateCode,
          createdAt: m.createdAt,
        })),
      };
    } else if (
      messageLower.includes("group") ||
      messageLower.includes("community") ||
      messageLower.includes("club")
    ) {
      const groups = await db.query.communityGroups.findMany({
        where: countyCode ? ((g: any) => g.countyCode.equals(countyCode)) : undefined,
        limit: 10,
      });
      result = {
        category: "groups",
        items: groups.map((g: any) => ({
          id: g.id,
          name: g.name,
          description: g.description,
          members: g.members,
          countyCode: g.countyCode,
          stateCode: g.stateCode,
        })),
      };
    } else if (messageLower.includes("hoa")) {
      const hoaData = await db.query.homeownerAssociations.findMany({
        where: countyCode ? ((h: any) => h.countyCode.equals(countyCode)) : undefined,
        limit: 10,
      });
      result = {
        category: "hoa",
        items: hoaData.map((h: any) => ({
          id: h.id,
          name: h.name,
          budget: h.budget,
          rulesPublic: h.rulesPublic,
          countyCode: h.countyCode,
          stateCode: h.stateCode,
        })),
      };
    } else if (messageLower.includes("county") || messageLower.includes("area")) {
      const counties = await db.query.counties.findMany({
        where: countyCode ? ((c: any) => c.countyCode.equals(countyCode)) : undefined,
      });
      result = {
        category: "counties",
        items: counties.map((c: any) => ({
          countyCode: c.countyCode,
          stateCode: c.stateCode,
          name: c.name,
          population: c.population,
          climate: c.climate,
        })),
      };
    }

    if (result && result.items?.length > 0) {
      return {
        source: "database",
        data: result,
        itemCount: result.items.length,
        layer: 3,
      };
    }
  } catch (error) {
    console.error("Database query error:", error);
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * LAYER 4: Search internet (last resort)
 * Only when all other layers insufficient
 */
async function searchInternet(
  gemini: GoogleGenerativeAI | null,
  message: string
): Promise<CacheResult> {
  try {
    if (!gemini) return { source: "none", data: null, layer: 0 };

    // Use stable model name; "-latest" can 404 on some API versions
    const model = gemini.getGenerativeModel({ model: "gemini-1.5-flash" });
    const result = await model.generateContent(
      `Search the web and provide accurate information about: ${message}`
    );

    if (result.response.text()) {
      return {
        source: "internet",
        data: { content: result.response.text() },
        layer: 4,
      };
    }
  } catch (error) {
    console.error("Internet search error:", error);
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * Main resolver: 4-layer strict knowledge resolution
 * NEVER invents data. NEVER uses mocks in production.
 * Priority: Admin Cache → Website Data (Cache + DB) → Internet Search → Honest "I don't know"
 */
export async function resolveKnowledge(
  request: KnowledgeRequest,
  gemini: GoogleGenerativeAI | null
): Promise<KnowledgeResponse> {
  const { message, userId, countyCode, stateCode } = request;
  const sources: string[] = [];

  // LAYER 1: Manual Admin Overrides (Highest Authority)
  // If admin has set a rule, local guide, or override → use it exactly
  const manualResult = checkManualOverrides(message, countyCode);
  if (manualResult.source !== "none" && manualResult.data) {
    if (manualResult.data.override) {
      sources.push("Admin Manual Override");
      return {
        answer: manualResult.data.response,
        sources,
        layer: 1,
        confidence: "high",
      };
    }
    if (manualResult.data.fact) {
      sources.push("Admin Forced Fact");
      return {
        answer: manualResult.data.content,
        sources,
        layer: 1,
        confidence: "high",
      };
    }
    // County-specific admin data
    sources.push(`Admin County Override (${countyCode})`);
    return {
      answer: JSON.stringify(manualResult.data, null, 2),
      sources,
      layer: 1,
      confidence: "high",
    };
  }

  // LAYER 1B: Curated knowledge base in data/TradeScout Brain (docx/txt/md)
  const knowledgeBaseResult = await searchLocalKnowledgeBase(message);
  if (knowledgeBaseResult.source === "manual" && Array.isArray(knowledgeBaseResult.data)) {
    sources.push("TradeScout Brain (data folder)");
    const formatted = knowledgeBaseResult.data
      .map((item: any) => `${item.file}\n${item.snippet}`)
      .join("\n\n---\n\n")
      .slice(0, 3000);

    return {
      answer: formatted,
      sources,
      layer: 1,
      confidence: "high",
    };
  }

  // LAYER 2: Website Data (Auto-Generated Cache + Database)
  // Check cache first (faster), then DB if needed
  let category = detectCategory(message);
  
  // Try auto-generated cache
  const cacheResult = readAutoCache(category);
  if (cacheResult.source !== "none" && cacheResult.data && Array.isArray(cacheResult.data) && cacheResult.data.length > 0) {
    sources.push(`TradeScout Cache (${category})`);
    return {
      answer: JSON.stringify(cacheResult.data, null, 2).slice(0, 3000),
      sources,
      layer: 2,
      confidence: "high",
    };
  }

  // Try live database query
  const dbResult = await queryWebsite(message, userId, countyCode);
  if (dbResult.source === "database" && dbResult.data?.items?.length > 0) {
    sources.push(`TradeScout Database (${dbResult.data.category})`);
    return {
      answer: JSON.stringify(dbResult.data.items, null, 2).slice(0, 3000),
      sources,
      layer: 2,
      confidence: "high",
    };
  }

  // LAYER 3: Internet Search (Only when local data doesn't exist)
  // Use real web sources - DO NOT invent local businesses, prices, or county rules
  const internetResult = await searchInternet(gemini, message);
  if (internetResult.source === "internet" && internetResult.data?.content) {
    sources.push("Internet Search (Not Local TradeScout Data)");
    return {
      answer: internetResult.data.content,
      sources,
      layer: 3,
      confidence: "medium",
    };
  }

  // LAYER 4: Total Failure (Honest "I don't know")
  // No mocks, no examples, no made-up data
  return {
    answer: "I couldn't find reliable information about this in TradeScout's local data or on the web. You may need to confirm with a local professional or contact your admin for assistance.",
    sources: ["No reliable source found"],
    layer: 4,
    confidence: "low",
  };
}

/**
 * Detect category from user message
 */
function detectCategory(message: string): string {
  const lower = message.toLowerCase();
  
  if (lower.includes("contractor") || lower.includes("roofer") || 
      lower.includes("plumber") || lower.includes("electrician") || 
      lower.includes("hvac") || lower.includes("handyman")) {
    return "contractors";
  }
  if (lower.includes("group") || lower.includes("community") || lower.includes("club")) {
    return "groups";
  }
  if (lower.includes("hoa") || lower.includes("homeowner") || lower.includes("association")) {
    return "hoa";
  }
  if (lower.includes("county") || lower.includes("area") || lower.includes("region")) {
    return "counties";
  }
  return "marketplace";
}

/**
 * Get local guide (county-specific hyperlocal info)
 */
export function getLocalGuide(county: string, state: string): CacheResult {
  const filename = `${state.toUpperCase()}_${county.replace(/\s+/g, "_").toUpperCase()}.json`;

  // Check manual local guides
  const localGuide = readCacheFile(`county_overrides/${filename}`, true);
  if (localGuide) {
    return {
      source: "manual",
      data: localGuide,
    };
  }

  return {
    source: "none",
    data: null,
  };
}

/**
 * Get local markdown guide (e.g., roofing_houston.md)
 */
export function getLocalMarkdownGuide(topic: string, county: string): string | null {
  try {
    const filename = `${topic}_${county.toLowerCase().replace(/\s+/g, "_")}.md`;
    const dir = path.join(MANUAL_CACHE_DIR, "local_guides");
    const filepath = path.join(dir, filename);

    if (fs.existsSync(filepath)) {
      return fs.readFileSync(filepath, "utf-8");
    }
  } catch (error) {
    console.error(`Error reading local guide ${topic}/${county}:`, error);
  }

  return null;
}
