import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { and, eq, or, sql } from "drizzle-orm";
import mammoth from "mammoth";
import { db } from ".././db";
import { storage } from "../storage";
import { chooseKnowledgeMode } from "../scout/brandGuard";
import { webSearch, type WebSearchResult } from "./webSearchService";
import { observeScoutHybridShadow, searchScoutHybridCutover } from "./scoutHybridShadowService";
import {
  AUTOMATIC_CHAT_CORPUS_WRITES_ENABLED,
  GENERATED_SCOUT_CORPUS_RETRIEVAL_ENABLED,
  getScoutCorpusContainmentStatus,
} from "./scoutCorpusContainment";
import { businesses, businessCounties, counties, users } from "../../shared/schema";
import { publicBusinessDetailExposureSqlPredicate } from "../publicationBusiness";
import { runtimePaths } from "../runtimePaths";

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function findRepoRoot(startDir: string): string | null {
  // Walk up until we find package.json. This avoids brittle __dirname-relative paths
  // that break once compiled to dist/ in production.
  let current = path.resolve(startDir);
  for (let i = 0; i < 10; i++) {
    const pkg = path.join(current, "package.json");
    if (fs.existsSync(pkg)) return current;
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  return null;
}

function resolveRepoRoot(): string {
  return (
    findRepoRoot(process.cwd()) ??
    findRepoRoot(__dirname) ??
    // Last resort: keep behavior close to prior layout.
    path.resolve(__dirname, "..", "..")
  );
}

const REPO_ROOT = resolveRepoRoot();
const AUTO_CACHE_DIR = runtimePaths.scoutAutogeneratedCache;
const MANUAL_CACHE_DIR = runtimePaths.scoutManualCache;
const KNOWLEDGE_BASE_DIR = path.join(REPO_ROOT, "data", "TradeScout Brain");
const DEFAULT_KNOWLEDGE_DIRS = [KNOWLEDGE_BASE_DIR, path.join(REPO_ROOT, "docs")].join(",");
const KNOWLEDGE_ROOT_DIRS = String(process.env.SCOUT_KNOWLEDGE_DIRS || DEFAULT_KNOWLEDGE_DIRS)
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean)
  .map((p) => (path.isAbsolute(p) ? p : path.join(REPO_ROOT, p)));
const CHAT_CORPUS_FILE = path.join(AUTO_CACHE_DIR, "chat_corpus.json");
const KNOWLEDGE_EXTENSIONS = new Set([".md", ".txt", ".docx"]);
const knowledgeTextCache: Record<string, { mtimeMs: number; text: string }> = {};

interface CacheResult {
  source: "manual" | "auto" | "database" | "internet" | "none";
  data: any;
  timestamp?: string;
  itemCount?: number;
  layer?: number;
}

interface KnowledgeRequest {
  message: string;
  userId?: string;
  countyCode?: string;
  stateCode?: string;
}

export interface KnowledgeSource {
  title: string;
  url?: string;
  type?: string;
  provider?: string;
}

export type KnowledgeSourceReference = string | KnowledgeSource;

interface KnowledgeResponse {
  answer: string;
  sources: KnowledgeSourceReference[];
  layer: 1 | 2 | 3 | 4;
  confidence: "high" | "medium" | "low";
  meta?: {
    communityPosts?: { count: number };
    contractors?: { count: number };
  };
}

interface InternetFallbackDecisionInput {
  message: string;
  mode: ReturnType<typeof chooseKnowledgeMode>;
  sources: KnowledgeSourceReference[];
  meta: KnowledgeResponse["meta"];
  hasManualOverride: boolean;
}

export function shouldUseInternetFallback(input: InternetFallbackDecisionInput): boolean {
  const { message, mode, sources, meta, hasManualOverride } = input;

  if (hasManualOverride) return false;
  if (mode !== "kb_site_then_web") return false;

  const lower = message.toLowerCase();
  // Codes, permits, inspections, zoning, and tax rules are authority- and
  // freshness-sensitive. A matching internal guide is useful context, but it
  // is not enough by itself to claim the current rule for a jurisdiction.
  if (isCodeOrPermitQuery(lower) || isTaxQuery(lower)) return true;

  const isExternalDiscoveryQuery =
    /\b(find|looking for|near me|best|compare|review|quote|estimate|price|cost|contractor|roofer|plumber|electrician|hvac|handyman|service)\b/.test(
      lower
    );

  if (!isExternalDiscoveryQuery) {
    return false;
  }

  const hasWebsiteData = sources.some((source) => {
    const title = typeof source === "string" ? source : source.title;
    return title.startsWith("TradeScout Cache") || title.startsWith("TradeScout Database");
  });
  const localSupplyCount = Math.max(
    meta?.contractors?.count ?? 0,
    meta?.communityPosts?.count ?? 0
  );
  const hasHealthyLocalSupply = localSupplyCount >= 3;

  const hasOnlyKnowledgeDocs =
    sources.length > 0 &&
    sources.every((source) => {
      const title = typeof source === "string" ? source : source.title;
      return (
        title === "TradeScout Brain (data folder)" ||
        title.startsWith("Admin ") ||
        title.startsWith("Admin County Override")
      );
    });

  if (hasOnlyKnowledgeDocs) {
    return true;
  }

  return !hasWebsiteData || !hasHealthyLocalSupply;
}

/**
 * Read a cached JSON file
 */
function readCacheFile(filename: string, isManual = false): any | null {
  try {
    const dir = isManual ? MANUAL_CACHE_DIR : AUTO_CACHE_DIR;
    const filepath = path.join(dir, filename);

    if (!fs.existsSync(filepath)) {
      return null;
    }

    const content = fs.readFileSync(filepath, "utf-8");
    return JSON.parse(content);
  } catch (error) {
    console.error(`Error reading cache ${filename}:`, error);
    return null;
  }
}

function walkKnowledgeFiles(dir: string): string[] {
  const files: string[] = [];
  if (!fs.existsSync(dir)) return files;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkKnowledgeFiles(fullPath));
    } else if (KNOWLEDGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      files.push(fullPath);
    }
  }
  return files;
}

async function loadKnowledgeText(filePath: string): Promise<string | null> {
  try {
    const stats = fs.statSync(filePath);
    const cached = knowledgeTextCache[filePath];
    if (cached && cached.mtimeMs === stats.mtimeMs) {
      return cached.text;
    }

    const ext = path.extname(filePath).toLowerCase();
    let text: string | null = null;

    if (ext === ".docx") {
      const result = await mammoth.extractRawText({ path: filePath });
      text = result.value;
    } else {
      text = fs.readFileSync(filePath, "utf-8");
    }

    const clean = text?.trim();
    if (clean) {
      knowledgeTextCache[filePath] = { mtimeMs: stats.mtimeMs, text: clean };
      return clean;
    }
  } catch (error) {
    console.error(`Error loading knowledge file ${filePath}:`, error);
  }

  return null;
}

function buildSnippet(text: string, terms: string[]): string {
  const lower = text.toLowerCase();
  const term = terms.find((t) => lower.includes(t));
  if (!term) {
    return text.slice(0, 600);
  }

  const idx = lower.indexOf(term);
  const start = Math.max(0, idx - 200);
  const end = Math.min(text.length, idx + 800);
  return text.slice(start, end);
}

async function searchLocalKnowledgeBase(
  message: string,
  countyCode?: string,
  stateCode?: string
): Promise<CacheResult> {
  if (!GENERATED_SCOUT_CORPUS_RETRIEVAL_ENABLED) {
    return { source: "none", data: null, layer: 0 };
  }

  try {
    const strictJurisdiction = isCodeOrPermitQuery(message.toLowerCase());
    const locality = {
      countyFips: /^\d{5}$/.test(String(countyCode || "").trim())
        ? String(countyCode).trim()
        : null,
      state: /^[a-z]{2}$/i.test(String(stateCode || "").trim())
        ? String(stateCode).trim().toUpperCase()
        : null,
    };
    const hybridQuery = {
      text: message,
      kind: "knowledge" as const,
      locality,
      strictLocality: strictJurisdiction && Boolean(locality.countyFips || locality.state),
      requireCountyMatch: strictJurisdiction && Boolean(locality.countyFips),
      limit: 10,
    };
    const cutoverResults = await searchScoutHybridCutover({ query: hybridQuery });
    if (cutoverResults?.length) {
      return {
        source: "manual",
        data: cutoverResults.slice(0, 3).map((result) => ({
          file: result.title,
          snippet: result.snippet,
          score: result.score,
          sourceUrl: result.sourceUrl,
          sourceId: result.id,
        })),
        itemCount: Math.min(3, cutoverResults.length),
        layer: 1,
      };
    }

    const existingRoots = KNOWLEDGE_ROOT_DIRS.filter((dir) => {
      try {
        return fs.existsSync(dir);
      } catch {
        return false;
      }
    });

    if (!existingRoots.length) {
      return { source: "none", data: null, layer: 0 };
    }

    const filesByRoot: Array<{ root: string; file: string }> = [];
    for (const root of existingRoots) {
      const files = walkKnowledgeFiles(root);
      for (const file of files) {
        filesByRoot.push({ root, file });
      }
    }

    if (!filesByRoot.length) {
      return { source: "none", data: null, layer: 0 };
    }

    const terms = message
      .toLowerCase()
      .split(/\s+/)
      .map((t) => t.trim())
      .filter((t) => t.length > 3);

    const matches: Array<{ file: string; snippet: string; score: number }> = [];

    for (const item of filesByRoot) {
      const text = await loadKnowledgeText(item.file);
      if (!text) continue;

      const lower = text.toLowerCase();
      let score = 0;
      for (const term of terms) {
        if (lower.includes(term)) {
          score += 1;
        }
      }

      if (score > 0) {
        const rootLabel = path.basename(item.root);
        matches.push({
          file: `[${rootLabel}] ${path.relative(item.root, item.file)}`,
          snippet: buildSnippet(text, terms),
          score,
        });
      }
    }

    matches.sort((a, b) => b.score - a.score);
    const top = matches.slice(0, 3);
    void observeScoutHybridShadow({
      query: hybridQuery,
      legacyIds: top.map((match) => match.file),
    });

    if (top.length) {
      return {
        source: "manual",
        data: top,
        itemCount: top.length,
        layer: 1,
      };
    }
  } catch (error) {
    console.error("Local knowledge search error:", error);
  }

  return { source: "none", data: null, layer: 0 };
}

function isCodeOrPermitQuery(lower: string): boolean {
  return /\b(code|building code|permit|permitting|inspection|inspector|zoning|setback|occupancy|egress|fire\s*safety|smoke\s*alarm|carbon\s*monoxide|electrical|panel|breaker|gfci|afci|receptacle|outlet|subpanel|service\s*entrance|plumbing|drain|sewer|cleanout|trap|vent|slope|foundation|slab|footing|framing|joist|beam|header|stair|handrail|guardrail|deck)\b/.test(
    lower
  );
}

function isTaxQuery(lower: string): boolean {
  return /\b(tax|property\s*tax|assessment|assessed\s*value|mill\s*rate|valuation|homestead|escrow|tax\s*lien|delinquent\s*tax|tax\s*sale|foreclosure)\b/.test(
    lower
  );
}

/**
 * Write/update a manual knowledge JSON file
 */
export function writeManualCacheFile(filename: string, data: any): void {
  try {
    if (!fs.existsSync(MANUAL_CACHE_DIR)) {
      fs.mkdirSync(MANUAL_CACHE_DIR, { recursive: true });
    }
    const filepath = path.join(MANUAL_CACHE_DIR, filename);
    fs.writeFileSync(filepath, JSON.stringify(data, null, 2), "utf-8");
  } catch (error) {
    console.error(`Error writing manual cache ${filename}:`, error);
    throw error;
  }
}

/**
 * Compatibility shim for the retired automatic chat-corpus write path.
 * Generated Scout answers must not become retrieval evidence.
 */
export { AUTOMATIC_CHAT_CORPUS_WRITES_ENABLED };

export function appendChatKnowledge(_entry: {
  question: string;
  answer: string;
  userId?: string;
  countyCode?: string;
  stateCode?: string;
  layer?: number;
  sources?: KnowledgeSourceReference[];
  actions?: string[];
}): { appended: false; reason: "automatic_corpus_writes_disabled" } {
  // Production hardening: generated answers are never allowed to write
  // themselves into Scout's global retrieval corpus. A future reviewed
  // ingestion lane may replace this compatibility function, but it must
  // require sanitization, provenance, approval, and an explicit authority.
  return {
    appended: false,
    reason: "automatic_corpus_writes_disabled",
  };
}

function searchChatCorpus(message: string, countyCode?: string, stateCode?: string): CacheResult {
  if (!GENERATED_SCOUT_CORPUS_RETRIEVAL_ENABLED) {
    return { source: "none", data: null, layer: 0 };
  }

  try {
    if (!fs.existsSync(CHAT_CORPUS_FILE)) {
      return { source: "none", data: null, layer: 0 };
    }

    const raw = fs.readFileSync(CHAT_CORPUS_FILE, "utf-8");
    const corpus = JSON.parse(raw);
    if (!Array.isArray(corpus) || corpus.length === 0) {
      return { source: "none", data: null, layer: 0 };
    }

    const lowerMessage = message.toLowerCase();
    const terms = lowerMessage
      .split(/\s+/)
      .map((t) => t.replace(/[^a-z0-9]/gi, "").trim())
      .filter((t) => t.length >= 4);

    if (!terms.length) {
      return { source: "none", data: null, layer: 0 };
    }

    let best: any = null;
    let bestScore = 0;

    for (const item of corpus) {
      const q = typeof item.question === "string" ? item.question.toLowerCase() : "";
      const a = typeof item.answer === "string" ? item.answer.toLowerCase() : "";

      let score = 0;
      for (const term of terms) {
        if (!term) continue;
        if (q.includes(term) || a.includes(term)) {
          score += 1;
        }
      }

      if (!score) continue;

      if (
        countyCode &&
        item.countyCode &&
        item.countyCode.toLowerCase() === countyCode.toLowerCase()
      ) {
        score += 2;
      } else if (
        stateCode &&
        item.stateCode &&
        item.stateCode.toLowerCase() === stateCode.toLowerCase()
      ) {
        score += 1;
      }

      if (score > bestScore) {
        bestScore = score;
        best = item;
      }
    }

    // Require at least a small overlap to avoid irrelevant matches
    if (!best || bestScore < 2) {
      return { source: "none", data: null, layer: 0 };
    }

    return {
      source: "auto",
      data: best,
      layer: 3,
      itemCount: 1,
    };
  } catch (error) {
    console.error("Chat corpus search error:", error);
    return { source: "none", data: null, layer: 0 };
  }
}

/**
 * LAYER 1: Check manual admin overrides
 * Highest priority - admin-controlled facts that override everything
 */
function checkManualOverrides(message: string, countyCode?: string): CacheResult {
  // Check response overrides
  const overrides = readCacheFile("overrides.json", true);
  if (overrides?.responseOverrides) {
    for (const [key, value] of Object.entries(overrides.responseOverrides)) {
      if (message.toLowerCase().includes(key.toLowerCase())) {
        return {
          source: "manual",
          data: { override: true, response: value },
          layer: 1,
        };
      }
    }

    // Check forced facts
    if (overrides?.forcedFacts) {
      for (const [key, fact] of Object.entries(overrides.forcedFacts)) {
        if (message.toLowerCase().includes(key.toLowerCase())) {
          return {
            source: "manual",
            data: { fact: true, content: fact },
            layer: 1,
          };
        }
      }
    }
  }

  // Check county-specific overrides
  if (countyCode) {
    const countyFile = `county_overrides/${countyCode.toUpperCase()}.json`;
    const countyData = readCacheFile(countyFile, true);
    if (countyData) {
      return {
        source: "manual",
        data: countyData,
        layer: 1,
      };
    }
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * LAYER 2: Auto-generated cache (crawler data)
 * Primary knowledge source - updated every 5 minutes
 */
function readAutoCache(category: string): CacheResult {
  const cacheFile = category.toLowerCase();
  const data = readCacheFile(`${cacheFile}.json`, false);

  if (data && data.status !== "cache initialized") {
    return {
      source: "auto",
      data: data.items || data,
      timestamp: data.lastUpdated,
      itemCount: Array.isArray(data.items) ? data.items.length : 0,
      layer: 2,
    };
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * LAYER 3: Query live website database
 * Fallback when cache is insufficient
 */
async function queryWebsite(
  message: string,
  userId?: string,
  countyCode?: string,
  stateCode?: string
): Promise<CacheResult> {
  try {
    const messageLower = message.toLowerCase();
    let result: any = null;

    // Detect category from message and fetch from live database when cache is thin.
    // Keep queries conservative and scoped to user's county/state when available.

    // Community posts / feed (neighbors talking, recommendations, etc.)
    if (
      messageLower.includes("post") ||
      messageLower.includes("posts") ||
      messageLower.includes("feed") ||
      messageLower.includes("neighbors") ||
      messageLower.includes("neighbours") ||
      messageLower.includes("recommendation") ||
      messageLower.includes("recommendations")
    ) {
      const filters: Parameters<typeof storage.getCommunityPosts>[0] = {
        limit: 10,
      };

      if (countyCode) {
        filters.scope = "county" as any;
        filters.countyFips = countyCode;
      } else if (stateCode) {
        filters.scope = "state" as any;
        filters.stateCode = stateCode;
      }

      const posts = await storage.getCommunityPosts(filters);

      result = {
        category: "community_posts",
        items: posts.map((p: any) => ({
          id: p.id,
          title: p.title,
          content: p.content,
          category: p.category,
          tags: p.tags,
          createdAt: p.createdAt,
          location: p.location,
          authorName: p.author?.name,
          authorRole: p.author?.role,
          likeCount: p.upvotes,
          commentCount: p.comments,
        })),
      };
    } else if (
      messageLower.includes("contractor") ||
      messageLower.includes("roofer") ||
      messageLower.includes("plumber") ||
      messageLower.includes("electrician") ||
      messageLower.includes("hvac")
    ) {
      // Contractors: prefer cache, but fall back to a thin live query if needed.
      const contractors = await db.query.contractors.findMany({
        // For now, keep this unfiltered; location scoping is handled in higher layers.
        limit: 10,
      });
      result = {
        category: "contractors",
        items: contractors.map((c: any) => ({
          id: c.id,
          companyName: c.companyName,
          yearsInBusiness: c.yearsInBusiness,
          verifiedLicensed: c.verifiedLicensed,
          verifiedInsured: c.verifiedInsured,
          recommendationScore: c.recommendationScore,
          totalRecommendations: c.totalRecommendations,
        })),
      };
    } else if (
      messageLower.includes("supplier") ||
      messageLower.includes("supply") ||
      messageLower.includes("materials") ||
      messageLower.includes("hardware") ||
      messageLower.includes("lumber") ||
      messageLower.includes("retail") ||
      messageLower.includes("store") ||
      messageLower.includes("tool") ||
      messageLower.includes("equipment rental") ||
      messageLower.includes("stone") ||
      messageLower.includes("granite") ||
      messageLower.includes("marble") ||
      messageLower.includes("quartzite") ||
      messageLower.includes("quartz") ||
      messageLower.includes("countertop") ||
      messageLower.includes("slab")
    ) {
      // Directory businesses: awareness-only. Return links to business profiles, not phone/email.
      const seen = new Set<string>();
      const rows: any[] = [];

      // Prefer county-scoped businesses (business_counties) when available.
      if (countyCode) {
        try {
          const countyRows = await db
            .select({
              id: businesses.id,
              name: businesses.name,
              slug: businesses.slug,
              type: businesses.type,
              profileData: businesses.profileData,
            })
            .from(businesses)
            .innerJoin(businessCounties, eq(businessCounties.businessId, businesses.id))
            .innerJoin(counties, eq(counties.id, businessCounties.countyId))
            .leftJoin(users, eq(users.id, businesses.ownerUserId))
            .where(
              and(
                eq(businesses.status, "active" as any),
                eq(businesses.publicDiscoveryEnabled, true),
                publicBusinessDetailExposureSqlPredicate(),
                eq(counties.fips, countyCode)
              )
            )
            .limit(15);
          for (const r of countyRows) {
            if (rows.length >= 15) break;
            if (seen.has(String(r.id))) continue;
            seen.add(String(r.id));
            rows.push(r);
          }
        } catch {
          // If joins fail for any reason, fall through to broader queries.
        }
      }

      // Fill remaining with state-scoped businesses. Prefer business_counties if present, else importExtras.state_code.
      if (rows.length < 15 && stateCode) {
        const needed = 15 - rows.length;
        try {
          const stateRows = await db
            .select({
              id: businesses.id,
              name: businesses.name,
              slug: businesses.slug,
              type: businesses.type,
              profileData: businesses.profileData,
            })
            .from(businesses)
            .leftJoin(businessCounties, eq(businessCounties.businessId, businesses.id))
            .leftJoin(counties, eq(counties.id, businessCounties.countyId))
            .leftJoin(users, eq(users.id, businesses.ownerUserId))
            .where(
              and(
                eq(businesses.status, "active" as any),
                eq(businesses.publicDiscoveryEnabled, true),
                publicBusinessDetailExposureSqlPredicate(),
                or(
                  eq(counties.stateCode, stateCode),
                  sql`coalesce(${businesses.profileData} -> 'importExtras' ->> 'state_code', '') = ${stateCode}`
                )
              )
            )
            .limit(Math.max(needed * 3, 20));
          for (const r of stateRows) {
            if (rows.length >= 15) break;
            if (seen.has(String(r.id))) continue;
            seen.add(String(r.id));
            rows.push(r);
          }
        } catch {
          // ignore
        }
      }

      // Last resort: any active businesses (kept small).
      if (rows.length < 1) {
        const anyRows = await db
          .select({
            id: businesses.id,
            name: businesses.name,
            slug: businesses.slug,
            type: businesses.type,
            profileData: businesses.profileData,
          })
          .from(businesses)
          .leftJoin(users, eq(users.id, businesses.ownerUserId))
          .where(
            and(
              eq(businesses.status, "active" as any),
              eq(businesses.publicDiscoveryEnabled, true),
              publicBusinessDetailExposureSqlPredicate()
            )
          )
          .limit(15);
        for (const r of anyRows) {
          if (rows.length >= 15) break;
          if (seen.has(String(r.id))) continue;
          seen.add(String(r.id));
          rows.push(r);
        }
      }
      result = {
        category: "businesses",
        items: rows.map((b: any) => {
          const profile: any = b.profileData || b.profile_data || {};
          return {
            id: b.id,
            name: b.name,
            businessType: b.type,
            category: profile.category || null,
            services: Array.isArray(profile.services) ? profile.services : null,
            // Keep contact gated; give a canonical on-platform link instead.
            profileUrl: b.slug ? `/business/${b.slug}` : null,
          };
        }),
      };
    } else if (
      messageLower.includes("listing") ||
      messageLower.includes("sell") ||
      messageLower.includes("buy") ||
      messageLower.includes("item") ||
      messageLower.includes("marketplace")
    ) {
      const listings = await db.query.marketplaceListings.findMany({
        limit: 10,
      });
      result = {
        category: "marketplace",
        items: listings.map((m: any) => ({
          id: m.id,
          title: m.title,
          price: m.price,
          description: m.description,
          county: m.county,
          state: m.state,
          createdAt: m.createdAt,
        })),
      };
    } else if (
      messageLower.includes("group") ||
      messageLower.includes("community") ||
      messageLower.includes("club")
    ) {
      const groups = await db.query.communityGroups.findMany({
        limit: 10,
      });
      result = {
        category: "groups",
        items: groups.map((g: any) => ({
          id: g.id,
          name: g.name,
          description: g.description,
          memberCount: g.memberCount,
          countyFips: g.countyFips,
          stateCode: g.stateCode,
        })),
      };
    } else if (messageLower.includes("hoa")) {
      const hoaData = await db.query.homeownerAssociations.findMany({
        limit: 10,
      });
      result = {
        category: "hoa",
        items: hoaData.map((h: any) => ({
          id: h.id,
          name: h.name,
          budget: h.budget,
          rulesPublic: h.rulesPublic,
          countyFips: h.countyFips,
          stateCode: h.stateCode,
        })),
      };
    } else if (messageLower.includes("county") || messageLower.includes("area")) {
      const counties = await db.query.counties.findMany({
        limit: 25,
      });
      result = {
        category: "counties",
        items: counties.map((c: any) => ({
          countyFips: c.countyFips,
          stateCode: c.stateCode,
          name: c.name,
          population: c.population,
          climate: c.climate,
        })),
      };
    }

    if (result && result.items?.length > 0) {
      return {
        source: "database",
        data: result,
        itemCount: result.items.length,
        layer: 3,
      };
    }
  } catch (error) {
    console.error("Database query error:", error);
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * LAYER 4: Search internet (last resort)
 * Only when all other layers insufficient
 */
function normalizeKnowledgeSourceUrl(value: unknown): string | undefined {
  if (typeof value !== "string" || value.trim().length === 0) return undefined;

  try {
    const parsed = new URL(value.trim());
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return undefined;
    return parsed.toString();
  } catch {
    return undefined;
  }
}

export function buildInternetKnowledgeSources(
  result: Pick<WebSearchResult, "provider" | "sources">
): KnowledgeSource[] {
  const sources = Array.isArray(result.sources) ? result.sources : [];
  const normalized: KnowledgeSource[] = [];
  const seen = new Set<string>();

  for (const source of sources) {
    if (!source || typeof source !== "object") continue;
    const url = normalizeKnowledgeSourceUrl(source.url);
    if (!url) continue;
    const type = typeof source.type === "string" ? source.type.trim() : "";
    const title =
      typeof source.title === "string" && source.title.trim().length > 0
        ? source.title.trim()
        : url;
    if (!title) continue;

    const key = `${title}\n${url || ""}`;
    if (seen.has(key)) continue;
    seen.add(key);
    normalized.push({
      title,
      url,
      ...(type ? { type } : { type: "internet" }),
      ...(typeof source.provider === "string" && source.provider.trim()
        ? { provider: source.provider.trim() }
        : typeof result.provider === "string" && result.provider.trim()
          ? { provider: result.provider.trim() }
          : {}),
    });
  }
  return normalized;
}

export function hasCitableInternetSource(sources: KnowledgeSourceReference[]): boolean {
  return sources.some(
    (source) => typeof source !== "string" && Boolean(normalizeKnowledgeSourceUrl(source?.url))
  );
}

async function searchInternet(
  _gemini: GoogleGenerativeAI | null,
  message: string,
  countyCode?: string,
  stateCode?: string
): Promise<CacheResult> {
  try {
    if (!process.env.OPENAI_API_KEY) {
      return { source: "none", data: null, layer: 0 };
    }
    const lower = message.toLowerCase();

    const codeOrPermit = isCodeOrPermitQuery(lower);
    const taxQuery = isTaxQuery(lower);

    const localityHint = [countyCode, stateCode].filter(Boolean).join(", ");

    const authorityInstruction =
      codeOrPermit || taxQuery
        ? "Use the applicable official county, municipal, state, tax, or building-code authority."
        : "Prefer official or authoritative sources.";
    const query = [message, localityHint ? `Location: ${localityHint}.` : "", authorityInstruction]
      .filter(Boolean)
      .join("\n");
    try {
      const result = await webSearch(query, 5);
      if (result.success && result.content) {
        const internetSources = buildInternetKnowledgeSources(result);
        if (!hasCitableInternetSource(internetSources)) {
          console.warn("Citation-capable search returned no valid provider source");
        } else {
          return {
            source: "internet",
            data: {
              content: result.content,
              sources: internetSources,
              provider: result.provider,
            },
            layer: 4,
          };
        }
      }
    } catch (error) {
      console.error("Citation-capable internet search error:", error);
    }
  } catch (error) {
    console.error("Internet search error:", error);
  }

  return { source: "none", data: null, layer: 0 };
}

/**
 * Main resolver: 4-layer aggregated knowledge resolution
 * Combines information from ALL relevant sources instead of stopping at first match
 * NEVER invents data. NEVER uses mocks in production.
 * Priority: Admin Cache → Website Data (Cache + DB) → Internet Search → Honest "I don't know"
 */
export async function resolveKnowledge(
  request: KnowledgeRequest,
  gemini: GoogleGenerativeAI | null
): Promise<KnowledgeResponse> {
  const { message, userId, countyCode, stateCode } = request;
  const sources: KnowledgeSourceReference[] = [];
  const aggregatedContent: string[] = [];
  let highestLayer = 4;
  let hasManualOverride = false;
  const meta: KnowledgeResponse["meta"] = {};
  const mode = chooseKnowledgeMode(message);

  // LAYER 1: Manual Admin Overrides (Highest Authority)
  // If admin has set a rule, local guide, or override → use it exactly and STOP
  const manualResult = checkManualOverrides(message, countyCode);
  if (manualResult.source !== "none" && manualResult.data) {
    if (manualResult.data.override) {
      sources.push("Admin Manual Override");
      return {
        answer: manualResult.data.response,
        sources,
        layer: 1,
        confidence: "high",
      };
    }
    if (manualResult.data.fact) {
      sources.push("Admin Forced Fact");
      aggregatedContent.push(`ADMIN FACT:\n${manualResult.data.content}`);
      highestLayer = 1;
      hasManualOverride = true;
    }
    // County-specific admin data
    if (manualResult.data.override === undefined && manualResult.data.fact === undefined) {
      sources.push(`Admin County Override (${countyCode})`);
      aggregatedContent.push(`ADMIN COUNTY DATA:\n${JSON.stringify(manualResult.data, null, 2)}`);
      highestLayer = 1;
    }
  }

  // LAYER 1B: Generated/unverified disk knowledge. The containment policy
  // keeps this path empty until reviewed source validation exists.
  const knowledgeBaseResult = await searchLocalKnowledgeBase(message, countyCode, stateCode);
  if (
    knowledgeBaseResult.source === "manual" &&
    Array.isArray(knowledgeBaseResult.data) &&
    knowledgeBaseResult.data.length > 0
  ) {
    const linkedSources = knowledgeBaseResult.data
      .filter(
        (item: any) => typeof item?.sourceUrl === "string" && item.sourceUrl.startsWith("http")
      )
      .map((item: any) => ({
        title: String(item.file || item.sourceId || "TradeScout knowledge"),
        url: String(item.sourceUrl),
        type: "reviewed",
        provider: "TradeScout",
      }));
    if (linkedSources.length) {
      sources.push(...linkedSources);
    } else {
      sources.push("TradeScout Brain (data folder)");
    }
    const formatted = knowledgeBaseResult.data
      .map((item: any) => `SOURCE: ${item.file}\n${item.snippet}`)
      .join("\n\n---\n\n");
    aggregatedContent.push(`KNOWLEDGE BASE:\n${formatted}`);
    highestLayer = Math.min(highestLayer, 1);
  }

  // LAYER 2: First-party website intelligence (auto-generated cache + live database)
  // Scout should reason over what exists on the site right now.
  // Check cache first (faster), then DB if needed.
  const category = detectCategory(message);

  // Try auto-generated cache
  const cacheResult = readAutoCache(category);
  if (
    cacheResult.source !== "none" &&
    cacheResult.data &&
    Array.isArray(cacheResult.data) &&
    cacheResult.data.length > 0
  ) {
    sources.push(`TradeScout Cache (${category})`);
    aggregatedContent.push(
      `CACHED DATA (${category}):\n${JSON.stringify(cacheResult.data, null, 2)}`
    );
    if (category === "contractors" && typeof cacheResult.itemCount === "number") {
      meta.contractors = { count: cacheResult.itemCount };
    }
    highestLayer = Math.min(highestLayer, 2);
  }

  // Try live database query
  const dbResult = await queryWebsite(message, userId, countyCode, stateCode);
  if (dbResult.source === "database" && dbResult.data?.items?.length > 0) {
    sources.push(`TradeScout Database (${dbResult.data.category})`);
    aggregatedContent.push(
      `DATABASE (${dbResult.data.category}):\n${JSON.stringify(dbResult.data.items, null, 2)}`
    );
    const count =
      typeof dbResult.itemCount === "number"
        ? dbResult.itemCount
        : Array.isArray(dbResult.data.items)
          ? dbResult.data.items.length
          : 0;
    if (dbResult.data.category === "community_posts") {
      meta.communityPosts = { count, items: dbResult.data.items } as any;
    }
    if (dbResult.data.category === "contractors") {
      meta.contractors = { count } as any;
    }
    highestLayer = Math.min(highestLayer, 2);
  }

  // If we have enough content from Layers 1-2, return it (no need to hit the wider web)
  if (aggregatedContent.length > 0) {
    const shouldFallbackToInternet = shouldUseInternetFallback({
      message,
      mode,
      sources,
      meta,
      hasManualOverride,
    });

    if (shouldFallbackToInternet) {
      const internetResult = await searchInternet(gemini, message, countyCode, stateCode);
      if (internetResult.source === "internet" && internetResult.data?.content) {
        return {
          answer: String(internetResult.data.content),
          sources: [
            ...sources,
            ...(Array.isArray(internetResult.data.sources)
              ? internetResult.data.sources
              : buildInternetKnowledgeSources({ provider: internetResult.data.provider })),
          ],
          layer: 3,
          confidence: "medium",
          meta,
        };
      }
    }

    // Combine all sources and truncate to reasonable size
    const combinedAnswer = aggregatedContent.join("\n\n========\n\n").slice(0, 5000);
    return {
      answer: combinedAnswer,
      sources,
      layer: highestLayer as 1 | 2 | 3 | 4,
      confidence: highestLayer === 1 ? "high" : "high",
      meta,
    };
  }

  // LAYER 3A: Thin retrieval over chat corpus for repeat code/tax questions
  const lower = message.toLowerCase();
  if (isCodeOrPermitQuery(lower) || isTaxQuery(lower)) {
    const chatResult = searchChatCorpus(message, countyCode, stateCode);
    if (chatResult.source === "auto" && chatResult.data?.answer) {
      sources.push("Chat Corpus (similar prior question)");
      return {
        answer: String(chatResult.data.answer),
        sources,
        layer: 3,
        confidence: "medium",
      };
    }
  }

  // LAYER 3: Hyperlocal internet search (only when internal knowledge is insufficient)
  // Use real web sources - DO NOT invent local businesses, prices, or county rules.
  // Location (county/state) must be used when available and answers should be framed as "here's what I found locally".
  if (mode === "kb_site_then_web") {
    const internetResult = await searchInternet(gemini, message, countyCode, stateCode);
    if (internetResult.source === "internet" && internetResult.data?.content) {
      sources.push(
        ...(Array.isArray(internetResult.data.sources)
          ? internetResult.data.sources
          : buildInternetKnowledgeSources({ provider: internetResult.data.provider }))
      );
      return {
        answer: internetResult.data.content,
        sources,
        layer: 3,
        confidence: "medium",
      };
    }
  }

  // LAYER 4: Total Failure (Honest "I don't know")
  // No mocks, no examples, no made-up data
  return {
    answer:
      "I do not have enough verified data to answer this directly right now. I can still move this forward with one concrete next step inside TradeScout.",
    sources: ["No reliable source found"],
    layer: 4,
    confidence: "low",
  };
}

/**
 * Detect category from user message
 */
function detectCategory(message: string): string {
  const lower = message.toLowerCase();

  // Public / marketplace profiles (profile pages, pro cards, seller pages)
  if (
    lower.includes("public profile") ||
    (lower.includes("profile") &&
      (lower.includes("page") ||
        lower.includes("site") ||
        lower.includes("url") ||
        lower.includes("link"))) ||
    lower.includes("pro card")
  ) {
    return "profiles_public";
  }

  if (
    lower.includes("contractor") ||
    lower.includes("roofer") ||
    lower.includes("plumber") ||
    lower.includes("electrician") ||
    lower.includes("hvac") ||
    lower.includes("handyman")
  ) {
    return "contractors";
  }
  if (
    lower.includes("supplier") ||
    lower.includes("supply") ||
    lower.includes("materials") ||
    lower.includes("hardware store") ||
    lower.includes("lumber") ||
    lower.includes("tool") ||
    lower.includes("equipment rental") ||
    lower.includes("retailer") ||
    lower.includes("store")
  ) {
    return "businesses";
  }
  if (lower.includes("group") || lower.includes("community") || lower.includes("club")) {
    return "groups";
  }
  if (lower.includes("hoa") || lower.includes("homeowner") || lower.includes("association")) {
    return "hoa";
  }
  if (lower.includes("county") || lower.includes("area") || lower.includes("region")) {
    return "counties";
  }
  return "marketplace";
}

/**
 * Get local guide (county-specific hyperlocal info)
 */
export function getLocalGuide(county: string, state: string): CacheResult {
  const filename = `${state.toUpperCase()}_${county.replace(/\s+/g, "_").toUpperCase()}.json`;

  // Check manual local guides
  const localGuide = readCacheFile(`county_overrides/${filename}`, true);
  if (localGuide) {
    return {
      source: "manual",
      data: localGuide,
    };
  }

  return {
    source: "none",
    data: null,
  };
}

/**
 * Get local markdown guide (e.g., roofing_houston.md)
 */
export function getLocalMarkdownGuide(topic: string, county: string): string | null {
  try {
    const filename = `${topic}_${county.toLowerCase().replace(/\s+/g, "_")}.md`;
    const dir = path.join(MANUAL_CACHE_DIR, "local_guides");
    const filepath = path.join(dir, filename);

    if (fs.existsSync(filepath)) {
      return fs.readFileSync(filepath, "utf-8");
    }
  } catch (error) {
    console.error(`Error reading local guide ${topic}/${county}:`, error);
  }

  return null;
}

/**
 * Load comprehensive knowledge from ALL sources for synthesis (used when Gemini needs full context)
 * This gathers everything: admin docs, data/TradeScout Brain, manual cache, etc.
 * Returns concatenated knowledge base up to a limit
 */
export async function loadComprehensiveKnowledge(): Promise<string> {
  const chunks: string[] = [];
  const maxSize = 50000; // 50KB total

  try {
    // 1. Load all manual admin cache files
    if (fs.existsSync(MANUAL_CACHE_DIR)) {
      const manualFiles = walkKnowledgeFiles(MANUAL_CACHE_DIR);
      for (const file of manualFiles) {
        if (chunks.join("").length > maxSize) break;

        const text = await loadKnowledgeText(file);
        if (text) {
          const relPath = path.relative(MANUAL_CACHE_DIR, file);
          chunks.push(`\n[ADMIN CACHE: ${relPath}]\n${text.slice(0, 2000)}`);
        }
      }
    }

    // 2. Generated/unverified roots stay quarantined until a reviewed
    // sanitation and source-validation workflow is available.
    if (GENERATED_SCOUT_CORPUS_RETRIEVAL_ENABLED) {
      for (const root of KNOWLEDGE_ROOT_DIRS) {
        if (!fs.existsSync(root)) continue;
        const rootLabel = path.basename(root);
        const knowledgeFiles = walkKnowledgeFiles(root);
        for (const file of knowledgeFiles) {
          if (chunks.join("").length > maxSize) break;

          const text = await loadKnowledgeText(file);
          if (text) {
            const relPath = path.relative(root, file);
            chunks.push(`\n[KNOWLEDGE BASE: ${rootLabel}/${relPath}]\n${text.slice(0, 2000)}`);
          }
        }
      }
    }

    const combined = chunks.join("\n").slice(0, maxSize);
    return combined || "No comprehensive knowledge available";
  } catch (error) {
    console.error("Error loading comprehensive knowledge:", error);
    return "Error loading knowledge base";
  }
}

export function getKnowledgeBaseStatus(): {
  repoRoot: string;
  knowledgeBasePresent: boolean;
  manualCachePresent: boolean;
  autoCachePresent: boolean;
  containment: ReturnType<typeof getScoutCorpusContainmentStatus>;
} {
  const safeExists = (p: string) => {
    try {
      return fs.existsSync(p);
    } catch {
      return false;
    }
  };

  return {
    repoRoot: REPO_ROOT,
    knowledgeBasePresent: KNOWLEDGE_ROOT_DIRS.some((dir) => safeExists(dir)),
    manualCachePresent: safeExists(MANUAL_CACHE_DIR),
    autoCachePresent: safeExists(AUTO_CACHE_DIR),
    containment: getScoutCorpusContainmentStatus(),
  };
}
