import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { resolveTradeScoutRuntimePaths } from "../runtimePaths";

describe("TradeScout runtime paths", () => {
  const cwd = path.resolve("/workspace/tradescout");

  it("preserves the existing repository paths in development", () => {
    expect(resolveTradeScoutRuntimePaths({ NODE_ENV: "development" }, cwd)).toEqual({
      runtimeRoot: cwd,
      scoutCacheRoot: path.join(cwd, "server", "cache"),
      scoutManualCache: path.join(cwd, "server", "cache", "manual"),
      scoutAutogeneratedCache: path.join(cwd, "server", "cache", "autogenerated"),
      scoutHybridIndex: path.join(cwd, "data", "scout-hybrid-index.v1.json"),
      publicUploads: path.join(cwd, "public", "uploads"),
      privateUploads: path.join(cwd, "private", "uploads"),
    });
  });

  it("places production-owned runtime data under one root", () => {
    expect(resolveTradeScoutRuntimePaths({ NODE_ENV: "production" }, cwd)).toEqual({
      runtimeRoot: path.join(cwd, "runtime"),
      scoutCacheRoot: path.join(cwd, "runtime", "scout-cache"),
      scoutManualCache: path.join(cwd, "runtime", "scout-cache", "manual"),
      scoutAutogeneratedCache: path.join(cwd, "runtime", "scout-cache", "autogenerated"),
      scoutHybridIndex: path.join(cwd, "runtime", "scout-hybrid-index.v1.json"),
      publicUploads: path.join(cwd, "runtime", "uploads", "public"),
      privateUploads: path.join(cwd, "runtime", "uploads", "private"),
    });
  });

  it("honors absolute and workspace-relative environment overrides", () => {
    const resolved = resolveTradeScoutRuntimePaths(
      {
        NODE_ENV: "production",
        TRADESCOUT_RUNTIME_DIR: "var/runtime",
        SCOUT_CACHE_DIR: "/mnt/scout",
        SCOUT_MANUAL_CACHE_DIR: "var/manual",
        SCOUT_AUTOGENERATED_CACHE_DIR: "/mnt/generated",
        SCOUT_HYBRID_INDEX_PATH: "var/index.json",
        UPLOAD_DIR: "/mnt/public-uploads",
        PRIVATE_UPLOAD_DIR: "var/private-uploads",
      },
      cwd
    );

    expect(resolved).toEqual({
      runtimeRoot: path.join(cwd, "var", "runtime"),
      scoutCacheRoot: path.resolve("/mnt/scout"),
      scoutManualCache: path.join(cwd, "var", "manual"),
      scoutAutogeneratedCache: path.resolve("/mnt/generated"),
      scoutHybridIndex: path.join(cwd, "var", "index.json"),
      publicUploads: path.resolve("/mnt/public-uploads"),
      privateUploads: path.join(cwd, "var", "private-uploads"),
    });
  });

  it("does not let blank overrides replace safe defaults", () => {
    const resolved = resolveTradeScoutRuntimePaths(
      {
        NODE_ENV: "production",
        TRADESCOUT_RUNTIME_DIR: "  ",
        SCOUT_CACHE_DIR: "",
        UPLOAD_DIR: "\t",
      },
      cwd
    );

    expect(resolved.runtimeRoot).toBe(path.join(cwd, "runtime"));
    expect(resolved.scoutCacheRoot).toBe(path.join(cwd, "runtime", "scout-cache"));
    expect(resolved.publicUploads).toBe(path.join(cwd, "runtime", "uploads", "public"));
  });

  it("keeps live cache and upload consumers on the shared resolver", () => {
    const repoRoot = process.cwd();
    const consumers = [
      "server/crawler/crawl.ts",
      "server/localStorage.ts",
      "server/uploadsFallback.ts",
      "server/services/adminCacheService.ts",
      "server/services/knowledgeIngest.ts",
      "server/services/knowledgeService.ts",
      "server/services/promptService.ts",
      "server/services/scoutHybridShadowService.ts",
      "server/routes/commercial-directory.ts",
      "server/routes/hardrock.ts",
      "server/routes/promptAdmin.ts",
      "server/routes/scoutfitters.ts",
      "server/routes/worker-tasks.ts",
    ];

    for (const relativePath of consumers) {
      const source = fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
      expect(source, relativePath).toContain("runtimePaths");
      expect(source, relativePath).not.toMatch(
        /process\.env\.(?:UPLOAD_DIR|PRIVATE_UPLOAD_DIR)\s*\|\||path\.join\([^\n]*__dirname[^\n]*(?:cache|uploads)/
      );
    }
  });
});
